### PR TITLE
adding in E.sendOnly()

### PR DESCRIPTION
**Pull request by zarutian**
To bring E() syntax/convience methods into alignment closer to
what is proposed/shown in https://github.com/tc39/proposal-eventual-send

### CODE REVIEW

**Comment by zarutian** [comment]
Added only one test because, frankly I am stumped on how to check how test excercisement in the other cases.

**Comment by zarutian** [comment]
pinging @Chris-Hibbert @erights @michaelfig and @warner per git-blame.

I am in no hurry for this PR to be reviewed if you all are super busy.

**Comment by michaelfig** [comment]
> I am in no hurry for this PR to be reviewed if you all are super busy.

Thanks for your patience!

**Comment by zarutian** [comment]
Feel free to review this pull request anytime soon-ish.

**Review by michaelfig — APPROVED** [review]
LGTM!  Thanks for the contribution!

**Comment by zarutian** [comment]
I am still stumped on how to fully excercise this via tests as `E.sendOnly()` is a bit of a fire and forget functionality.

Note that this pr does not fully propagate the 'sendOnly'-ness to HandledPromise as those traps are still missing from HandledPromise at the time of this PR. But this is fine for now.

**Comment by michaelfig** [comment]
That's fine.  It's more important to get the API into place, so that consumers can start using it.

We'll clean up the rest when we move to `Promise.delegate` or similar.

**Pull request merged**
