### PR TITLE
7099 drop loan terminology in Vaults and StakeFactory

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
refs: #7099

## Description

Correct terminology in Vaults and StakeFactory from 'loan' to 'debt' or similar.

### Security Considerations

N/A

### Scaling Considerations

N/A

### Documentation Considerations

loanFee becomes mintFee and should be corrected.

### Testing Considerations

All tests updated.

### CODE REVIEW

**Comment by Chris-Hibbert** [comment]
@turadg, feel free to make minor corrections and merge, if it would be helpful to get it into the tree while I'm away.

**Comment by dckc** [comment]
please add the conventional commits BREAKING CHANGE indicator (at least a !)

**Comment by Chris-Hibbert** [comment]
@turadg, you added `automerge`, but don't seem to have approved it. Is there anything remaining?

**Review by turadg — APPROVED** [review]
whups

**Pull request merged**
