### PR TITLE
chore: moddable ac9978f6 2021-03-15 edits

### PR DESCRIPTION
**Pull request by dckc**
semi-auto-generated; see #2648

for reference:

```
$ git log --date=short --pretty="%h %ad %s" b7a0a6ec202a..ac9978f6015d 

ac9978f6 2021-03-15 edits
ee959cb6 2021-03-15 XS: #582 #581 #580 #567
3edc9137 2021-03-15 XS: #582 #581 #580 #567
d2d9a0f7 2021-03-15 XS: #583
ef5216cc 2021-03-15 XS: #585
dbd3a5f4 2021-03-14 XS: #586 & #587
f5169bb1 2021-03-11 esp32: merge application release sdkconfig rather than replacing
e7f318d3 2021-02-17 Microphone support for M5StackCore2 and M5StickC
836341b3 2021-03-10 XS: #592
b05e8dcf 2021-03-09 update getting started doc
efb9086b 2021-03-09 add builtinGetBufferPointer to support TypedArray views; use in SPI
68435bdc 2021-03-09 remove stray character #597
55863cbb 2021-03-09 instrumentation examples need to explicitly include instrumentation module #598
a2d8180d 2021-03-09 XS: marshalling
dec256cd 2021-03-08 remove stray character
102e8d2c 2021-03-08 xpt2046 example (SPI transfer)
9590db19 2021-03-08 fix read of pin 16
9fdeb7ba 2021-03-08 pixel colors  are big endian; add moddable zero registers
52913a26 2021-03-08 TC53 SPI for ESP8266 and ESP32
e7e72ba6 2021-03-08 XS linker explicit strip REPL fix
2770b4ec 2021-03-08 XS linker explicit strip REPL fix
83d6ca72 2021-03-04 last change broke left edge color cell clipping
0d4e6c27 2021-03-03 update manifest.md to reflect ESP32-S2 and ESP-IDF 4.2 changes
b068ffbe 2021-03-03 XS: error stack at creation - REBUILD ALL FROM SCRATCH
```

### CODE REVIEW

**Comment by katelynsills** [comment]
Awesome! One very minor suggestion: maybe use conventional commits in the autogenerated commit message and PR title?

**Review by michaelfig — APPROVED** [review]
I don't have enough context to know what is going into the update, but I'm happy to maintain it if it breaks.

LGTM!

**Review by warner — APPROVED** [review]
I skimmed the `xs/sources/` changes, looks like a bunch of parser/error-reporting changes, and one tidbit in the WeakMap memory-handling that maybe if we're lucky fixes the weird bug we've been seeing. Go for it!

**Comment by warner** [comment]
This bit in `xsMemory.c` that changes

```c
void fxMarkWeakStuff(txMachine* the, void (*theMarker)(txMachine*, txSlot*)) 
{
	txSlot* slot;
	txSlot** address;
	address = &the->firstWeakMapTable;
	while ((slot = *address)) {
		fxMarkWeakMapTable(the, slot, theMarker);
		*address = C_NULL;
		address = &(slot->value.table.address[slot->value.table.length]);
	}
	address = &the->firstWeakSetTable;
```

to:

```c
void fxMarkWeakStuff(txMachine* the, void (*theMarker)(txMachine*, txSlot*)) 
{
	txSlot* slot;
	txSlot** address;
	while (the->firstWeakMapTable) {
		txSlot* firstWeakMapTable = the->firstWeakMapTable;
		the->firstWeakMapTable = C_NULL;
		address = &firstWeakMapTable;
		while ((slot = *address)) {
			fxMarkWeakMapTable(the, slot, theMarker);
			*address = C_NULL;
			address = &(slot->value.table.address[slot->value.table.length]);
		}
	}
	address = &the->firstWeakSetTable;
```

seems especially relevant.

**Pull request merged**
