### PR TITLE
refactor(SwingSet): unify vat-worker filenames

### LINKED ISSUE #2202: unify vat-worker filenames
The `packages/SwingSet/src/kernel/vatManager/` directory currently contains the following files:

```
deliver.js
factory.js
localVatManager.js
nodeWorker.js
nodeWorkerSupervisor.js
nodeWorkerSupervisorCJS.js
subprocessSupervisor.js
syscall.js
transcript.js
worker-subprocess-node.js
```

and they could do with a renaming/cleanup pass. @dckc is likely to be working here in the next week, which might be a good time to do the cleanup.

`factory.js` is the entry point: it exposes a function (to the kernel) to create a new vat-manager of a particular type, with some set of options. Vat-managers of all types present a common API to the kernel for delivering messages to the vats they manage.

`transcript.js`, `deliver.js`, and `syscall.js` are libraries used by multiple manager types.

We currently have three types of vat-managers (and XS will be a fourth):

* The oldest is the "local" type, which runs the vat in the same process (and thread) as the kernel: it is the default.
* The "Node.js Worker" type runs the vat in the same process as the kernel, but in its own thread. In the Node.js world, `Worker` is the facility by which new threads are created, similar to how web browsers provide `ServiceWorker` and `WebWorker`. The kernel thread uses `postMessage` to send deliveries to the worker thread.
* The "Node.js Subprocess" type runs the vat in a child subprocess, communicating with it via Netstring-wrapped JSON-encoded messages sent over pipes. The child subprocess runs Node.js
* The (old) "XS Subprocess" type was just like a Node.js Subprocess, except that the child ran an XS binary instead of the Node.js binary. Our new XS type does the same, but uses a different control protocol, and uses the `xsnap` library to spawn and communicate with the child.

Each type of vat-manager is defined in a separate file: `localVatManager.js`, `nodeWorker.js`, and `worker-subprocess-node.js`.

The manager types which run the worker in a child process or thread all need some code for the child to first execute, known as a "supervisor". The Node.js Subprocess type puts this in `subprocessSupervisor.js`. The Node.js Worker type puts it in `nodeWorkerSupervisor.js`, and requires an additional file named `nodeWorkerSupervisorCJS.js` because you cannot start a worker from an ES6 Module -format file (so `nodeWorkerSupervisorCJS.js` is CJS-format and loads first, and it then can import the module-format code from `nodeWorkerSupervisor.js`).

The new XS-via-xsnap will require several pieces of code to be `eval()`ed in the child process. The first will set up the SES environment (portions of the SES-shim, and code to invoke `lockdown()`). The second will establish the supervisor, and install a command handler that accepts requests to create new Compartments and load vat code into them. Both must be delivered as single strings (actually byte arrays). These will be created by calling `rollup()` on files that live in the `vatManager/` directory, and sending the resulting single string in an xsnap `evaluate` command.

So our current files are:

type | manager/parent | worker/child | extra worker/child
---- | ------------ | ---------- | ----------
local | localVatManager.js | N/A | N/A
Node.js Worker | nodeWorker.js | nodeWorkerSupervisor.js | nodeWorkerSupervisorCJS.js
Node.js Subprocess | worker-subprocess-node.js | subprocessSupervisor.js | N/A

I think the new filenames should be:

type | manager/parent | worker/child | extra worker/child
---- | ------------ | ---------- | ----------
local | manager-local.js | N/A | N/A
Node.js Worker | manager-nodeworker.js | supervisor-nodeworker.js | supervisor-nodeworker-cjs.js
Node.js Subprocess | manager-subprocess-node.js | supervisor-subprocess-node.js | N/A
xsnap subprocess | manager-subprocess-xsnap.js | supervisor-subprocess-xsnap.js | lockdown-subprocess-xsnap.js

Also note that `rollup` takes a non-trivial amount of time, and is especially noticeable when running unit tests that create dozens of vats or kernel instances in a single program. We can improve this by building the two supervisor bundles ahead of time, and stashing them in memory until needed. Look at `buildKernelBundles` in `src/initializeSwingset.js` and examples of its use in e.g. `test/test-promises.js` and follow the pattern there.

### PR DESCRIPTION
**Pull request by dckc**
fixes #2202

Makes me glad I invested in learning vs-code!

### CODE REVIEW

**Comment by dckc** [comment]
#2158 shows this is incomplete.

**Comment by dckc** [comment]
the filenames we're unifying also show up in a couple `require.resolve` calls in `controller.js`:

fbbd53559f7be71958d85dae538e3811d19b257f

cc @warner

**Comment by warner** [comment]
Once #2217 lands, all workers should be getting exercised.

> the filenames we're unifying also show up in a couple require.resolve calls in controller.js:

Yeah, `controller.js` is run inside the Start Compartment, so that's where we need to define the functions that create a new Node.js thread (`new Worker(supercode)`) and/or spawn a child process. It's also where we do the path algebra to locate the supervisor code that must be loaded into those new containers.

I'd suggest renaming those two functions (`makeNodeWorker`, `startSubprocessWorker`, `startSubprocessWorkerXS`) to match the pattern we're using in the other files, and of course update those filenames to match your file renames in `src/kernel/vatManager/`.

**Comment by dckc** [comment]
I rolled this into #2225

**Pull request closed without merging**
