### PR TITLE
test(ERTP): balance {x, y, z} >= {z}

### LINKED ISSUE #10292: odd {x, y, z} >= {z} failure in AmountMath.isGTE with AssetKind.SET
## Describe the bug

AmountMath.isGTE with AssetKind.SET fails in a case involving invitations with common descriptions but distinct instance handles.

## To Reproduce

Add this to `packages/ERTP/test/unitTests/mathHelpers/copySetMathHelpers.test.js` and run it:

```js
test('balance {x, y, z} >= {z}', t => {
  const x = { instance: mockHandle('Foo'), description: 'fraz' };
  const y = { instance: mockHandle('Foo'), description: 'fraz' };
  const z = { instance: mockHandle('Foo'), description: 'alan' };

  const balance = harden({ brand: mockBrand, value: makeCopySet([x, y, z]) });
  const withdraw = harden({ brand: mockBrand, value: makeCopySet([z]) });

  t.true(m.isGTE(balance, withdraw));
});
```

## Expected behavior

test above passes

## Platform Environment

375dc25

## Additional context

@frazarshad discovered this while working on 

 - #10241

He made a test PR, #10281 

[a ci log of that a3p test](https://github.com/Agoric/agoric-sdk/actions/runs/11365912632/job/31615121873?pr=10281) shows the original context where the problem was found

_more diagnosis an an endo issue to follow_

## Screenshots / Logs

since ci logs expire:

```
2024-10-16T13:03:13.026Z SwingSet: ls: v9: Error#1: Withdrawal of { brand: Object [Alleged: Zoe Invitation brand] {}, value: [ { description: 'charter member invitation', handle: Object [Alleged: InvitationHandle] {}, installation: Object [Alleged: BundleIDInstallation] {}, instance: Object [Alleged: InstanceHandle] {} } ] } failed because the purse only contained { brand: Object [Alleged: Zoe Invitation brand] {}, value: [ { description: 'charter member invitation', handle: Object [Alleged: InvitationHandle] {}, installation: Object [Alleged: BundleIDInstallation] {}, instance: Object [Alleged: InstanceHandle] {} }, { description: 'oracle invitation', handle: Object [Alleged: InvitationHandle] {}, installation: Object [Alleged: BundleIDInstallation] {}, instance: Object [Alleged: InstanceHandle] {} }, { description: 'oracle invitation', handle: Object [Alleged: InvitationHandle] {}, installation: Object [Alleged: BundleIDInstallation] {}, instance: Object [Alleged: InstanceHandle] {} }, { description: 'Voter0', handle: Object [Alleged: InvitationHandle] {}, installation: Object [Alleged: BundleIDInstallation] {}, instance: Object [Alleged: InstanceHandle] {} } ] }
```

### PR DESCRIPTION
**Pull request by dckc**
closes: #10292

depends on an endo fix:
 - https://github.com/endojs/endo/issues/2588

to try a preview integration, we would use hash - endo-branch: master
but we want to test failure for a sec

## Description

_IOU_

### CODE REVIEW

**Comment by dckc** [comment]
huzzah!

```
ok 65 - unitTests › mathHelpers › copySetMathHelpers › balance {x, y, z} >= {z} %ava-dur=3ms
```
-- [ci log](https://github.com/Agoric/agoric-sdk/actions/runs/11464562264/job/3190)

cc @frazarshad

**Comment by dckc** [comment]
now I want to double-check that it fails with the old endo packages.

**Comment by kriskowal** [comment]
Capturing this PR in https://github.com/Agoric/agoric-sdk/pull/10316

To catch it breaking, remove the `#endo-branch` pin in the description and re-run the checks. I usually rebase and force-push for this effect, but there is a button somewhere in Github actions.

**Comment by dckc** [comment]
overtaken by #10316

**Pull request closed without merging**
