### PR TITLE
Default to disallowing implicit remotables

### PR DESCRIPTION
**Pull request by erights**
The default can be overridden for now with the `ALLOW_IMPLICIT_REMOTABLES` environment variable. Eventually we'll stop supporting that as well.

(Note to reviews: Important but not yet urgent)

The existing test cases should already cover both settings, and so no additional tests were necessary.

### CODE REVIEW

**Comment by erights** [comment]
Hi @michaelfig 

   * Lots of `Far`s now merged into dapps
   * rebased
   * green under CI

Now?

**Comment by michaelfig** [comment]
> * Lots of `Far`s now merged into dapps
> Now?

I would say yes, but, before you merge:  I haven't tested any of the dapps manually yet with `ALLOW_IMPLICIT_REMOTABLES=false ...` so I'd like to ask @katelynsills's opinion as well.

**Comment by katelynsills** [comment]
I think I'm missing some context. What's the current state of the dapps? Are they mostly all fixed up but not tested yet? Let's test them if that's the case, since there's no urgent deadline associated with this PR. I can help with that.

**Comment by erights** [comment]
> I think I'm missing some context. What's the current state of the dapps? Are they mostly all fixed up but not tested yet? Let's test them if that's the case, since there's no urgent deadline associated with this PR. I can help with that.

Help would be appreciated, thanks!

**Comment by katelynsills** [comment]
Sorry for the delay on this. I should be able to test out the dapps today

**Comment by katelynsills** [comment]
rebased on origin/master

**Comment by katelynsills** [comment]
@erights and @michaelfig, I started going through manually testing the dapps, starting with dapp-fungible-faucet. I found a missed Far within the wallet in the `addOffer` path, which I think means that none of the dapps would have worked at all if we had merged this. Given that this PR is not on the critical path for any near term deadline, and given that we are putting together demos this week, I think we need to complete the manual testing of the dapps before this can be merged. However, I need to do other things first as manual testing takes a lot of time. @michaelfig or @erights , can I pass on the manual testing of the dapps to you? Otherwise, I will come back to this after finishing other tasks.

**Comment by erights** [comment]
While this PR has been languishing, another implicit remotable snuck into our code. Which this PR would have prevented. As I understand it, what's holding it back is someone needs to check if it breaks any external dapps. Who can do this?

@Chris-Hibbert I added you in case you can do this.

There is a whole train of changes that has been piling up behind this two line change. Please let's get this merged.

**Comment by Chris-Hibbert** [comment]
I can be dragooned into this, but I have little relevant expertise, and I'm working on a tight deadline. 

@katelynsills, as I recall, you have done tasks across the set of external dapps. Would you mind taking care of this? If not, who would be better suited?

**Comment by katelynsills** [comment]
Please see https://github.com/Agoric/agoric-sdk/issues/3962 for the testing required for this change.

**Comment by erights** [comment]
Now that https://github.com/Agoric/agoric-sdk/pull/3970 landed, is this one clear to proceed? If so, ping to reviewers. Thanks.

**Review by dtribble — APPROVED** [review]

**Comment by dtribble** [comment]
NOTE we know this may impact some dapps that are not yet updated with Far annotations.

**Pull request merged**
