### PR TITLE
chore: rename ERTP and SwingSet dirs to match their package names

### PR DESCRIPTION
**Pull request by turadg**
## Description

Some package directory names differ from the name of the package. Can be seen by `cd packages && grep '"name"' */package.json`. That can be confusing.

This changes `ERTP` and `SwingSet` to match `@agoric/ertp` and `@agoric/swingset-vats`. It leaves alone `agoric-cli` because aligning that would require changing the actual package name from `agoric` and that has downstream implications.

### Security Considerations

--
### Documentation Considerations
--
### Testing Considerations

This should not create a pain for people with open branches touching these files. Fortunately [Git has support for directory renames](https://git-scm.com/docs/directory-rename-detection/). I tested this by making an edit in a branch and then merging this PR; it resolved automatically.

*reviewer*, is there anything else I should test?

### CODE REVIEW

**Comment by turadg** [comment]
If this is too much to take on before Mainnet 1 I'll file an issue to do after.

**Comment by erights** [comment]
a) why not wait until we move it to Endo and rename it `@endo/something` at the same time?

b) As long as we're renaming, I though `@something/swingset` was better than `@something/swingset-vat`. Do you prefer the latter, or is it inertia or incrementalism?

**Comment by turadg** [comment]
> a) why not wait until we move it to Endo and rename it @endo/something at the same time?

Good call. I couldn't find a ticket for the "move it to End" so I created https://github.com/Agoric/agoric-sdk/issues/4501 and noted this there.

> b) As long as we're renaming, I though @something/swingset was better than @something/swingset-vat. Do you prefer the latter, or is it inertia or incrementalism?

No preference here. I was constraining the PR to not affect downstream imports.

I'll remove SwingSet from this changeset and maybe leave some doc trail on package naming.

**Comment by turadg** [comment]
Closing b/c very stale

**Pull request closed without merging**
