### PR TITLE
remove web UI packages

### LINKED ISSUE #6591: Move UI components out of agoric-sdk
## What is the Problem Being Solved?

UI development has different tooling and release requirements than the rest of agoric-sdk. https://github.com/Agoric/wallet-app/  was removed in https://github.com/Agoric/agoric-sdk/pull/6511

There remains `ui-components` and `web-components` which weren't moved at the time because they need tooling to publish to NPM. agoric-sdk has all that built in but moving them out will require setting that up in another repo.

Related issues: https://github.com/Agoric/agoric-sdk/issues/2320

## Description of the Design

Start a new repo for client code that is used in UIs. No changes could break anything server-side so it would have much faster testing.

Migrate these packages to it,
- `@agoric/ui-components`
- `@agoric/web-components`

does it include CLI as well as GUI?
- `@agoric/agoric-cli`

DECISION: no, that's too useful rn to agoric-sdk testing.

## Test Plan

New repo is https://github.com/Agoric/ui-kit 
```[tasklist]
### Tasks
- [x] new repo has CI running tests
- [x] new repo has CI running lint (eslint and types)
- [x] new repo has MAINTAINERS.md with how to publish to NPM
- [x] new repo has commit history for ui-components and web-components
```

### PR DESCRIPTION
**Pull request by turadg**
closes: #6591

Not to be merged until https://github.com/Agoric/ui-kit is publishing to NPM.

## Description

Remove deprecated `wallet-connection` since it doesn't need to be updated.
Remove `ui-components` and `web-components` that will live in https://github.com/Agoric/ui-kit

Also cleans up unneeded code and dependencies with those gone.

Lastly it fixes an eslint-config export (worked around downstream for the time being with https://github.com/Agoric/ui-kit/commit/812ef76e8d200c939a8d4756485138fd38f77454 )

### CODE REVIEW

**Comment by turadg** [comment]
loadgen is failing because it's trying to get `stringifyNat` from `@agoric/ui-components` from agoric-sdk. It would work to from NPM or just copy that helper. @mhofman would that be difficult to change?

**Comment by mhofman** [comment]
I thought that `agoric install` was supposed to fallback on published NPM packages if one is removed. Would be curious to understand why it isn't here.

**Comment by michaelfig** [comment]
Breadcrumbs start at `agoric-sdk/packages/agoric-cli/src/sdk-package-names.js` for anybody who wants to look closer before I get to it.

**Comment by mhofman** [comment]
@michaelfig the problem was that `ui-components` has peer dependencies which were never satisfied by the loadgen. When it was symlinked, the peer dependency was satisfied through agoric-sdk, but not when pulled from NPM. However what was confusing is that the bundler tried to validate the presence of these peer dependencies in the first place, even though they were not needed for the particular deep import of `ui-components`. As suggested by @turadg I inlined the helper inside the loadgen and removed the `ui-components` dependency altogether.

Since https://github.com/Agoric/testnet-load-generator/pull/111 landed, I kicked a re-run of the deployment test.

**Review by samsiegart — APPROVED** [review]

**Pull request merged**
