### PR TITLE
feat: default to xs-worker in chain

### LINKED ISSUE #2473: commit to XS
- [x] limits - string size, number of properties #2681 
   - gather experience using benchmarks
 - [ ] metering  #2972 
     - [ ] sound
 - [ ] XS based testnet / devnet experience #2521
 - [x] [Error stacks](https://github.com/tc39/proposal-error-stacks)
     - fallback: debug on node

Postpone:
   - deterministic metering #2776 
       - [x] https://github.com/Moddable-OpenSource/moddable/issues/564
   - sloppy metering #2979 
 - run agoric-sdk, SES-shim tests on XS #370 - we ran most of the tests but have yet to land regular CI
   - [SES-shim/issues/535](https://github.com/Agoric/SES-shim/issues/535) running ava tests on XS
would be nice:
 - [SES-shim/issues/536](https://github.com/Agoric/SES-shim/issues/536) module support in XS Compartment
   - work-around: rollup / bundleSource

related:
 - determinism of weakref finalization

### LINKED ISSUE #2521: XS based testnet / devnet experience
## What is the Problem Being Solved?

We lack experience with performance, size limits (#2652 ), etc. using XS in validators.

## Test Plan

sync w/@warner on switching to XS (perhaps not exactly the same as committing to XS, but close):

 - [x] vat creation in crank is #2911 #2928 pending review.
 - [x] removing tests that we don't want to make work on XS
   - [x] removing within-vat metering #2952
     - [x] spawner to use createVat #2941 failing a test
 - [x] test that metering catches runaways on XS.
 - [x] test that metering catches allocation overrun on XS. #2972
 - [x] don't force local when metering
 - [x] remove assert !metering in manager-subprocess-xs
 
 - [x] refactor dispatch #2671 is landed.

_Apr 23 plan moved from https://github.com/Agoric/agoric-sdk/issues/2473#issuecomment-825847899_

### LINKED ISSUE #2837: xsnap swingset worker does not support metering
## To Reproduce
1. in `packages/zoe` run `yarn test:xs-worker`
4. See `xsnap worker does not support enableInternalMetering` and `TODO: support metered with xs-worker; using local as work-around`

### PR DESCRIPTION
**Pull request by dckc**
I suggest that this:
closes #2473 commit to XS
closes #2521 XS devnet experience
closes #2837 xsnap swingset metering
  - [x] @warner I do have a question in #2837 about `test:xs-worker` in zoe

You may want to browse **xsnap** issues; I made an effort to label all relevant issues.

FYI @dtribble @rowgraus 

since #3012 has come up, this is stacked on #3023

### CODE REVIEW

**Comment by warner** [comment]
I'm testing this now.. dynamic vats still seem to be using the local worker, not XS. Investigating...

**Comment by warner** [comment]
#2998 fixes the issue, let's land it first.

I started a chain, and restarted it, and things seem to look good. Startup is an order of magnitude faster (23s vs 247s). Restart is 20x faster (13.3s vs 244s).

I'd appreciate someone else doing a smoke test (following the Getting Started instructions and [installing/testing a dapp](https://agoric.com/documentation/getting-started/agoric-cli-guide.html#starting-multiuser-dapps)).

Please review/land #2998, then get a second-opinion smoke test, then land.

Yay!

**Review by warner — APPROVED** [review]

**Comment by dckc** [comment]
> I'd appreciate someone else doing a smoke test

I asked @ski to take it for a spin; expect to hear from him in the next day or so.

**Comment by dckc** [comment]
do you want me to rebase rather than that merge, @warner ?

**Comment by dckc** [comment]
@warner @erights test-innerVat.js was sensitive to engine-specific messages for ReferenceError. But it also showed that when the XS supervisor reports an error in setBundle, the message was being censored before being passed back to the kernel.

In ecf24f9 I changed the `assert` to use `q` so that the message gets thru. It's OK for the kernel to see these error details, right? I guess we plan to come back to related questions in #2937 (though that's not on a milestone, so that plan is iffy).

**Comment by warner** [comment]
I'm seeing a problem when a load generator is pointed at this version.. please wait on landing it until I can investigate the cause.

_p.s. for follow-up, see #3012_

**Comment by dckc** [comment]
since #3012 has come up, this is stacked on #3023

**Comment by dckc** [comment]
@warner and I just agreed that this should be chain only, not ag-solo.

Again, the trick is that this is due for today's release, presumably at the testnet meeting in 20 minutes; I'm not available for a bit for reasons I mentioned.

@michaelfig @rowgraus be advised.

**Review by warner — APPROVED** [review]
Looks good to me, I think we're ready!

For anyone following along, we're making the solo machine use Node.js (`local`) vats so that the `agoric start` developer environment (aka "simchain") provide a better debugging experience, especially the stack traces. Making dynamic vats use XS is much faster (because we don't have to rewrite the code with the metering transform), but XS doesn't provide very nice stack traces.

**Comment by warner** [comment]
BTW I hear that the CI failure will go away when @Chris-Hibbert lands a pending treasury fix.

**Comment by dckc** [comment]
Thanks, @kriskowal , for listening to the story behind this PR.

**Pull request merged**
