### PR TITLE
[WIP] Add catch to promises. However, uncaught promise rejection still happening

### PR DESCRIPTION
**Pull request by katelynsills**
I think I followed the instructions on how to prevent uncaught promise rejections, but for some reason, I am still getting uncaught promise rejections, so I believe I'm missing something. Any help would be greatly appreciated. Thanks! 

To reproduce: 

`npx ava test/unitTests/contracts/test-coveredCall.js -m "zoe - coveredCall - alice's deadline expires, cancelling alice and bob"`

### CODE REVIEW

**Comment by michaelfig** [comment]
Here's how to solve the test error.  It's in the `updater.fail` method called by `kickOut`:
```diff
diff --git a/packages/notifier/src/notifier.js b/packages/notifier/src/notifier.js
index 1033adb6..221bb0a4 100644
--- a/packages/notifier/src/notifier.js
+++ b/packages/notifier/src/notifier.js
@@ -108,6 +108,8 @@ export const makeNotifierKit = (...args) => {
       assert(nextPromiseKit);
       currentUpdateCount = undefined;
       currentResponse = undefined;
+      // Don't trigger Node.js's UnhandledPromiseRejectionWarning
+      nextPromiseKit.promise.catch(_ => {});
       nextPromiseKit.reject(reason);
     },
   });
```

@erights you may have a better way to accomplish this.

**Comment by katelynsills** [comment]
> Here's how to solve the test error. It's in the `updater.fail` method called by `kickOut`:
> 
> ```diff
> diff --git a/packages/notifier/src/notifier.js b/packages/notifier/src/notifier.js
> index 1033adb6..221bb0a4 100644
> --- a/packages/notifier/src/notifier.js
> +++ b/packages/notifier/src/notifier.js
> @@ -108,6 +108,8 @@ export const makeNotifierKit = (...args) => {
>        assert(nextPromiseKit);
>        currentUpdateCount = undefined;
>        currentResponse = undefined;
> +      // Don't trigger Node.js's UnhandledPromiseRejectionWarning
> +      nextPromiseKit.promise.catch(_ => {});
>        nextPromiseKit.reject(reason);
>      },
>    });
> ```
> 
> @erights you may have a better way to accomplish this.

Woohoo, that solved it! Thanks so much!

**Comment by katelynsills** [comment]
I'm going to merge this into my branch now, but if there are any improvements, let me know and I will incorporate those too. Thanks!

**Comment by erights** [comment]
I have no better way to handle this. This particular case is a great example where suppressing the warning is the right thing. The whole point of the `updater`/`notifier` pair is that interested parties are notified of new things after then occurred. It is also one where there's no danger created if no one sees the failure notification. It is only a notification of an actual failure that should have already caused some effect (like a `kickOut`). If a consumer loses interest in further notifications, then they've legitimately lost interest in how the stream of notifications terminates.

**Comment by erights** [comment]
How did you folks track this one down? What would have helped? I'd like to understand in order to better support such debugging.

**Comment by katelynsills** [comment]
> How did you folks track this one down? What would have helped? I'd like to understand in order to better support such debugging.

I would also be interested, it seems like magic to me. :)

**Comment by katelynsills** [comment]
Here's another unhandled promise rejection that I can't find the origin of:

Screen Shot 2020-08-25 at 3 59 41 PM

**Comment by michaelfig** [comment]
> > How did you folks track this one down? What would have helped? I'd like to understand in order to better support such debugging.
> 
> I would also be interested, it seems like magic to me. :)

I was tracking where the rejected promise would go, then I noticed in `zoeSeat.js`, `kickOut` calls `updater.fail(reason)`.  Remembering that this is a promise-related function, I followed to its implementation and noticed a `.reject(reason)` there.

So, yes, it was magical. :smile:

We could probably check out all the `.reject(` occurrences and find more.

**Comment by michaelfig** [comment]
> Here's another unhandled promise rejection that I can't find the origin of:

Unfortunately, every metering exception is likely to generate several rejections that just aren't handled.  I don't know of any way around that.  Perhaps there's a way to tone down AVA's pickiness somehow in the test config?

**Pull request merged**
