### PR TITLE
fix(vat-data)!: deprecate kinds in favor of Far Classes

### PR DESCRIPTION
**Pull request by erights**
I believe we've now had enough experience with FarClasses, etc, to deprecate the virtual/durable kind APIs and unconditionally recommend FarClasses, etc, instead.

### CODE REVIEW

**Comment by turadg** [comment]
@erights you marked this Ready for Review but the PR description says, "We won't know if this is a good idea until…". Do you think it's a good idea now?

**Comment by erights** [comment]
> @erights you marked this Ready for Review but the PR description says, "We won't know if this is a good idea until…". Do you think it's a good idea now?

Good question! You and @Chris-Hibbert have given these more road testing at this point than I have. What do you both think? Are we ready to deprecate kinds in favor of far classes / far instances?

**Comment by Chris-Hibbert** [comment]
I don't know enough yet to think we should definitely start on a project to convert everything over, but I prefer Far classes at this point. I'm not sure whether it would be more prudent to finish making Zoe durable using Kinds, rather than mixing the two styles.

**Comment by erights** [comment]
Reviewers (as well as @turadg @michaelfig ), I'd appreciate help in how to deprecate these so that the deprecations show up more reliably under vscode. Thanks.

**Comment by turadg** [comment]
> help in how to deprecate these so that the deprecations show up more reliably under vscode

The `export const` is implicitly defining a new types. I don't see a way to to propagate the types but we can mark the new one as deprecated.
```

/** @deprecated */
 export const {
   defineKind,
   defineKindMulti,
   defineDurableKind,
   defineDurableKindMulti,
} = VatDataGlobal;

export const {
   makeKindHandle,
   providePromiseWatcher,
```

**Comment by erights** [comment]
Re https://github.com/Agoric/agoric-sdk/pull/6106#issuecomment-1305802805 , Done.

**Review by turadg — APPROVED** [review]

**Pull request merged**
