### PR TITLE
chore(store): Define narrow VOM context types

### LINKED ISSUE #7319: narrower types for ContextProvider
In the review of #7138, @gibson042 suggested some better (narrower) types for the new ContextProvider function:

              How about narrowing this?
```suggestion
/**
 * @typedef {{self: any, state: any}} ClassContext
 * @typedef {{self: any, facets: Record<string, any>}} ClassKitContext
 * @typedef {(representative: any) => ClassContext} ContextProvider
 * @typedef {Record<facetName: string, (facet: any) => ClassKitContext>} ContextProviderKit
 */
```

_Originally posted by @gibson042 in https://github.com/Agoric/agoric-sdk/pull/7138#discussion_r1149648437_

Since the exo-utils.js changes referenced by that comment got landed earlier (#7304 in agoric-sdk, https://github.com/endojs/endo/pull/1534 in Endo), this suggestion can now be applied independently (before or after the landing) of #7138.

Once we find a form that we like (and doesn't cause any other type errors to crop up), we should apply it to both agoric-sdk and Endo (compare 7304 and endo-1534 to find the corresponding files that need changing), to facilitate changing agoric-sdk to get this exo functionality from Endo instead of packages/stores.

@gibson042 I applied your recommended change, and got an error that `facetName` isn't known as a type. I removed the `facetName:` portion, and ran into other type errors in nearby files that I don't know how to resolve. Can I hand this branch off to you to make it work? Or to decide that it isn't worth changing at this point.. I like the proposed changes, but if it turns into a large project, then you might decide otherwise.

The branch is [7319-narrower-exo-types](https://github.com/Agoric/agoric-sdk/tree/7319-narrower-exo-types) .

cc @erights

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #7319

## Description

Splits `ContextProvider` and related types into class vs. class-kit flavors as suggested at https://github.com/Agoric/agoric-sdk/pull/7138#discussion_r1149648437 .

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

n/a

### CODE REVIEW

**Review by warner — APPROVED** [review]
That sounds plausible? If this passes `tsc` in CI, I'm ok with it.

You should make a parallel change to the exo tools in Endo, and make sure the owners of that module are ok with them, before landing this one, to keep the two copies of `exo-tools.js`/`exo-makers.js` in sync.

**Comment by warner** [comment]
.. and apparently CI is *not* happy, https://github.com/Agoric/agoric-sdk/actions/runs/4641308681/jobs/8214208955?pr=7360#step:5:365

**Comment by gibson042** [comment]
@warner Looks like I carried forward a preexisting typo; PTAL.

**Comment by gibson042** [comment]
> You should make a parallel change to the exo tools in Endo, and make sure the owners of that module are ok with them, before landing this one, to keep the two copies of `exo-tools.js`/`exo-makers.js` in sync.

https://github.com/endojs/endo/pull/1543

**Review by erights — APPROVED** [review]
LGTM

**Review by warner — APPROVED** [review]
I'm no expert but it seems ok to me. I'll defer to @erights for the Endo side.

**Pull request merged**
