### PR TITLE
docs(swingset): Synchronize networking docs with public docs

### PR DESCRIPTION
**Pull request by gibson042**
## Description

Synchronize with https://agoric.com/documentation/repl/networking.html .

### Security Considerations

n/a

### Documentation Considerations

This will be followed with a PR against https://github.com/Agoric/documentation for the same purpose.

### Testing Considerations

n/a

### CODE REVIEW

**Review by FUDCo — COMMENTED** [review]
Purely from a copy editing point of view this looks fine to me.  I'll leave it to the other reviewers who (I hope) know more about the underlying ground truth to judge correctness.

**Comment by warner** [comment]
I gotta leave this one to @michaelfig too

**Comment by michaelfig** [comment]
> Synchronize with https://agoric.com/documentation/repl/networking.html .

I wanted to check your work so that I can see that it is synchronised.  However, you're using a forked repo to submit this PR which made it trickier.

I encourage you to create branches directly on the Agoric repos for future PRs.

**Review by michaelfig — COMMENTED** [review]
I diffed:
```sh
curl https://raw.githubusercontent.com/gibson042/agoric-sdk/gibson-synchronize-swingset-networking-docs/packages/SwingSet/docs/networking.md
curl https://raw.githubusercontent.com/Agoric/documentation/d3ce5349c1840473a9722d169f8ab00174b937f7/main/repl/networking.md
```

The results were not illuminating.

So, I'm approving this based on content only in the hopes that the upcoming PR against the documentation repo will bring these two sources closer together.

**Comment by gibson042** [comment]
@michaelfig https://github.com/Agoric/documentation/pull/656 is posted. Please compare the results to this PR, and mark both approved at your convenience.

**Review by michaelfig — APPROVED** [review]
Thanks for this, @gibson042.  Both content and synchronization LGTM!

**Pull request merged**
