### PR TITLE
Stop doing object-inspect type checks the hard way

### LINKED ISSUE #7277: replace brand checks: was Investigate the performance impact of xsnap-lockdown `isMap`
## What is the Problem Being Solved?
[packages/xsnap-lockdown/lib/object-inspect.js line 333](https://github.com/Agoric/agoric-sdk/blob/master/packages/xsnap-lockdown/lib/object-inspect.js#L333) `isMap()` generates a lot of debug spew suggesting it might be creating a lot of short-lived Error objects in otherwise normal code path which might be expensive and result in slow down of core scenarios.

### PR DESCRIPTION
**Pull request by FUDCo**
This PR eliminates a bunch of expensive `try/catch` based type checks from the object-inspect module used by the xsnap console logger, in favor of just using `instanceof`.

Closes #7277

### CODE REVIEW

**Comment by mhofman** [comment]
So taking a closer look at `object-inspect.js`, I'm wondering if we shouldn't get rid of the whole waterfall of `isFoo` (keeping `isArray` and `isError`), and replace with a big old switch statement:

```js
switch(gPO(obj)) {
  case Map.prototype: {
    // ...
  }
  case Set.prototype: {
    // ...
  }
  //...
}
```

At this point the code has already established that `obj` is a non-null `typeof obj === 'object'` (by exhaustion, maybe we should introduce an explicit check). I don't think we care about pretty printing derived classes from these base classes, the same way we don't care about them not passing brand checks.

**Comment by FUDCo** [comment]
> I'm wondering if we shouldn't get rid of the whole waterfall of `isFoo` (keeping `isArray` and `isError`), and replace with a big old switch statement

From a code cleanliness perspective, I think that would be a big improvement, but the issue at hand is performance.  I'd be reluctant to undertake a more invasive refactoring without evidence that there's a notable performance benefit to be had at the end to pay for the effort and risk.  The main benefit (from a perf standpoint) would be factoring out the redundant checks for the reference being nullish or not an object, but I'm not sure those are that costly (and if so probably could be factored out at the top of the current check sequence).  Since the cases of the `switch` wouldn't be simple integers, I suspect it would probably expand internally to a cascaded if anyway, rather than using some kind of jump table, so we'd still be paying the cost of that (and even it did use a jump table, it's not clear than the table lookup itself wouldn't cost more than a bunch of ifs).

**Comment by mhofman** [comment]
> The main benefit (from a perf standpoint)

I also expect a single prototype lookup, even if in user space, to be a lot more efficient than repeated prototype walks internal to `instanceof` nested inside function calls.

**Comment by michaelfig** [comment]
> I also expect a single prototype lookup, even if in user space, to be a lot more efficient than repeated prototype walks internal to `instanceof` nested inside function calls.

They're not semantically equivalent.  What is the user behaviour wrt deep subclassing that is most desirable?

**Comment by mhofman** [comment]
> They're not semantically equivalent. What is the user behaviour wrt deep subclassing that is most desirable?

I honestly think we don't care.



> I don't think we care about pretty printing derived classes from these base classes, the same way we don't care about them not passing brand checks.

**Review by michaelfig — APPROVED** [review]
I'm fine with this landing as-is to address the problem at hand.  However, if you'd like to adopt some of @mhofman's suggestions to improve further, please feel free to do so.

**Review by mhofman — APPROVED** [review]
I am fine with this merging as-is, but would prefer going all the way and simplify the logic in `object-inspect.js` further. For context, I believe this was originally just slightly adapted from the node.js implementation, and there is really no reason to keep carrying forward some of the original design choices (which were likely motivated by trying to support a wide range of cases where the environment is a lot more dynamic than ours, and the engine more performant).

**Comment by FUDCo** [comment]
I'm going to land this as is and file a separate ticket for the refactoring so we don't forget about it.  My read of the code is that Mathieu's heart's desire here is not entirely trivial -- not particularly hard either, but not something we need to spend the time on right now when we're pushing to ship.  Obviously if further perf data suggests otherwise, we can bump the priority of the follow-on issue.

**Pull request merged**
