### PR TITLE
Instructions for testing testnet-load-generator

### PR DESCRIPTION
**Pull request by samsiegart**

### CODE REVIEW

**Review by katelynsills — APPROVED** [review]
This looks good to me! thanks for adding it! I'll leave it to @mhofman to confirm the details

**Review by mhofman — APPROVED** [review]
LGTM. Just checking in case the other dapps require a locally installed `agoric-sdk` already, it might make more sense to use `./runner/bin/loadgen-runner` instead of `./start.sh` to avoid rebuilding a whole SDK.

**Comment by samsiegart** [comment]
> LGTM. Just checking in case the other dapps require a locally installed `agoric-sdk` already, it might make more sense to use `./runner/bin/loadgen-runner` instead of `./start.sh` to avoid rebuilding a whole SDK.

You mentioned it requires both `agoric` and `ag-chain-cosmos`, right? I don't seem to have `ag-chain-cosmos` in my path, so I think testing other dapps doesn't require it for now.

**Comment by samsiegart** [comment]
Just added the extra bit about `./runner/bin/loadgen-runner` just in case

**Pull request merged**
