### PR TITLE
BREAKING CHANGE: remove  @agoric/wallet-ui

### LINKED ISSUE #6474: pull web UI out of agoric-sdk
## What is the Problem Being Solved?

the Web UI packages have different dependencies, CI and deploy processes from the chain parts of agoric-sdk. Problems we could solve by pulling it out,
1. Having to release all agoric-sdk to bump versions for dapp deps ([example](https://github.com/Agoric/agoric-sdk/pull/6486#issuecomment-1286895311))
2. Needlessly running loadgen on Web UI changes, which can't possible affect the chain (~1hr merge delay, unless dev tags to skip)
3. NPM module resolution for dependencies that run in user browser VM vs chain
4. Security advisory noise for inclusion of those dependencies in different contexts
5. Having to build extra tooling for https://github.com/Agoric/wallet-app/issues/40

## Description of the Design

Move @agoric/wallet-ui package to wallet-app repo.

Update project management tooling to include tickets from that repo.

## Security Considerations
TBD
## Test Plan

TBD

### PR DESCRIPTION
**Pull request by turadg**
closes: #6474

## Description

Per #6474, the Wallet app code is now at https://github.com/Agoric/wallet-app. 

This PR removes it from agoric-sdk so that there is just one canonical Wallet UI. I believe that the [instructions for using the older version compatible with ag-solo ](https://github.com/Agoric/agoric-sdk/blob/cf6836259b35e5e5bfd927379825f642c3724074/packages/wallet/README.md#L12-L18)still work since they check out community-dev and not master. (Indeed, master wallet-ui is already broken for agsolo)

### Security Considerations

Improves separation of builds and dependencies.

### Documentation Considerations

End users are not affected.
Developers who wish to contribute to the Wallet app will need to know about the new repository. This commit message directs them.
Ag-solo users will need to use the instructions above to get an older version. (We've already decided agsolo doesn't need a GUI going forward).

### Testing Considerations

CI

### CODE REVIEW

**Review by samsiegart — COMMENTED** [review]
1. We plan to add it to [wallet-app](https://github.com/Agoric/wallet-app) before merging this right?
2. Will we move `web-components` to a separate repo too as part of https://github.com/Agoric/agoric-sdk/issues/6474?
3. I wonder if there's now some things we can prune from yarn.lock. @mhofman might know better how to clean that up.
4. I know @michaelfig was doing some stuff around ag-solo so I want to defer approval to him

**Comment by mhofman** [comment]
Oh cleaning up `yarn.lock` would be much appreciated!

**Comment by turadg** [comment]
> 1. We plan to add it to [wallet-app](https://github.com/Agoric/wallet-app) before merging this right?

It's already there, per the first line of the description. Specifically: https://github.com/Agoric/wallet-app/tree/master

> 2. Will we move `web-components` to a separate repo too as part of #6474?

That's not part of 6474. I'm not opposed but it would need some discussion as to where it goes and how it gets published. 

> 3. I wonder if there's now some things we can prune from yarn.lock. @mhofman might know better how to clean that up.

Good call. I meant to include that and forgot. Here's my local,
```
[6474-extract-wallet-app a53bf6480] chore: yarn install
 1 file changed, 239 insertions(+), 5496 deletions(-)
```

18536 lines down to 13729, 26% reduction. I'll hold off on push until approval since that's liable to get stale as master changes.

> 4. I know @michaelfig was doing some stuff around ag-solo so I want to defer approval to him

Ok, I'll make him the sole reviewer.

**Comment by samsiegart** [comment]
>It's already there, per the first line of the description. Specifically: https://github.com/Agoric/wallet-app/tree/master

Oh okay I had trouble finding it. Why `master` instead of `main`?

**Review by michaelfig — APPROVED** [review]
LGTM.  Can you please update `yarn.lock` as well?

**Comment by mhofman** [comment]
Any reason integration was bypassed for this?
CI is now broken: https://github.com/Agoric/agoric-sdk/actions/runs/3365023455

**Pull request merged**
