### PR TITLE
feat(docker): publish more than one architecture

### LINKED ISSUE #4901: Build dockerfile for multiple architectures
## Describe the bug
It would be cool to publish the agoric-sdk dockerfile for more than one architecture (e.g. linux/amd64, linux/arm64/v8)

### PR DESCRIPTION
**Pull request by arirubinstein**
closes: #4901

## Description

adopts the official docker github actions and builds for two architectures

### Testing Considerations

Tested in my local fork

### CODE REVIEW

**Comment by arirubinstein** [comment]
Going to try to rework the tags with the docker/metadata-action@v3 action

**Comment by arirubinstein** [comment]
Reworked this to work with github dockerx build and xplatform build.  Tested on my local fork

**Review by michaelfig — COMMENTED** [review]
Can you please test this in CI with:

```
on:
  pull_request: # FIXME: Remove after testing
  push: ...
```

**Comment by erights** [comment]
This PR is about things that I am only dimly aware of, so I'm removing myself as a reviewer. If my attention is needed, please add me back in and let me know what you'd like my attention on. Thanks.

**Comment by arirubinstein** [comment]
> pull_request: # FIXME: Remove after testing

Testing now

**Comment by arirubinstein** [comment]
> This PR is about things that I am only dimly aware of, so I'm removing myself as a reviewer. If my attention is needed, please add me back in and let me know what you'd like my attention on. Thanks.

seems like this was a side effect of the default CODEOWNERS path - there may be lots more PRs in your inbox after the CODEOWNERS change today

**Comment by arirubinstein** [comment]
Should be good to go @michaelfig
Screen Shot 2022-03-24 at 1 01 55 PM

**Review by michaelfig — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
