### PR TITLE
feat: agoric client docker-compose config

### LINKED ISSUE #2697: As a user, I can run an ag-solo / wallet to connect to testnet dapps using a docker container
_p.s. see https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose --Dan_

### LINKED ISSUE #2705: ag-solo discord invitation expired
https://discord.gg/9nKvca expired. Let's use https://agoric.com/discord

### PR DESCRIPTION
**Pull request by dckc**
sorta starting to work

goal:
fixes #2697 fixes #2705

### CODE REVIEW

**Review by michaelfig — APPROVED** [review]
LRNTM!  Looks really-noice to me.

**Comment by dckc** [comment]
does it actually work for you?

**Comment by dckc** [comment]
also: is this where these files should go?

I had to `git add -f .env` to override `.gitignore`. That seem hazardous.

**Comment by michaelfig** [comment]
> does it actually work for you?

I just now tested, but it needed another push.  Now it seems to work.

**Comment by michaelfig** [comment]
> also: is this where these files should go?

It may be better to put them somewhere in the top of the SDK (`agoric-sdk/docker` or something), for discoverability?

> I had to `git add -f .env` to override `.gitignore`. That seem hazardous.

That's acceptable from time to time.  I'm okay with it.

**Comment by dckc** [comment]
> Now it seems to work.

And what does that look like?

For me, it says `start: adding HTTP/WS listener on 127.0.0.1:8000` but I get connection refused there. Is there some docker networking step I missed?

And it still spins with `Error running ag-cosmos-helper query swingset egress agoric12ssfrtkkyppman765qg3ckyjvmahpw6ecx6yvt` even well after I did `!faucet client ...`.

**Comment by dckc** [comment]
`.env` might not be necessary... `"${PASS:-secret}"` is reported to work: https://github.com/docker/docker.github.io/issues/6914#issuecomment-398818071

**Comment by michaelfig** [comment]
I added a quick README.md.

The Dockerfile commit above (additional /usr/local/bin/agoric symlink) will mean in the future you don't need to prepend `npx` before the `agoric open ...`.

**Comment by dckc** [comment]
@rowgraus we put some instructions in https://github.com/Agoric/agoric-sdk/tree/2697-docker-client/docker ; take a look, please?

**Review by michaelfig — APPROVED** [review]
LGTM.  And it actually works, too!

**Pull request merged**
