### PR TITLE
Use ordered merge for set operations

### PR DESCRIPTION
**Pull request by erights**

### CODE REVIEW

**Review by FUDCo — APPROVED** [review]
Seems legit.

**Comment by erights** [comment]
Hi @FUDCo , the ordered set operator logic is as you reviewed it. But the use by ERTP now works, which it did not in the previous Draft. It is now R4R with these additional changes, so I hit the "request review" button. Thanks.

**Comment by erights** [comment]
This was stacked on #4191 which is stacked on #4210 . However, it doesn't actually depend on any of the changes from #4191, so I restacked it directly on #4210

**Review by FUDCo — APPROVED** [review]
Well, OK then

**Pull request merged**
