### PR TITLE
fix(agoric): convey tx opts to `agoric wallet` and subcommands

### LINKED ISSUE #9554: agoric-cli wallet send options are too strongly positional
## Describe the bug
A cli invocation of `agoric wallet send` which placed `keyring-backend` or other options after the `send` command no longer accepts that option (unrecognized)

This is a regression from u15

## To Reproduce
See above

## Expected behavior
These base options should be accepted both before and after leaf commands

## Platform Environment
master

### PR DESCRIPTION
**Pull request by michaelfig**
closes: #9554

## Description

Propagate tx options to `agoric wallet` and the relevant subcommands.

### CODE REVIEW

**Comment by mhofman** [comment]
Re-running #9526 based on this change to verify regression fix

**Comment by mhofman** [comment]
I don't think this is doing what it claims. See https://github.com/Agoric/agoric-sdk/actions/runs/9619983237/job/26537260778?pr=9526#step:9:3058 for a failure

**Comment by michaelfig** [comment]
> I don't think this is doing what it claims.

Sorry for the half-fast implementation.  I totally forgot that the command actions also needed to be updated.  I tested the current commit more thoroughly, and it behaves the way I'd expect.

**Review by mhofman — APPROVED** [review]
Approving on the basis that #9526 is green

**Pull request merged**
