### PR TITLE
Switch from a noActionElectorate to a committee for a demo

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
Switch install-on-chain to create the treasury governed by a committee rather than a noActionElectorate so we can do a demo.

### CODE REVIEW

**Comment by dckc** [comment]
I added a `demo` name hub and used it to make the powers we need available:

```
command[4] E(E(home.agoricNames).lookup('demo', 'voteCreator')).help()
history[4] Promise.reject("TypeError: target has no method \"help\", has [\"voteOnParamChange\"]")
command[5] E(E(home.agoricNames).lookup('demo', 'electorateCreatorFacet')).help()
history[5] Promise.reject("TypeError: target has no method \"help\", has [\"addQuestion\",\"getPoserInvitation\",\"getPublicFacet\",\"getQuestionSubscription\",\"getVoterInvitations\"]")
```

Along the way I fixed some lint and types that are probably worth keeping.

p.s. switched to draft PR, since I don't think we intend to merge this to master.

**Comment by Chris-Hibbert** [comment]
@warner   There's a test failing here that I don't understand. (This is demo code, so if it's too much work to analyze, feel free to ignore.) The test ('bootstrap export' in `test-controller.js`) has failed repeatedly in CI, but runs cleanly when I run it locally.

**Comment by warner** [comment]
> @warner There's a test failing here that I don't understand. (This is demo code, so if it's too much work to analyze, feel free to ignore.) The test ('bootstrap export' in `test-controller.js`) has failed repeatedly in CI, but runs cleanly when I run it locally.

I've opened #3981 for that, and I'm betting it's an instance of the "V8 finalizers vs AVA parallelism" problem. I observed a similar problem in the same test, in CI only, but it went away before I had a chance to investigate.

Could you try changing that failing test (`packages/SwingSet/test/test-controller.js` "bootstrap export", around line 171) from `test(..` to `test.serial(..` and see if that lets CI pass?

**Comment by warner** [comment]
@Chris-Hibbert oh and @FUDCo pointed out that most of us are running Node 14 locally, but CI does both 14 and 16, and this bug might only be tickled by 16. So you might try running 16 locally and see if it reproduces.

**Comment by Tartuffo** [comment]
@dckc @rowgraus After various meetings, this ended up with a MN-1 tag *AND* in the Product Backlog pipeline.  Please modify appropriately for what it should actually be.

**Comment by dckc** [comment]
I _think_ this is water under the bridge and should be closed, but I'm not sure I can speak for @Chris-Hibbert .

**Comment by Chris-Hibbert** [comment]
The demo is certainly no longer relevant.  The change from a NoActionElectorate to a Committee is in @dckc's hands with the refactoring of bootstrap.

I'm going to take this out of both MN-1 and the product backlog, and leave it as Draft, in case it's helpful for #3981.

**Pull request closed without merging**
