### PR TITLE
chore: moddable 7abc931d 2021-03-19 XS: 608 (weak maps)

### LINKED ISSUE #2670: XS-specific test failure, WeakMap vs GC?
## Describe the bug

We're seeing an intermittent failure in the `test:xs` target. The most reliable appearance appears in https://github.com/Agoric/agoric-sdk/pull/2669/checks?check_run_id=2133636064#step:7:830 , in `test/unitTests/zcf/test-zcf.js`, during the `userSeat.getCurrentAllocation from zcf.makeEmptySeatKit` test. When present, the STR is to:

* cd `packages/zoe`
* `yarn test:xs test/unitTests/zcf/test-zcf.js`

and you'll see something like:

```
TEST ONLY: capturing test data function [""] (){[native code]}
{
  status: 'not ok',
  id: 168,
  message: 'should be deep equal: {"actual":{"length":0,"keys":[]},"expected":{"length":1,"keys":["A"]}}',
  filename: 'test/unitTests/zcf/test-zcf.js',
  label: ''
}
{
  status: 'not ok',
  id: 169,
F test/unitTests/zcf/test-zcf.js userSeat.getCurrentAllocation from zcf.makeEmptySeatKit
  message: 'should be deep equal: {"actual":{"length":0,"keys":[]},"expected":{"length":2,"keys":["A","B"]}}',
  filename: 'test/unitTests/zcf/test-zcf.js',
  label: ''
}
{
  status: 'not ok',
  id: 170,
  message: 'should be deep equal: {"actual":{"length":2,"keys":["A","B"]},"expected":{"length":0,"keys":[]}}',
  filename: 'test/unitTests/zcf/test-zcf.js',
  label: ''
}
```

When it happens, it's fairly sticky, but random other code changes can make it go away. I strongly suspect a GC bug in XS. I can make it go away by:

* introduce more memory allocations before the test runs, by adding the ollowing to the first test in the `test-zcf.js` file:
```js
  for (let i=0; i < 800; i++) {
    const o = harden({});
  }
```

(allocating 790 or fewer objects preserves the failure, allocating 800 or more makes the failure go away)

* delete all test functions after the failing one
  * however retaining the immediately-following test, and deleting all the subsequent ones, retains the failure

Our hypothesis is that XS WeakMaps sometimes lose their keys when a GC event happens. @dckc imported a Moddable update which addressed something involving WeakMaps (perhaps where a WeakMap held another WeakMap, or the retention path was root -> key, `key2 = weakmap1.get(key1)`, `target = weakmap2.get(key2)`), but it didn't seem to fix the problem.

This might suggest a place to explore: build a structure involving weakmaps, allocate enough objects to force a GC event (or uncomment the facility for adding a `gc()` function to the global object), then inspect the weakmap again.

## Platform Environment

I've seen this locally on linux, and on the CI machines (which are also linux).

### PR DESCRIPTION
**Pull request by dckc**
again, semi-automated #2648

fixes #2670 
I checked: https://github.com/Moddable-OpenSource/moddable/issues/608#issuecomment-803074826

### CODE REVIEW

**Comment by dckc** [comment]
oops...

**Comment by dckc** [comment]
there.

**Review by erights — APPROVED** [review]
What should one think about to review this?

In my ignorance, LGTM

**Comment by warner** [comment]
I certainly don't know enough about their codebase to pass judgement.. I'm entirely at their mercy. I look for consistency in the changes that were made, and I treat it as an opportunity to see that some functional area was modified in some way. E.g. from the diffs I can tell that WeakMaps are doing something different (so yay maybe it fixes our bug), some sort of stack-size limit is being computed or maybe enforced (so yay progress towards some of our metering goals), and a number of places that were assuming a chunk size of 1 are now accepting a configurable chunk size, so some sort of memory allocation thing is becoming more generic. Not much for me to approve or disapprove, but it acts a bit like a ChangeLog of the upstream sources, which is nice to be aware of.

**Review by warner — APPROVED** [review]
No problems jump out at me.

**Pull request merged**
