### PR TITLE
fix: restore simpler setStore type

### PR DESCRIPTION
**Pull request by erights**
The setStore api grew more api and type than I intended. Specifically, it should have `.keys` but not `.values` and `.entries`.

### CODE REVIEW

**Comment by FUDCo** [comment]
It has those because the JavaScript `Set` has those.  You should leave them in.

**Comment by FUDCo** [comment]
Further thought after double checking with MDN to verify that I wasn't just talking out of my hat with that last comment: `Set` has `values` and `entries` but it does not have `keys`.  We should remove `keys` from SetStore but leave `values` and `entries` in.  Or come up with a different name that doesn't make JS programmers think it's related to `Set`.

**Review by FUDCo — CHANGES_REQUESTED** [review]
I think this change is mistaken in principle.  We should discuss before proceeding.

**Comment by gibson042** [comment]
> Further thought after double checking with MDN to verify that I wasn't just talking out of my hat with that last comment: `Set` has `values` and `entries` but it does not have `keys`. We should remove `keys` from SetStore but leave `values` and `entries` in. Or come up with a different name that doesn't make JS programmers think it's related to `Set`.

Set does have `keys`: https://tc39.es/ecma262/multipage/keyed-collections.html#sec-set.prototype.keys

I don't know why it's missing from MDN, but I'll open a PR to fix that.

**Comment by gibson042** [comment]
> I don't know why it's missing from MDN, but I'll open a PR to fix that.

It appears to be an accidental consequence of an intentional redirect: https://github.com/mdn/content/issues/13286

I'll let someone else sort out MDN.

**Comment by erights** [comment]
I still think this would have been an improvement. But it is too late to consider. The existing API is, at this point, entrenched enough that it is not worth changing for this purpose. Closing.

**Pull request closed without merging**
