### PR TITLE
Require virtual object selves to be declared Far

### PR DESCRIPTION
**Pull request by FUDCo**
Fixes bug #3562

### CODE REVIEW

**Review by erights — CHANGES_REQUESTED** [review]
What about a negative test, where the new assert is violated?

**Comment by warner** [comment]
BTW I think it's accurate to say "Representatives are Far" rather than trying to define a "virtual object self": We use `Representative` and `Presence` and `Remotable` to refer to the three concrete JS `Object`s that userspace code interacts with. The "virtual object" is the abstract object with state and behavior, which has a longer lifetime than any single ephemeral+concrete `Representative`.

At least, that's the terminology that I use (and that I think we need) from everywhere except the interior of the virtual object manager. I guess I'm thinking the `initialRepresentative` variable is slightly misnamed: the user-provided "kind constructor" returns a record with two pieces (an `init` function for making new virtual objects, and a `self` behavior record which becomes the actual concrete Representative `Object`), but the overall record is being stored in `initialRepresentative`

**Review by warner — CHANGES_REQUESTED** [review]
In addition to @erights 's recommended negative test, please also update `docs/virtual-objects.md` to include the `Far` requirement.

Apart from that the code changes look great.

**Review by erights — APPROVED** [review]
LGTM

**Review by warner — APPROVED** [review]

**Pull request merged**
