### PR TITLE
change handledPromise to use a function rather than a subclass.

### LINKED ISSUE #333: pixel demo getBalance not working
When I do `px~.getBalance()` in the pixel demo, I just get `{}`, not anything like what the cosmic-swingset README says I should. @Chris-Hibbert says this is busted.

The first clue that something is up is that the previous step, `px = home.gallery~.tapFaucet()`, gives `{}` too; not an unresolved promise nor a presence.

Also (separate issue?), in the top level README, under **Run the larger demo**, after the 3 make commands, I could have used  a reminder to look at localhost:8000 . I suppose looking at the cosmic-swingset/README only makes sense after `cd packages/cosmic-swingset` but it didn't occur to me, so I expect others will likewise wonder if log messages in their terminals is the point of the "larger demo".

_p.s. I suppose this is supposed to be tagged cosmic-swingset but I don't seem to have access to do that._

### LINKED ISSUE #334: Promise.resolve(x)!==x for HandledPromises
The cosmic-swingset REPL code looks basically like this:

```js
r = evaluateProgram(text);
if (Promise.resolve(r) === r) {
  r.then(resolution => notifyFrontend(resolution), rejection => notifyFrontend(..));
} else {
  notifyFrontend(r);
}
```

We're seeing that `Promise.resolve(r) === r` *fail* when `r` is a HandledPromise. This seems to be the root cause of #333 (the results of a `~.` tildot call are presented as `{}`, which I'm guessing is the stringification of the Promise/HandledPromise object). I think the tildot calls are actually being executed, it's just that their results are not being recognized as Promises by the repl code, so it thinks they're all done, and it tells the frontend to update the display with a stringification of that promise, which comes out as `{}` (indistinguishable from an empty object). And because it doesn't realize they're promises, it doesn't wire up a `.then` to update the display later when it finally does resolve.

@erights MarkM says this is because HandlePromise is a subclass of Promise. He's working on a fix now.

CC @michaelfig

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
Closes https://github.com/Agoric/agoric-sdk/issues/334
Closes https://github.com/Agoric/agoric-sdk/issues/333

### CODE REVIEW

**Review by michaelfig — APPROVED** [review]
LGTM.

Can you please add a test that exercises:

```js
const hp = new HandledPromise(() => {});
t.equal(Promise.resolve(hp), hp, 'Promise.resolve of a HandledPromise');
```
?

**Comment by erights** [comment]
Hi @michaelfig @warner @Chris-Hibbert , @Chris-Hibbert handed the PR over to me. I made the remaining fixes I intended and added your suggested test. PTAL. Thanks.

**Comment by erights** [comment]
This is my fault. @michaelfig asked me to review https://github.com/Agoric/agoric-sdk/pull/110 . I was feeling overwhelmed at the time at advised him to proceed without my review. Had I not done so, I likely would have caught this.

In any case, in progress at #336

**Review by michaelfig — APPROVED** [review]
LGTM!

**Comment by michaelfig** [comment]
I tested against scenario3 as well.  Merging.

**Pull request merged**
