### PR TITLE
chore(marshal): Migrate to Endo

### PR DESCRIPTION
**Pull request by kriskowal**
This change applies my patented™ seven (maybe eight?) step system to eject a package to npm, this time to Marshal.

Refs: https://github.com/endojs/endo/issues/506

### CODE REVIEW

**Comment by kriskowal** [comment]
Currently blocked on https://github.com/endojs/endo/pull/1021 and a publish.

**Comment by kriskowal** [comment]
This is ready for review. The commit that includes SES patches will be replaced pending https://github.com/endojs/endo/pull/1030

**Review by michaelfig — COMMENTED** [review]
Outdate merge conflicts mean that this PR needs to be redune to absorb @erights changes.

**Comment by kriskowal** [comment]
Removed the patches, reran the automated commits. Ready for review.

**Review by michaelfig — APPROVED** [review]
I hope it's okay that I skipped over the giant sed-transform of `@agoric/marshal` to `@endo/marshal`.  I couldn't bring myself to audit >500 files.

**Comment by kriskowal** [comment]
> I hope it's okay that I skipped over the giant sed-transform of `@agoric/marshal` to `@endo/marshal`. I couldn't bring myself to audit >500 files.

Yeah, I didn’t either. Let’s hope the tests have us covered.

**Pull request merged**
