### PR TITLE
Update README to support building on Apple Silicon

### PR DESCRIPTION
**Pull request by jessysaurusrex**
fix: docs: building instructions for readme.md

Some native dependencies do not have pre-built binaries for arm64 (i.e. Apple Silicon), and it isn't possible to successfully build with the existing steps.  This section helps users download native dependencies to allow for building from source on these platforms. 

Given that this might be the first of many native dependencies that exhibit this issue, a documentation-based approach may be more scalable for futureproofing than patching the upstream projects and/or having Agoric take on aggregating dependencies.

### CODE REVIEW

**Comment by katelynsills** [comment]
@michaelfig, are you the right person to work on this / review this?

**Comment by michaelfig** [comment]
> @michaelfig, are you the right person to work on this / review this?

The instructions look alright.  I can't test them easily, but I see no reason to block merging.

@jessysaurusrex is there more that should go in the readme, or is this good to merge as-is?

**Comment by jessysaurusrex** [comment]
@michaelfig This should be good to unblock M1 users.

**Review by michaelfig — APPROVED** [review]
LGTM!

**Pull request merged**
