### PR TITLE
fix(cosmic-swingset): only require vatconfig if uninitialized

### PR DESCRIPTION
**Pull request by michaelfig**
refs: #8102

## Description

This PR removes an unnecessary runtime dependency on the static SwingSet config file.  It is used only for bootstrap, so its absence (or modification) in a future upgrade does not affect the operation of the SwingSet.  Cosmic-swingset was searching for this file on every restart, which meant that part of the reorganization intended by #8102 prevented the chain from restarting:

> portHandler threw (Error#1)
Error#1: Cannot find module '/usr/src/agoric-sdk/node_modules/@agoric/vats/decentral-main-vaults-config.json' imported from /usr/src/agoric-sdk/packages/cosmic-swingset/src/chain-main.js

As #8102 intended, this PR also removes the redundant copies of the swingset configs from `@agoric/vats/decentral*.json`.

### Security Considerations

Makes existing SwingSet instances more robust to future bootstrap config modifications.

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Tested by upgrade-tests.

### Upgrade Considerations

Removes an unnecessary dependency, enabling upgrade to be more successful.

### CODE REVIEW

**Review by FUDCo — APPROVED** [review]
Seems legit.

**Review by turadg — APPROVED** [review]
Clear fix and nice adjacent cleanup.

**Comment by michaelfig** [comment]
I'm having problems with the [getting-started local-npm test](https://github.com/Agoric/agoric-sdk/actions/runs/5752640482/job/15594084698#step:10:858), so I manually removed from the merge queue:

```
> @agoric/boot@0.1.1-dev-cffd97d.0+cffd97d prepack /home/runner/work/agoric-sdk/agoric-sdk/packages/boot
> tsc --build jsconfig.build.json

Error: ../vats/src/centralSupply.js(10,12): error TS2304: Cannot find name 'ZCF'.
Error: ../vats/src/centralSupply.js(43,15): error TS2304: Cannot find name 'ContractOf'.
Error: ../vats/src/mintHolder.js(23,12): error TS2304: Cannot find name 'ZCF'.
Error: ../vats/src/mintHolder.js(35,12): error TS2304: Cannot find name 'ContractMeta'.
Error: ../vats/src/mintHolder.js(46,12): error TS2304: Cannot find name 'ZCF'.
Error: ../vats/src/provisionPoolKit.js(100,11): error TS2304: Cannot find name 'ZCF'.
Error: ../vats/src/provisionPool.js(17,12): error TS2304: Cannot find name 'ContractMeta'.
Error: ../vats/src/provisionPool.js(36,14): error TS2304: Cannot find name 'StandardTerms'.
Error: ../vats/src/provisionPool.js(41,12): error TS2304: Cannot find name 'ZCF'.
Error: ../vats/src/provisionPool.js(44,30): error TS2304: Cannot find name 'Invitation'.
Error: ../vats/src/core/startWalletFactory.js(72,22): error TS2304: Cannot find name 'AdminFacet'.
Error: ../vats/src/core/types.js(314,28): error TS2304: Cannot find name 'IssuerKeywordRecord'.
Error: ../vats/src/core/types.js(337,28): error TS2304: Cannot find name 'IssuerKeywordRecord'.
Error: ../vats/src/core/types.js(396,22): error TS2304: Cannot find name 'PriceAuthority'.
lerna ERR! lifecycle "prepack" errored in "@agoric/boot", exiting 1
```

**Comment by michaelfig** [comment]
> I'm having problems with the [getting-started local-npm test](https://github.com/Agoric/agoric-sdk/actions/runs/5752640482/job/15594084698#step:10:858), so I manually removed from the merge queue:

Thanks to @turadg for helping me wrangle some ambient types.  This should pass now.

**Pull request merged**
