### PR TITLE
windows compatibility for agoric-cli

### LINKED ISSUE #5907: Windows compatibility for agoric-cli package
## Describe the bug

Windows doesn't 'recognize' the `node` command inferred from path in the [get-sdk-package-names.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/agoric-cli/scripts/get-sdk-package-names.js) script in the agoric-cli package.
image

https://github.com/Agoric/agoric-sdk/blob/cf97ba310fb5eb5f1ff5946d7104fdf27bcccfd4/packages/agoric-cli/scripts/get-sdk-package-names.js#L1

Windows keeps returning this error:
image

while it works perfectly in Linux environments.

Spent a lot of time trying to figure it out while working on Windows compatibility for the [Agoric Extension](https://github.com/Agoric/agoric-sdk/issues/5156)

A fix I was able to come up with is explicitly using `node` command in the agoric-cli package build script:
`"build": "node ./scripts/get-sdk-package-names.js > src/sdk-package-names.js",`
And setting the shell option to `true` :
```js
const ps = spawn('yarn', ['workspaces', '--silent', 'info'], {
  stdio: ['ignore', 'pipe', 'inherit'],
  shell: true
});
```
which works well in both Windows and Linux enviroments:

Linux Environment:
image

Windows Environment:
image

@jeetraut @dckc  @michaelfig 

I'll send in a Pull Request for the changes
## To Reproduce
1. Go to 'agoric-sdk/packages/agoric-cli' on a Windows system
2. Run 'yarn build'
3. Check the error logs

## Platform Environment
 - what OS are you using? what version of Node.js? Platform: Windows and Linux. Node version: v14.17.1
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) version 0.16.0

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

### PR DESCRIPTION
**Pull request by danBamikiya**
closes: #5907 

## Description

Makes the agoric-cli package more compatible for Windows systems

### CODE REVIEW

**Review by dckc — APPROVED** [review]
nice work. Thanks!

**Comment by Tartuffo** [comment]
@danBamikiya @dckc should merge this?

**Comment by danBamikiya** [comment]
> @danBamikiya @dckc should merge this?

@Tartuffo yes he should

**Comment by mhofman** [comment]
I'm not sure why CI didn't run the first time around.

**Comment by mhofman** [comment]
The CI failure is independent of this pull request and due to a temporarily broken master CI.

**Comment by mhofman** [comment]
@mergifyio refresh

**Pull request merged**
