### PR TITLE
Update vega to get rid of override mistake problem

### LINKED ISSUE #2373: Vega (used in stat-logger) overrides O.p.hasOwnProperty by assignment
Our mitigation of the override mistake adds 8 junk lines to every display of every object by the VSCode debugger's object inspector. https://github.com/Agoric/agoric-sdk/issues/2324 would enable to stop mitigating `Object.prototype.constructor` and thereby remove two of these. If we could stop mitigating `Object.prototype.hasOwnProperties` we could remove another two. Together, this would be a significant noise reduction.

@FUDCo AFAICT `Object.prototype.hasOwnProperty` is overridden by assignment only by something called "vega-util" which I think is only linked in due to some stats library you're pulling in. https://github.com/vega/vega-util itself claims to be superceded by https://github.com/vega/vega , so it is possible that upgrading that dependency might painlessly make the problem go away.

### PR DESCRIPTION
**Pull request by FUDCo**
Trivial update of a dependent npm package version lets us clear out an ancient issue.

Closes #2373

### CODE REVIEW

**Review by erights — APPROVED** [review]
If this makes the patch file unnecessary, please delete the patch file in the same PR. Thanks.

LGTM

**Comment by FUDCo** [comment]
Ah, I forgot the patch file was there.  Done.

**Review by erights — COMMENTED** [review]
Hey, what about my nickel!

See https://github.com/Agoric/agoric-sdk/issues/2373#issuecomment-1364426376

**Comment by FUDCo** [comment]
Of course. I'd rather owe you the rest of my life than cheat you out of it.

**Pull request merged**
