### PR TITLE
fix(ci): detect all repo changes during build

### PR DESCRIPTION
**Pull request by mhofman**
Detect untracked files as well as modified files

### CODE REVIEW

**Review by michaelfig — APPROVED** [review]

**Comment by mhofman** [comment]
I'm expecting this first build to fail on the untracked `build-env` file that was introduced in #7048

**Comment by mhofman** [comment]
@warner can you confirm the intention was to make the build env file part of the repo in #7048

**Comment by michaelfig** [comment]
> @warner can you confirm the intention was to make the build env file part of the repo in #7048

I can speak to that.  The intention was to make it available to NPM packages and the Docker build.  Before, that was done by putting it in the `dist` folder, but it's fine to move it up to the parent.

**Comment by mhofman** [comment]
> I can speak to that. The intention was to make it available to NPM packages and the Docker build. Before, that was done by putting it in the `dist` folder, but it's fine to move it up to the parent.

I'm not sure how to interpret this. There are obviously ways to ignore from source control yet include in the build artifacts. Do we want to include this file in source control? If so I'll just merge this PR.

It's likely not a problem to have this file change when we update the XS deps, we already have tests changing in these cases. With repo forks it'd also require a change, but I think the `.gitmodules` file needs to change as well.

**Comment by michaelfig** [comment]
> I'm not sure how to interpret this. There are obviously ways to ignore from source control yet include in the build artifacts. Do we want to include this file in source control? If so I'll just merge this PR.

Sorry for not being clear.  Yes, let's include it in source control.

**Pull request merged**
