### PR TITLE
fix(solo): take a dependency on `esm` to reenable plugins

### PR DESCRIPTION
**Pull request by michaelfig**
## Description

Expedient fix to get solo plugins working again for `dapp-oracle` and other future plugin-using packages.

This should be refined so that `agoric deploy` and the plugin system use the same logic to load foreign code that might need RESM, but could also use NESM.  @kriskowal, I may punt this back to you to do that cleanup and deduplication in your copious spare time.

### CODE REVIEW

**Review by kriskowal — COMMENTED** [review]
I presume we need to walk backwards here because I previously walked forward without overtly breaking the dapp-oracle integration test. Could this change include a regression test (even manual test instructions!) for solo plugins like dapp-oracle?

**Review by kriskowal — CHANGES_REQUESTED** [review]
(Requesting a regression test so this can be safely migrated to NESM)

**Comment by michaelfig** [comment]
> I presume we need to walk backwards here because I previously walked forward without overtly breaking the dapp-oracle integration test. Could this change include a regression test (even manual test instructions!) for solo plugins like dapp-oracle?

The manual test for `dapp-oracle` just involves reading its `README.md` and following the steps.  Ignore the Chainlink integration and just keep going; the instructions you want include `--allow-unsafe-plugins`.

**Comment by michaelfig** [comment]
> (Requesting a regression test so this can be safely migrated to NESM)

I've provided a regression test, and verified that it fails without RESM support.

**Review by kriskowal — APPROVED** [review]

**Pull request merged**
