### PR TITLE
chore(types): upgrade TypeScript to 5.3

### PR DESCRIPTION
**Pull request by turadg**
## Description

Update TypeScript from 5.2 to 5.3

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html

### Security Considerations

n/a
### Scaling Considerations

n/a
### Documentation Considerations

n/a
### Testing Considerations

CI

### Upgrade Considerations

n/a

### CODE REVIEW

**Review by dckc — COMMENTED** [review]
I'd like to know why the ci bot is so unhappy before approving.

I wondered what prompted this, but now I remember discussion of typedoc stuff a la #8343 / #4291 .

**Comment by turadg** [comment]
> I'd like to know why the ci bot is so unhappy before approving.

I had manually edited the yarn.lock to get rid of what appeared to be a stale dep on 5.2.2, but it turns out that Endo's eslint plugin is pretty specific about the TS version:
```
"@endo/eslint-plugin@^0.5.1":
  version "0.5.2"
  resolved "https://registry.yarnpkg.com/@endo/eslint-plugin/-/eslint-plugin-0.5.2.tgz#835d22e9ff17d9935f7f565e50a21ef07aa92ca2"
  integrity sha512-WzQmzBXoGGm5vb2mX/Ho9dS5wSaajmeE2PnFqiBUwPQ5ml7B0T7/QwzV5MSAv1ClyzDt3t5j36ENWxeibb2C9Q==
  dependencies:
    "@typescript-eslint/utils" "^6.6.0"
    requireindex "~1.1.0"
    tsutils "~3.21.0"
    typescript "~5.2.2"
```

**Comment by dckc** [comment]
> ... but it turns out that Endo's eslint plugin is pretty specific about the TS version:
> 
> ```
> "@endo/eslint-plugin@^0.5.1":
> ...
>   dependencies:
> ...
>     typescript "~5.2.2"
> ```

So we'll have both 5.2.2 and 5.3 for a while? That seems worth tracking in an issue. Do you know if we already have something close?

**Comment by turadg** [comment]
> So we'll have both 5.2.2 and 5.3 for a while?

A dev dependency of this repo has a dependency on an earlier version. That's pretty normal, imo. Eventually Endo will update its deps. In the meantime, there's no harm.

**Review by iomekam — APPROVED** [review]

**Pull request merged**
