### PR TITLE
feat(wallet-ui): reenable solo-only wallet

### PR DESCRIPTION
**Pull request by michaelfig**
refs: #6497

## Description

Put the built (solo-only) wallet from the `community-dev` branch where the `ag-solo` web server can find it.

### CODE REVIEW

**Review by dckc — COMMENTED** [review]
It's not clear to me how maintenance of this is intended to work. I suspect there's some rationale for this approach that we would benefit from writing down explicitly.

 - build products in the source tree
 - old BLD icons
 - another copy of lockdown

**Review by dckc — COMMENTED** [review]
wow... much cleaner... but now I don't really understand how it works. clue me in?

**Comment by michaelfig** [comment]
> wow... much cleaner... but now I don't really understand how it works. clue me in?

Here is a draft of what I intend to put in `packages/wallet/README.md`.  LMK if it's clear enough, and then I'll add it to this PR.

---

# Agoric Wallet

This directory contains two Agoric Wallet pieces:

- `api` - the legacy "off-chain" wallet used by `@agoric/solo`
- `ui` - the `@agoric/smart-wallet` user interface

The smart wallet has not yet subsumed all the features of the off-chain wallet.  Until it does, we require the `api` directory.

The `ui` directory no longer supports the off-chain wallet.  In order to work around this, we point the solo web server at a wallet UI package that does.

## Upgrading the solo wallet UI

Change the legacy wallet UI:

1. Check out the Agoric SDK branch containing a working ag-solo wallet (such as `community-dev`).
2. `yarn && yarn build`
3. `cd packages/wallet/ui`
4. Develop any changes to the wallet, then `yarn build`
5. `yarn publish`, setting the version number to end in `-solo.N` where N is greater than the previous.
6. Commit, create a PR and target it at the same branch in step 1.

Next, you can update the master branch:

1. Check out the Agoric SDK master branch.
2. Set the version of `@agoric/wallet-ui` in the `packages/wallet/package.json` to be the one you published (the exact version, no caret or tilde).
3. `yarn`
4. Test your wallet updates by running an ag-solo (sim chain is fine).
5. Commit, create a PR and target it at master.

After merging the first PR, you can merge the second.

**Review by godwn2890 — COMMENTED** [review]
@kriskowal

**Review by godwn2890 — COMMENTED** [review]
@godwn2890

**Review by dckc — APPROVED** [review]
the approach in the README comment looks good!

**Pull request merged**
