### PR TITLE
Marshal should treat -0 as 0. No symbols should be passable.

### PR DESCRIPTION
**Pull request by erights**
Also remove redundancy between marshal/test/test-marshal vs SwingSet/test/test-marshal.

### CODE REVIEW

**Review by warner — APPROVED** [review]
Looks good.

`sameValueZero` really is a horrible name for a function that's basically `Object.is` plus an extra case. If I hadn't reviewed this PR and saw that function pop up somewhere, I'd have no clue what it was supposed to be doing.

I'd kind of like to see the 0/-0 and symbol changes in separate PRs, but I don't think it's worth changing that now. Failing that, it'd be nice to have them as distinct commits within this PR.

This is a breaking change for the marshaller, so it'd be nice to make the "Conventional Commits" style of changelog messages. @michaelfig should correct me, but I *think* that means `feat(marshal): serialize -0 and 0 the same way` for one commit, and `feat(marshal): do not pass Symbols` for another. But again, it's not worth changing things now. We should just remember to bump the version numbers appropriately to reflect the breaking change.

**Comment by michaelfig** [comment]
> This is a breaking change for the marshaller, so it'd be nice to make the "Conventional Commits" style of changelog messages. @michaelfig should correct me, but I _think_ that means `feat(marshal): serialize -0 and 0 the same way` for one commit, and `feat(marshal): do not pass Symbols` for another.

The actual messages would be:

```
feat(marshal)!: serialize -0 and 0 the same way
feat(marshal)!: do not pass Symbols
```

Where the [exclamation points indicate a breaking change](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-to-draw-attention-to-breaking-change).  The two breaking changes will only result in one major semver bump between releases.

> But again, it's not worth changing things now. We should just remember to bump the version numbers appropriately to reflect the breaking change.

If we do a "Squash and Merge" we have the opportunity to make this into a Conventional Commit.

**Comment by erights** [comment]
> sameValueZero really is a horrible name for a function that's basically Object.is plus an extra case. If I hadn't reviewed this PR and saw that function pop up somewhere, I'd have no clue what it was supposed to be doing.

I fully agree. I would really like a better name before I merge this. The things a better name could emphasize:

- What it was originally for: key equality as used by JS Map and Set
- What we're using it for: the primitive equality that our distributed object equality bottoms out in. Our distributed object equality predicate also currently has a terrible name: `sameStructure`. Perhaps these could be changed together?
- What it actually does, which is a genuine equivalence class (so NaN equals NaN) that is less precise than `Object.is` in that -0 equals 0.

The first two bullets above are related, in that our upcoming passable maps will compare keys by sameStructure identity. This PR was motivated as a step towards passable collections.

Suggestions?

**Comment by katelynsills** [comment]
> Suggestions?

Adverbs + equals? "nearlyEquals" "almostEq" "primEquality", "sloppyEq"

**Comment by FUDCo** [comment]
In the Crockfordian tradition, how about “equalish”?

**Comment by kriskowal** [comment]
Throwing some words to see what sticks.

similar
equivalent
interchangeable
weakly equal
close enough
okay fine but next time i'm only taking the genuine article

I feel pretty strongly that these names should come in pairs for their
shallow and transitive couples. For example, equals and deepEquals, same
and deepSame, similar and deepSimilar. If harden were merely transitive
freeze, I’d have gone with deepFreeze to guide the user who learns by
skimming API docs.

**Comment by dtribble** [comment]
`sameKey` to specify the goal and the role in the computation that limits its semantics. I also like Kate's `sloppyEq` to suggest that it essentially exists to navigate the JS semantics, and we might find additional cases that we need to add.

**Pull request merged**
