### PR TITLE
test: Add Node.js 22.x to CI

### PR DESCRIPTION
**Pull request by kriskowal**
refs: https://github.com/endojs/endo/issues/2230

### CODE REVIEW

**Comment by erights** [comment]
The remaining error at https://github.com/Agoric/agoric-sdk/actions/runs/8769402273/job/24064849229?pr=9274

```
error @ava/typescript@4.1.0: The engine "node" is incompatible with this module. Expected version "^14.19 || ^16.15 || ^18 || ^20". Got "21.7.3"
```

will be an impediment to moving this PR forward. The mismatch is coming from @ava/typescript, not directly from our code. At https://www.npmjs.com/package/@ava/typescript I see that the most recent version of that package is 4.1.0, so we cannot fix it merely by upgrading to depend on a new version of this package. Do we need to patch it?

**Comment by erights** [comment]
patch-package --help says

>  2. Creating patch files
>  =======================
>
>    patch-package <package-name>[ <package-name>]
>
>  When given package names as arguments, patch-package will create patch files
>  based on any changes you've made to the versions installed by yarn/npm. 


I tried to patch it and was not able to for reasons I do not understand. At

image

I modified `agoric-sdk/node_modules/@ava/typescript/package.json`

But then

```sh
$ ./node_modules/.bin/patch-package @ava/typescript
patch-package 8.0.0
• Creating temporary folder
• Installing @ava/typescript@4.1.0 with yarn
• Diffing your files with clean files
⁉️  Not creating patch file for package '@ava/typescript'
⁉️  There don't appear to be any changes.
```
even though that package.json file still has my change. No patch file was generated.

**Comment by kriskowal** [comment]
I have heard that `patch-package` requires additional urging to capture changes to `package.json`.

**Comment by erights** [comment]
> I have heard that `patch-package` requires additional urging to capture changes to `package.json`.

Urging how?

**Comment by erights** [comment]
No longer needed. Closing.

**Pull request closed without merging**
