### PR TITLE
Add Github Action Workflow for all dapps

### LINKED ISSUE #1899: Add tests for any dapps that we want to keep current to agoric-sdk CI
**What is the Problem Being Solved?**

Currently, people make changes on agoric-sdk and unknowingly break dapps. 

**Design**

We should add a Github Action Workflow for any dapp that we want to keep up-to-date. That way, when someone makes a breaking change in agoric-sdk, they will be required to fix the dapps or add backwards compatibility before merging into trunk.

Dapps to cover:

- [x] dapp-fungible-faucet
- [x] dapp-card-store
- [x] dapp-otc
- [x] dapp-oracle
- [x] dapp-pegasus
- [x] dapp-encouragement
- [x] dapp-autoswap
- [x] dapp-simple-exchange
- [x] dapp-token-economy

### PR DESCRIPTION
**Pull request by katelynsills**
Adds a Github Action Workflow to test all the dapps. Note: for some dapps, there are no contract tests.

dapp-token-economy not included.

Closes #1899

### CODE REVIEW

**Comment by warner** [comment]
Oof, six files with contents that are almost identical? That sounds like a maintenance headache, is there any sensible way to factor out the common parts? Maybe put them all in the same file? I know YAML doesn't exactly have macros or `#include`s or anything, but maybe there's a way to use the `matrix:` feature over the dapp repository name to get this stuff factored out better.

**Comment by katelynsills** [comment]
> Oof, six files with contents that are almost identical? That sounds like a maintenance headache, is there any sensible way to factor out the common parts? Maybe put them all in the same file? I know YAML doesn't exactly have macros or `#include`s or anything, but maybe there's a way to use the `matrix:` feature over the dapp repository name to get this stuff factored out better.

Yup, I feel the pain. These are all copies of the template that is in workflow-templates. I don't know of a better way currently. The Github Actions documentation has no examples that I could find.

**Comment by katelynsills** [comment]
Huh, `matrix` could work as a solution. I'd like to explore that. Would it be ok with you @warner if this PR does not require it, but I will work on it afterward? We have low churn in changing anything in these files so it should not matter for a few days.

**Review by Chris-Hibbert — COMMENTED** [review]
The workflows individually look fine to me. If Brian is okay with putting off the bigger fix, I'm okay with the PR.

**Review by warner — APPROVED** [review]
I read through the first script, and it looks good. Assuming the rest are the same, r+

You might have @michaelfig double-check the cache actions, though, I don't fully understand how those work. I believe the actions here are conservative and the feel right, though.

**Comment by katelynsills** [comment]
> I read through the first script, and it looks good. Assuming the rest are the same, r+
> 
> You might have @michaelfig double-check the cache actions, though, I don't fully understand how those work. I believe the actions here are conservative and the feel right, though.

The cache actions didn't come from me - I assume they came from him

**Pull request merged**
