### PR TITLE
adopt Ava default file glob

### LINKED ISSUE #8273: adopt Ava default `files` glob
## What is the Problem Being Solved?

Our `package.json` has an `"ava":` section that configures a custom `"files"` glob. There are two problems with this:
1. It requires that every package.json repeat the same custom config. Customizing tool defaults should have a high bar because of the maintenance cost they incur.
2. The naming scheme chosen puts "test" at the front of what is obviously a test from its path context. To run a particular test from the CLI requires typing "test" three time to pick one: `yarn test test/test-something.js`. With Ava's default it would be `yarn test test/something.test.js` and typing the "so" can autocomplete. 

## Description of the Design

Remove all the custom globs.
Rename test files to `.test.js`.

## Security Considerations
none

## Scaling Considerations
none
## Test Plan
Before closing this ticket, check that all open PRs don't have new test files that would be ignored upon merge.
## Upgrade Considerations
none

### PR DESCRIPTION
**Pull request by turadg**
closes: #8273

## Description

Adds a script to migrate a package's file glob to the Ava defaults. See script docs and #8273 for motivation. It uses https://github.com/google/zx because I was banging my head on Bash options and version inconsistencies. 

The main thing to review is whether this change is good. Then the code in the first commit. The subsequent commits just are the code running over all the packages. When this PR is approved I'll rebase and re-run the batch to make all the migration commits anew.

Once this is in SDK, we can do the same in other Agoric repos. 

### Security Considerations

n/a
### Scaling Considerations

n/a
### Documentation Considerations

If anything, less need for documentation because it aligns with how Ava works by default.

### Testing Considerations

To run the script yourself, ensure,
```
npm install -g zx
```

### Upgrade Considerations

n/a

### CODE REVIEW

**Review by erights — APPROVED** [review]
With

> Once this is in SDK, we can do the same in other Agoric repos.

in the PR comment, this PR LGTM. However, I'd like to see such a PR actually happen and be approved for endo before seeing both merged. After a month of unanticipated pain bringing our two main repos back in sync, the last thing I want to see is for them to diverge again. This makes it hazardous to merge either until both are approved.

See https://github.com/endojs/endo/issues/1913

**Comment by Chris-Hibbert** [comment]
I think the script will mis-handle generated `snapshots`. The old file name appears in the file, and probably needs to be corrected so new generated files will match.

**Comment by turadg** [comment]
> I think the script will mis-handle generated `snapshots`. The old file name appears in the file, and probably needs to be corrected so new generated files will match.

Good catch. I'll regenerate them and delete the old one.

**Comment by turadg** [comment]
> Good catch. I'll regenerate them and delete the old one.

Second thought, it's passing without it. The names are just in the Markdown which isn't read by the tests.

@Chris-Hibbert is leaving the stale names in Markdown acceptable to you?

**Comment by turadg** [comment]
@Mergifyio queue

**Comment by turadg** [comment]
@Mergifyio refresh

**Review by Chris-Hibbert — APPROVED** [review]
Looks good.

**Comment by turadg** [comment]
@Mergifyio queue

**Pull request merged**
