### PR TITLE
Merge branch 'release-pismo' into merge-pismo-into-trunk

### PR DESCRIPTION
**Pull request by warner**
Merge branch 'release-pismo' into merge-pismo-into-trunk

This is a merge from `release-pismo` into current `master`. The few
conflicts were resolved in favor of what was already on `master`. The
patch-package diff on `release-pismo` for endo/bundle-source 2.3.0 was
removed, because `master` had been upgraded to 2.3.1, and had its own
patch.

This ensures that we haven't left any changes behind (included in
release-pismo but not on trunk).

Once complete, we can fast-forward `release-pismo` to this commit, to
complete #6364 ("merge all of trunk into release-pismo"). At that
point, both branches will have this commit as their shared common
ancestor.

### CODE REVIEW

**Comment by warner** [comment]
@gibson042 `packages/swing-store/src/snapStore.js` was one conflict I had to resolve (involving the definition of `sink`, I believe), please double-check that I didn't resolve it wrong.

**Review by kriskowal — APPROVED** [review]
My review and the tests appear to agree that merging `release-pismo` does not frustrate kernel consistency, so no additional work necessary to resync Endo. 👍

**Review by mhofman — APPROVED** [review]
Re swing-store state (and lack of changes): LGTM.

**Comment by warner** [comment]
note: this PR was to make sure `master` had everything from the release branch. At about the same time, we decided that everything on trunk was also safe to put on the release branch, so after this landed, I fast-forwarded `release-pismo` to the same commit (ebbfc42). We chose to fast-forward the branch rather than make a new commit so the common ancestor would be this commit (and there would be a clear width=1 choke point on a commit-graph diagram). If instead I'd filed a PR against `release-pismo` from `master` (or rather a branch created from master without any new commits on it, to avoid auto-deleting `master`), then the diagram wouldn't have a clear choke point, and future commit-history spelunkers would have a harder time eyeballing the common ancestor commit.

**Pull request merged**
