### PR TITLE
add tildot transform to bundle-source

### PR DESCRIPTION
**Pull request by warner**
doesn't work yet

refs #1101

### CODE REVIEW

**Comment by warner** [comment]
ugh, there's still a cycle: bundle-source imports transform-eventual-send for the transformer function. transform-eventual-send imports the eventual-send bundle. The eventual-send bundle is built by `yarn build` inside transform-eventual-send, which runs `scripts/build-esend.js`, which imports eventual-send.

@michaelfig what if I change `build-esend.js` to use the `rollup` API *without* bundle-source? Hrm, I guess transform-eventual-send wants the full bundle format.

**Comment by michaelfig** [comment]
> @michaelfig what if I change `build-esend.js` to use the `rollup` API _without_ bundle-source? Hrm, I guess transform-eventual-send wants the full bundle format.

The other way is to explicitly add the `HandledPromise` global to all cases where bundles are imported.  We have to do that for SES2, so maybe this is a good time to start.

**Comment by michaelfig** [comment]
Urgh.  But we then cross realm boundaries, which is bad.

**Comment by michaelfig** [comment]
I think you're right: `built-esend.js` can use Rollup directly, and transform-eventual-send can just cope with that.

**Comment by warner** [comment]
oh, what if I put the small `makeTransform()` function at `@agoric/transform-eventual-send` (i.e. `packages/transform-eventual-send/index.js`), and move the larger `makeEventualSendTransformer()` into `@agoric/transform-eventual-send/somethingelse` (i.e. `packages/transform-eventual-send/somethingelse.js`)? Then anyone who does `import { makeTransform } from '@agoric/transform-eventual-send'` won't drag `bundles/eventual-send` into their dependency graph, breaking the cycle.

I'll have to modify the callers (maybe just default-evaluate-options) to import the new thing.

**Comment by michaelfig** [comment]
> I'll have to modify the callers (maybe just default-evaluate-options) to import the new thing.

That's the best solution.  Sorry I circled around all three solutions multiple times rather than just settling on this one. 😝

**Review by michaelfig — APPROVED** [review]
LGTM!  Great to see this land!

**Pull request merged**
