### PR TITLE
Split test storeGC

### PR DESCRIPTION
**Pull request by mhofman**
## Description

I've been hitting the issue in #5202 pretty consistently with a seemingly unrelated commit from #5124: https://github.com/Agoric/agoric-sdk/commit/4bd30d994fb29c07d2f203b3d5ee9f23687dc92b.

The only solution I found was to split up the `test-storeGC.js` into multiple files, which I've extracted into this PR.

### Testing Considerations

Making future tests pass again!

### CODE REVIEW

**Comment by FUDCo** [comment]
I'm confused about the role of the first commit here.  Should this PR consist solely of the second commit?

**Comment by mhofman** [comment]
The first commit is the motivation for the second one. Since it's self contained as well, I figured  putting them in the same PR didn't hurt.

**Comment by FUDCo** [comment]
I think these are completely decoupled.  You need the test split to run the tests at all, but that's independent of the other changes -- those changes didn't cause the need to do the test split, it's just that the test failures are blocking you.  But they'll block anybody else trying to make forward progress against `master` with more or less the same runtime setup you've got (i.e., Node 16 et al).  When I reproduced the test failures in my environment I didn't have your first set of changes at all.  Since these are two completely unrelated bits of work, I think they should be separate PRs.

**Comment by mhofman** [comment]
Well at least in my environment, and apparently in CI, the store GC tests work fine without the first commit, but fail with the first commit. So I wouldn't say they're independent, and that commit was indeed my motivation for the split

**Comment by mhofman** [comment]
@FUDCo I've removed the first commit, PTAL

**Review by FUDCo — APPROVED** [review]
👍

**Pull request merged**
