### PR TITLE
fix: alt syntax for positive but faster assertions

### PR DESCRIPTION
**Pull request by erights**
Like https://github.com/endojs/endo/pull/1280

Replace some occurrences of
```js
assert(..condExpr.., X`..detailsString..`);
```
with
```js
..condExpr.. || assert.fail(X`..detailsString..`);
```

I only made the changes that I was easily able to do via regexp search and replace in vscode
```
^\s*assert\(\n\s*(.*?),\n\s*X`(.*?)`,\n\s*\);
($1) || assert.fail(X`$2`);
```
and similar, followed by a global `yarn lint-fix` and then repair until everything tested green again. No doubt there are more cases that I missed. But from @dtribble 's measurements, these are already enough to show significant perf improvements.

### CODE REVIEW

**Comment by erights** [comment]
See also https://github.com/endojs/endo/pull/1280

**Comment by erights** [comment]
Ready for review!

**Review by turadg — APPROVED** [review]
LGTM. I spot checked the mechanical commit and verified the TS work-around commits. Consider squashing those two (into the latter name) before landing.

**Comment by turadg** [comment]
@Mergifyio requeue

**Comment by dckc** [comment]
> from @dtribble 's measurements, these are already enough to show significant perf improvements.

Somebody share those measurements, please?

**Pull request merged**
