### PR TITLE
chore: update eslint to prevent dapp-card-store build issues

### LINKED ISSUE #2797: Upgrade ESLint to fix dapp-card-store build error
> dapp-card-store-ui
$ react-scripts build

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "^7.11.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  /home/runner/work/agoric-sdk/agoric-sdk/node_modules/eslint (version: 6.8.0) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /home/runner/work/agoric-sdk/agoric-sdk/node_modules/eslint is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls eslint in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed eslint.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

### PR DESCRIPTION
**Pull request by katelynsills**
closes #2797

### CODE REVIEW

**Comment by erights** [comment]
@katelynsills have you seen https://github.com/Agoric/agoric-sdk/issues/2805 ? Can you review those as a group instead?

**Review by michaelfig — DISMISSED** [review]

**Comment by erights** [comment]
The latest I see among our repos is 7.23.0, so why 7.11.0 ? #2805 does 7.23.0

**Comment by katelynsills** [comment]
> @katelynsills have you seen #2805 ? Can you review those as a group instead?

I did see it, but I don't think it's on the critical path for Beta, so I'm putting it on the back burner for now. This PR is necessary though.

**Review by dtribble — APPROVED** [review]

**Comment by erights** [comment]
Why not #2804?

**Comment by katelynsills** [comment]
> The latest I see among our repos is 7.23.0, so why 7.11.0 ? #2805 does 7.23.0

I'm limited on time and just trying to fix the error, and create-react-app uses 7.11.0 right now. Updating all our dependencies or all of eslint is bigger than I can do right now.

**Review by erights — CHANGES_REQUESTED** [review]
Why not #2804 ?

**Comment by erights** [comment]
Sorry, I see the answer. But #2804 is green. Doesn't that mean it is non-problematic?

**Comment by erights** [comment]
(Green modulo XS, but that's independent)

**Comment by katelynsills** [comment]
> Sorry, I see the answer. But #2804 is green. Doesn't that mean it is non-problematic?

Sure, that's fine. I just approved it and will close this.

**Pull request closed without merging**
