### PR TITLE
feat(xsnap)!: Update Moddable SDK and xsnap-native

### LINKED ISSUE #6759: Synchronize with version 3.6.0 or newer of Moddable SDK
## What is the Problem Being Solved?

Since August 2022 we have not been able to update the Moddable SDK after encountering [divergences between validators in the integration test](https://github.com/Agoric/agoric-sdk/issues/6022) in the [last attempt to sync](https://github.com/Agoric/agoric-sdk/pull/6011). Since then, after fixing other divergences on mainnet (#6588), we have identified commits in the Moddable SDK tree which were the likely cause the divergences experienced when first trying to update. There are 2 remaining commits which are currently causing an unexpected difference in execution when replaying transcripts.

## Details of the upgrade step

The following 2 commits have been identified as causing issues, and already fixed:
- [XS: fuzzilli 38](https://github.com/Moddable-OpenSource/moddable/commit/2511eda9781bf4cb750a88282bced0a1d4f12fcc), fixed by [XS: initialize slot next when caching arrays](https://github.com/Moddable-OpenSource/moddable/commit/91aa14cf419c2055c7a4ba5df5ee160e15535225)
- [XS: performing pointer subtraction with a null pointer has undefined behavior](https://github.com/Moddable-OpenSource/moddable/commit/f660795f896ea7f17cedb770e11a1d1d576dabe6), fixed by [XS: revert "performing pointer subtraction with a null pointer has undefined behavior" without warning](https://github.com/Moddable-OpenSource/moddable/commit/4e23805c82e7e811881b3e2e484a4f76a090ea35)

The following 2 commits have also been identified as causing unexpected differences in execution, but no fix or explanation has been provided yet:
- [XS profile ID by function definition](https://github.com/Moddable-OpenSource/moddable/commit/29a2fad46f9b953ed67ca0b73832d0cc730f5430)
- The [xsCode.c changes](https://github.com/Moddable-OpenSource/moddable/commit/7d1bd60b74f82c66c6693ef5f91417c8a4351976) of [XS: profiler Linux Windows](https://github.com/Moddable-OpenSource/moddable/commit/5747ad17a99dcc0126464d004a9b7a5049d5e908)

## Test Plan

Once a fix has been published for the remaining unexplained execution differences, create a test branch from release-pismo with the updated Moddable SDK, and use the enhanced replay tool (#6723) to replay a transcript of all mainnet vats (but in priority vat18 and vat6 which have shown susceptible to divergences). Do not merge or publish this test branch on pismo.

After that, a normal branch and PR to update master can be created.

### PR DESCRIPTION
**Pull request by mhofman**
closes: #6759
supersedes: #6011 #6768

## Description

Updates our old fork of the Moddable SDK to the official 3.7.0 version

Updates xsnap-native with the following changes (details at https://github.com/agoric-labs/xsnap-pub/pull/34):
- handle profiler and instrumentation changes (disabled)
- updated promise queue behavior

### Security Considerations

This update contains a lot of bug fixes in XS found by fuzzing tools. This should be a strict improvement.

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

Followed the following process (now described in https://github.com/Agoric/agoric-sdk/issues/6929)
- Created a "chain transcript" from mainnet using a follower based on the pismoC version of XS (minus agoric-sdk version bump), equivalent to `mhofman/pismo-with-replay-tools-improvements-updated-xs~1`
- Replayed "chain transcript" using updated version of xsnap-worker (slightly different revision actually tested, but no effective changes to xsnap-worker), equivalent to branch `mhofman/pismo-with-replay-tools-improvements-updated-xs`
- Extracted vat transcripts
- Replayed vat transcripts by forcing a reload into a new worker after each snapshot being taken, and comparing the execution and snapshot hashes with workers that didn't reload.
- Observed no anachrophobia nor any snapshot hash differences indicating that no reload based divergences were experience on the mainnet derived data set

(PR #6931 for chain transcript replay tool against master)

### CODE REVIEW

**Comment by mhofman** [comment]
Apparently something broke, and I'm surprised the testing I didn't uncover these issues.

**Comment by warner** [comment]
I skimmed the `xsnap` changes and they look great. I couldn't look at the `xs` changes.. as usual we rely upon upstream's diligence and your thorough testing.

Not sure what's going on with the test (slogSender something?), but assuming it's something trivial, I think the PR is good to go once it works again.

(hm, I did notice some more file descriptors referenced in the xsnap code.. but I think that only happens if you ask for instrumentation/debugging to be turned on. There's a remote chance that the extra FDs used for the slogsender pipe are getting inherited by the xsnap child process and colliding with something it wants to use for debugging. That would qualify as a non-trivial problem :)

**Comment by mhofman** [comment]
> Not sure what's going on with the test (slogSender something?), but assuming it's something trivial, I think the PR is good to go once it works again.
> 
> (hm, I did notice some more file descriptors referenced in the xsnap code.. but I think that only happens if you ask for instrumentation/debugging to be turned on. There's a remote chance that the extra FDs used for the slogsender pipe are getting inherited by the xsnap child process and colliding with something it wants to use for debugging. That would qualify as a non-trivial problem :)

Oh that's an excellent idea. When I ran my tests I hadn't had time to fully understand the instrumentation changes, so I had ommitted that commit entirely. As described at https://github.com/agoric-labs/xsnap-pub/pull/34, I didn't feel fully confident in them so I disabled them using the build option, thinking the new select would result in a no-op because we're not using these FDs, but maybe that isn't the case. I'll do more testing.

**Comment by mhofman** [comment]
I figured it out: faulty disablement of the new intrument logic, and that code hangs if the fd doesn't exist. More info at https://github.com/agoric-labs/xsnap-pub/pull/34#issuecomment-1421666509

**Comment by mhofman** [comment]
@warner, all checks are green, PTAL

**Review by warner — APPROVED** [review]
recent changes to xsnap/ look good, I think we're go

**Pull request merged**
