### PR TITLE
sort directory entries when looking for vats

### LINKED ISSUE #363: vat enumeration non-deterministic?
Using node, I got:

```
Assigned VatID v1 for Genesis vat exchange
Assigned VatID v2 for Genesis vat host
Assigned VatID v3 for Genesis vat http
```

with xs, I got:

```
Assigned VatID v1 for Genesis vat zoe
Assigned VatID v2 for Genesis vat wallet
Assigned VatID v3 for Genesis vat mints
```

(I'm not sure the order is consistent in node either.)

I suppose this is due to non-determinism in directory listings.

@dtribble tells me this non-determinism shouldn't be exposed. We should sort them or some such.

### PR DESCRIPTION
**Pull request by dckc**
fixes: #363

### CODE REVIEW

**Review by erights — COMMENTED** [review]
LGTM but you should get a reaction from @warner before proceeding

**Comment by dckc** [comment]
Ok... but note that I can't really proceed anyway. Somebody with rights to merge will have to do it.

**Comment by dckc** [comment]
I re-formatted it after running into **no-nested-ternary**.

_Functional programming habits die hard, again._

**Review by erights — COMMENTED** [review]
Still LGTM but still wait for @warner

**Comment by dckc** [comment]
@warner ? ping?

**Comment by dckc** [comment]
hmm... xs is _still_ allocating vat IDs in reverse order, even with this sort.

**Comment by dckc** [comment]
ugh. now it seems to be working. Did my build get out of sync somehow? hmm....

**Comment by warner** [comment]
looks good, I'll land it

**Pull request closed without merging**
