### PR TITLE
feat!: rename EndorsedUI to ReferencedUI

### LINKED ISSUE #7839: Changed 'EndorsedUI' to 'ReferencedUI' as a governed parameter so it reflects same in Econ Gov UI
## What is the Problem Being Solved?

This is a contract change to support https://github.com/Agoric/dapp-inter/issues/125.

## Description of the Design

Change 'EndorsedUI' to 'ReferencedUI'. End result should be Econ Gov UI should not show 'EndorsedUI' but 'ReferencedUI' to align with consistent language including #125. 
 https://agoricopco.slack.com/archives/C03FUCJV2J2/p1685031797142509

### PR DESCRIPTION
**Pull request by samsiegart**
fixes: https://github.com/Agoric/agoric-sdk/issues/7839

## Description

Rename the vault factory governed param "EndorsedUI" to "ReferencedUI"

### Documentation Considerations

Updated inter protocol docs

### Testing Considerations

Updated unit tests.

Dapps should be backwards compatible already, will confirm.

### CODE REVIEW

**Comment by samsiegart** [comment]
This is a PR, does it actually need a label and assignee?

**Review by dckc — COMMENTED** [review]
Code looks good, but the justification for the breaking change is a citation to an issue that doesn't seem relevant. Hope to get clarity.

@ivanlei perhaps you have more context? If so, maybe you want to approve?

**Review by dckc — APPROVED** [review]
got some clarification from @ivanlei 

I'm still puzzled about the `#125` reference, but I suppose that's not critical.

**Comment by samsiegart** [comment]
Thanks for review! Yea should be https://github.com/Agoric/dapp-inter/issues/125, different repo

**Pull request merged**
