### PR TITLE
fix: When setting a new zcfBundleCap, store it in baggage

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
refs: #8806

## Description

Copy of #8806 for the upgrade-15 release branch

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

As we're testing zoe upgrades in a3p, verify that the newly set value survives zoe upgrade.

### Upgrade Considerations

Prep it for upgrade.

### CODE REVIEW

**Comment by mhofman** [comment]
@Chris-Hibbert it looks like the `zoe.js` part of the change from https://github.com/Agoric/agoric-sdk/pull/8806/files#diff-0a3a93511513efa0de6a26ae9a7e399dbcfca5adb2d71bd96245382fef8f2500 is not included here. Any reason why?

**Comment by Chris-Hibbert** [comment]
> it looks like the zoe.js part of the change from https://github.com/Agoric/agoric-sdk/pull/8806/files#diff-0a3a93511513efa0de6a26ae9a7e399dbcfca5adb2d71bd96245382fef8f2500 is not included here. Any reason why?

That's definitely either an oversight or just a bad merge. Those changes should be included here.

**Review by mhofman — CHANGES_REQUESTED** [review]
Some changes are missing in the rebase.

**Comment by Chris-Hibbert** [comment]
> Some changes are missing in the rebase.

Thanks for catching this. I added the missing commit.

**Review by mhofman — APPROVED** [review]

**Pull request merged**
