### PR TITLE
Update to depend on ses 0.12.5

### PR DESCRIPTION
**Pull request by erights**
Changing to WIP Draft until CI errors dealt with.

### CODE REVIEW

**Review by FUDCo — APPROVED** [review]
Hoorah for housecleaning!

**Comment by erights** [comment]
@dckc I have an approval from @FUDCo and I am mostly green no conflicts, and so almost ready to merge. However, I am getting one CI error from `test:xs` that I do not know how to diagnose. Could you take a look and let me know if I should merge anyway? Thanks.

@michaelfig and @katelynsills I took you off the reviewers list. However, @katelynsills , for many of the test cases I changed, I think you wrote them, so you might want to take a look. It was semi-manual but purely mechanical so I'm reasonably confident that the test changes didn't break anything.

**Review by katelynsills — APPROVED** [review]
Glanced through it, but looks good to me!

**Comment by dckc** [comment]
I don't recognize these symptoms. Let me investigate a but more...

```
{
  status: 'not ok',
  message: 'running test script: Possible direct eval expression rejected at <unknown>:4019. (SES_EVAL_REJECTED)',
  filename: 'test/unitTests/contractSupport/test-bondingCurves.js',
  label: ''
}
```

**Comment by dckc** [comment]
It seems to be tripping over...

```
     // This flag allow us to determine if the eval() call is an done by the
```
https://github.com/endojs/endo/blob/51adac66bde02402d4dc4422455b50da0f8a8ffb/packages/ses/src/scope-handler.js#L57

odd: that code isn't new.

when I change that `eval()` to `eval`, it still falls over; this time in the magic 8 lines:

https://github.com/endojs/endo/blob/51adac66bde02402d4dc4422455b50da0f8a8ffb/packages/ses/src/make-evaluate-factory.js#L63

**Review by dckc — CHANGES_REQUESTED** [review]
This is causing the first zoe `test:xs-unit` test to fail, which suggests it would make all of them fail.

When I try to skip `test-bondingCurve.js` it still fails on the first test script, though in a different mysterious way:

```
# test script: test/unitTests/contractSupport/test-depositTo.js
Module level directives cause errors when bundled, 'use jessie' was ignored.
(TypeError#1)
TypeError#1: Cannot assign to read only property 'hasOwnProperty' of object '[object Object]'

  at Generator.next (<anonymous>)
  at runMicrotasks (<anonymous>)
```

**Review by dckc — APPROVED** [review]
as discussed, we'll postpone the XS interaction for now

**Pull request merged**
