### PR TITLE
7181 durable auctioneer

### PR DESCRIPTION
**Pull request by turadg**
refs: #7181

## Description

Makes the auctioneer contract durable so it can run on-chain. A step towards full upgradability (#7181).

### CODE REVIEW

**Comment by Chris-Hibbert** [comment]
I think changes to liveslots require approval from a kernel expert.

**Review by Chris-Hibbert — APPROVED** [review]
Thanks, Turadg. This is a very clean transformation of the code.

**Comment by turadg** [comment]
> I think changes to liveslots require approval from a kernel expert.

Agree. I'm going to merge because I have confidence in the changes. Hoping that @warner or @FUDCo can take a look and reply with whether they want any changes.

**Comment by FUDCo** [comment]
> Agree. I'm going to merge because I have confidence in the changes. Hoping that @warner or @FUDCo can take a look and reply with whether they want any changes

Yeah, this seems totally fine.  It's hygiene, not a functionality change.

**Comment by turadg** [comment]
@Mergifyio refresh

**Pull request merged**
