### PR TITLE
update Yarn to v3 (berry)

### LINKED ISSUE #451: eventually move to Yarn 2+ (currently 4)
@katelynsills and @btulloh noticed that the Yarn docs encourage folks to install Yarn 2, but this tree only works with Yarn 1. A quick survey showed that many (all?) of us have Yarn 1 installed locally, so we haven't noticed the problem before.

Ideally our tree should work with both versions. Fallback position is to work with Yarn 2 and make sure the docs point people at installing it rather than yarn 1 (with a stretch goal of somehow detecting when you're using yarn 1 and printing a useful error message).

### PR DESCRIPTION
**Pull request by turadg**
closes: #451

## Description

Version 4 seems [close to release](https://github.com/yarnpkg/berry/milestones/4.0.0) (4.0.rc53 is out) but [the breaking changes](https://github.com/yarnpkg/berry/issues/3591) won't affect us much so let's go ahead to v3 now. https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#master

### Security Considerations

n/a. Though does open the option to keep the registry cache in the repo, reducing supply chain risk.

### Scaling Considerations

n/a

### Documentation Considerations

I haven't noticed anything breaking workflows. If they are it deserves a loud Slack announcement.

### Testing Considerations

CI

### Upgrade Considerations

n/a

### CODE REVIEW

**Comment by turadg** [comment]
Need to fix CI: https://github.com/yarnpkg/berry/discussions/2621

**Comment by turadg** [comment]
dapp tests failing to run `agoric` bin:
```
❯ ./bin/agoric --version
(ReferenceError#1)
ReferenceError#1: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/opt/agoric/yarn3-sdk/packages/agoric-cli/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
This file is being treated as an ES module because it has a '.js' file extension and '/opt/agoric/yarn3-sdk/packages/agoric-cli/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
  at Object.eval (eval at <anonymous> (eval at makeEvaluate (file:///opt/agoric/yarn3-sdk/node_modules/ses/src/make-evaluate.js:92:27)), <anonymous>:1)
  at eval (eval at makeEvaluate (file:///opt/agoric/yarn3-sdk/node_modules/ses/src/make-evaluate.js:92:27), <anonymous>:12:22)
  at safeEvaluate (file:///opt/agoric/yarn3-sdk/node_modules/ses/src/make-safe-evaluator.js:78:14)
  at eval (file:///opt/agoric/yarn3-sdk/node_modules/ses/src/make-eval-function.js:22:14)
  at Object.<anonymous> (/opt/agoric/yarn3-sdk/node_modules/@yarnpkg/core/lib/miscUtils.js:262:21)
```

Something in the bowels of SES. Any ideas @kriskowal ? 

UPDATE: it was the `eval('require')` that the package does to work around something in Webpack. I don't know why you'd build Yarn with Webpack but this patch works for now https://github.com/Agoric/agoric-sdk/pull/8461/files#diff-d6b4713855f18df4a84e2fb446d5915b8d5fcafe0be935795c31ddc653e9f4c9

**Comment by mhofman** [comment]
> n/a. Though does open the option to keep the registry cache in the repo, reducing supply chain risk.

Can you clarify?

> Version 4 seems [close to release](https://github.com/yarnpkg/berry/milestones/4.0.0) (4.0.rc53 is out) but [the breaking changes](https://github.com/yarnpkg/berry/issues/3591) won't affect us much so let's go ahead to v3 now.

If we're going through the trouble of upgrading with a breaking change version, have we considered alternative package managers (npm or pnpm)?

In general I am concerned about these low level changes that affect the structure of the repo while we have a release branch to maintain. The rebuild of xsnap motivation seems like an issue that should be fixed by our xsnap package, not the package manager used.

**Comment by turadg** [comment]
Blocked by https://github.com/Agoric/agoric-sdk/issues/8381

**Pull request closed without merging**
