### PR TITLE
Implement firstPriceAuction smartcontract.

### PR DESCRIPTION
**Pull request by zarutian**
refs: #3882

## Description

Adds firstPriceAuction smartcontract. Such auction is better known to most people as highest bid when the timer rings auction.

### Security Considerations

This change is basically based on the existing secondPriceAuction smartcontract so same security considerations it has applies here.

### Documentation Considerations

Pretty much copy pasta of secondPriceAuction with minimal changes

### Testing Considerations

The included test should work.

### CODE REVIEW

**Comment by zarutian** [comment]
paging @katelynsills or @michaelfig for review

**Comment by katelynsills** [comment]
Thanks @zarutian! We'll put this in our queue to review

**Comment by zarutian** [comment]
Can I get rough aprox ETA on when someone will review this?

**Comment by katelynsills** [comment]
Hi @zarutian, building a first price auction contract was a Gitcoin developer bounty issue (https://gitcoin.co/issue/Agoric/agoric-sdk/3882/100026650) which we have a submission for. Unfortunately, we can't review and merge additional submissions outside of that process. I'm going to close this PR, but thank you so much for your work on this. If you're interested in tackling another issue, let us know and we can see what might work best.

**Comment by zarutian** [comment]
Feel free to give these commits to them, I do not particularly care. Just wanted to help them along a bit and most of the thing is based of the second price auction smart contract code.

**Comment by katelynsills** [comment]
ok, thank you @zarutian!

**Pull request closed without merging**
