### PR TITLE
Add Compatibility w/ my Issuer

### PR DESCRIPTION
**Pull request by Mentors4EDU**
Hi, I am running a large scale app on the test network (non-production mode for beta users).
I'm looking to add compatibility w/ my issuer instead of having to make users also download a clone of the SDK or input the repo manually.
I added the config and symbol to the `issuer.js` file.
Please tag me if you have any questions.

Best regards, Andrew

### CODE REVIEW

**Comment by Mentors4EDU** [comment]
I also ran tests to make sure I didn't input anything wrong in the Javascript.

Screenshot from 2021-06-03 20-46-58
Screenshot from 2021-06-03 20-46-42

**Comment by rowgraus** [comment]
Hi Mentors4EDU -

Great to have you building.  For this specific change, adding your issuer to the bootstrap process is not the best way to handle it.  

The right way to approach it would be to have your dapp suggest a new issuer to the user's wallet.  An example of this is here: https://github.com/Agoric/dapp-card-store/blob/7d0d9ad92a9830f935ba9627027af10ce19e7bd6/ui/src/App.js#L110

Are you active in Discord?  If not, you should join and connect with us there.  Happy to help out as you're building.

**Comment by Mentors4EDU** [comment]
Hi @rowgraus 
Problem is I want to minimize how many applications the user runs in order for it to be more user friendly. Are you sure making an issuer suggestion into the DAPP is the best way to handle it? Where do you input specific symbol and all that as opposed to it being available in the the run process?

The DAPP I'm making will likely onboard a few thousand users and have alot of liquidity so I want to make sure to load the symbol the easiest way possible.

Do let me know your thoughts?

**Comment by katelynsills** [comment]
> The DAPP I'm making will likely onboard a few thousand users and have alot of liquidity so I want to make sure to load the symbol the easiest way possible.

Hi @Mentors4EDU, that's great news. I understand wanting to use the simplest process possible. Here's how to do that:

You're going to need to write a contract that creates the `mint`, `issuer`, and `brand` for your tokens. To start, you can use the [contract in dapp-fungible-faucet](https://github.com/Agoric/dapp-fungible-faucet/blob/main/contract/src/contract.js) as an example. Line 23 will need to change to something like:

```js
const zcfMint = await zcf.makeZCFMint(yourTokenNameHere,
    AssetKind.NAT,
    { decimalPlaces: 18 }
);
```

In this contract, you can provide your own logic for how tokens get distributed and the rules associated with it (e.g. does the user need to provide anything in exchange? Are you minting and then giving it to only one or two users of your choice, who can sell on the open market in a different contract?).

> Problem is I want to minimize how many applications the user runs in order for it to be more user friendly. 

Understood. Each user will need to run their own wallet to store digital assets and make offers, so that will always be a requirement. But, apart from the wallet, your users should only need to use your application, for the large part. And your application can make the call to the user's wallet to suggest a new issuer directly. So I think we can minimize the number of applications pretty easily, but let me know if there's something I've missed.

Let us know if you'd like to chat in real-time. We are available on Discord/ Zoom and happy to learn more about your use case.

**Comment by Mentors4EDU** [comment]
Hi, @katelynsills 
I think I understand now how to issue it directly through the `issuer` variable. My only other question before I close this, is how does one call multiple contracts at the same time in the `deploy.js` file? For example, they have an `issuer.js` and a `storage.js` contract w/ `Name X` and `Name Y`, how can they call both contracts at the same time in the `deploy.js` file? Is it similar to how you call packages and modules already in JavaScript or does Agoric have its own naming conventions? I haven't seen anything in the documentation regarding that and deploying it all in one contract may get a bit messy. If there is an easier way to do that, then I don't really need my issuer built into the run process. 

Please let me know as I been searching for almost 2 hours before making this pull request and it would be quite helpful.

Best regards, Andrew

**Comment by katelynsills** [comment]
Hi @Mentors4EDU, by calling multiple contracts in `deploy.js`, can you tell me more about what you mean? Are there two different contracts that you want to deploy? Does one of the contracts need special access to the other?

**Comment by Mentors4EDU** [comment]
So @katelynsills 
I'm deploying the issuer contract which is tied to my coin, a contract that lets new users mint new tokens untop of the issuer and a storage contract for various data store functions. I believe each contract is about 400 lines of code and some have specific functions they need to call untop of each other. Think of me wanting to deploy in Agoric in a similar way to reading JavaScript modules or how one deploys smart contracts via Ethereum's solidity. What is the best way to do that if they have more than one `contract.js` file?

**Comment by katelynsills** [comment]
Gotcha, @Mentors4EDU. Thanks, that was very clear.

There's a few ways to use code on the Agoric chain. We can help decide which way is best for your use case, but here are some options:

1. **For helper functions and library code**: Currently, the easiest way to reuse functionality is to import the code into your contracts using normal JavaScript imports. For instance:

```
import { something } from 'localFileOrNPMPackage';

const start = zcf => {
    something();
    ... // contract code here
```
This will include the `something` code in the bundle of code that is associated with this contract. So, if this is reused in multiple contracts, each version has a copy of that code.

2. **For one contract to create a sub-contract**: In this case, one contract instance can create another contract instance. For an example of this, see the OTC Desk contract that [creates bespoke quotes for customers by creating a new sub-contract for each quote](https://github.com/Agoric/dapp-otc/blob/fbdd0601977d14c6e49f360845c718e5cc8a36a6/contract/src/otcDesk.js#L58). For each quote, the OTC Desk escrows assets into the sub-contract and gives the customer an invitation to join the sub-contract (effectively, a financial option). This design benefits the customer tremendously, because if they accept, they only interact with the well-known sub-contract and are never affected by misbehavior in the OTC Desk itself. ([YouTube video of the live coding session explaining more here](https://www.youtube.com/watch?v=faxrecQgEio)). 

3. **For one contract to be given admin powers over another contract, after both have been instantiated**: When a contract instance is made, the user/contract who made the instance gets a number of objects back. One of those objects, the `creatorFacet` is defined by the contract to contain any functionality that only the creator should have. So for instance, if you want to be able to shutdown the contract but not allow anyone else to do so, you could add that functionality to the `creatorFacet` in your contract code. Then, you could pass this along to the second contract using that contract's `creatorFacet`,  in your `api/deploy.js` script. For example:

  ```js
  const { creatorFacet: cfA } = await E(zoe).startInstance(contractAInstallation);
  const { creatorFacet: cfB } = await E(zoe).startInstance(contractBInstallation);
  await E(cfB).controlContract(cfA);
  ```
  where the methods on `cfA` and `cfB` are determined by the contract code for each.

4. **For one contract to be given public access to the other contract, after both have been instantiated**: This is a lot like Option 3, but instead of it being dangerous authority that is shared, like the power to shutdown the contract, only authority that is available generally is shared. In addition to the `creatorFacet`, there is the `publicFacet`, which includes any functionality that should be available to anyone who knows about the contract. For instance, the ability to trade on an AMM can be gotten from the `publicFacet` for the AMM contract instance. This can be given to the second contract instance as well:

```js
const { creatorFacet: cfA, publicFacet: pfA } = await E(zoe).startInstance(contractAInstallation);
const { creatorFacet: cfB } = await E(zoe).startInstance(contractBInstallation);
await E(cfB).getAccess(pfA);
```
where `getAccess` is named and defined by the code in contractB. 


I dropped a ton of information, but I hope this helps. Happy to talk through the options to see what might work best for you. As an aside, you can mint multiple different kinds of tokens in the same contract, so the three contracts you mentioned might be able to be combined into one or two, if that is easier.

**Comment by Mentors4EDU** [comment]
Actually, I think that helps for now @katelynsills
If I run into any problems, I may check back w/ the dev team on Discord.
I will go ahead and close this for now.

**Comment by katelynsills** [comment]
Sounds good. Thanks, @Mentors4EDU

**Pull request closed without merging**
