### PR TITLE
Add a getAssays() method for the UI to SimpleExchange's publicAPI

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
@jfparadis Is this the kind of thing you need?

[for the UI](https://github.com/Agoric/agoric-sdk/issues/541)

### CODE REVIEW

**Comment by katelynsills** [comment]
We can get this from Zoe already through the getInstance method. Let's not add it to the contract.

**Comment by Chris-Hibbert** [comment]
@katelynsills, @jfparadis  

I think JF wants the wallet UI to be able to get the assays. It doesn't have direct access to zoe, so it can't get them that way. What objects does it have access to that it could rely on? It has the wallet backend, but I'm not sure they have a common reference for the particular exchange instance. Who can the wallet UI ask instead?

I think the most up-to-date diagram we have is in the [Agoric Powerbox Framework](https://docs.google.com/document/d/1hnQ3jMMnzg03I6vL54zElqX833mQt9nT2JI7kKg1SOE/edit#) write-up, which doesn't show much detail about which message are sent between the various parties, or what objects they end up with references to. Only a few of the messages in that diagram are even alluded to, much less named.

**Comment by katelynsills** [comment]
There shouldn't be a scenario in which something might have access to the contract publicAPI and not have access to Zoe. I don't see why that would happen. They are both presences and Zoe should be even more accessible through things like the registry than the contract publicAPI.

Currently, autoswap [gets the assays](https://github.com/Agoric/agoric-sdk/blob/c9cc4e82edffa51ef7297e87d9b225e7b29c1ab8/packages/cosmic-swingset/lib/ag-solo/vats/lib-exchange.js#L47) by using the `zoe.getInstance`method:

```js
function getOfferRules(instanceId, extent0, assayId0, assayId1) {
    const instanceHandleP = E(registrar).get(instanceId);
    const regAssay0P = E(registrar).get(assayId0);
    const regAssay1P = E(registrar).get(assayId1);

    return Promise.all([instanceHandleP, regAssay0P, regAssay1P]).then(
      ([instanceHandle, regAssay0, regAssay1]) =>
        E(zoe)
          .getInstance(instanceHandle)
          .then(
            ({
              terms: {
                assays: [contractAssay0, contractAssay1],
              },
            }) => {
              // Check whether we sell on contract assay 0 or 1.
              const normal = checkOrder(
                regAssay0,
                regAssay1,
                contractAssay0,
                contractAssay1,
              );
```

Can we close this PR and try something else? I think it's going in the wrong direction.

**Comment by jfparadis** [comment]
@katelynsills Maybe something got lost in translation, but I think I understand what @Chris-Hibbert is trying to do. Here is the need:

The exchange UI needs to know what pairs of assays to enable. In the 0x.org example, there is a drop-down menu at the top of the page, the `MarketsDropdown` that allows the user to select which pair of ERC20 tokens:
https://github.com/0xProject/0x-launch-kit-frontend/blob/development/src/components/erc20/common/markets_dropdown.tsx

In the UI, it shows immediately next to the logo on the top nav:
https://github.com/0xProject/0x-launch-kit-frontend/blob/development/src/components/erc20/common/toolbar_content.tsx#L87

Whether or not Simple Exchange support one or multiple markets is independent to the need to retrieve from the server the configuration of the app to display various context items. 
- This cannot come from the wallet or the lists of offers because both can return an empty list.
- This also cannot be hard-coded to the client to avoid client-server mismatch.

@Chris-Hibbert Did I get this right?

68747470733a2f2f73332e65752d776573742d322e616d617a6f6e6177732e636f6d2f30782d77696b692d696d616765732f65726332302e706e67

**Comment by katelynsills** [comment]
> The exchange UI needs to know what pairs of assays to enable. 

Gotcha. We will probably only have one instance of the exchange running (therefore one pair) for the MVP version. So I think this part is exactly the same as autoswap. Given an instanceHandle, you can get the pair of assays used. 

> Whether or not Simple Exchange support one or multiple markets is independent to the need to retrieve from the server the configuration of the app to display various context items.

Ok, gotcha. The SimpleExchange doesn't support multiple markets currently. Just two assays (one pair of digital assets.) Same as autoswap.

> This cannot come from the wallet or the lists of offers because both can return an empty list.
> This also cannot be hard-coded to the client to avoid client-server mismatch.

Yeah. I think we should handle this in the same exact way as autoswap already solves the problem. If we have access to the registrar, we get access to Zoe and the instanceHandle using the registrar and call `zoe.getInstance(instanceHandle)` which returns a record with one of the keys being "assays".

**Comment by jfparadis** [comment]
> Same as autoswap.

I'm a little confused here. AutoSwap gets the pair of assays from the wallet:
```
wallet -> get list of purses -> user selection -> pair of purses -> create contract 
```
The get purses is happening here, right after the connection is made to the wallet.
https://github.com/Agoric/autoswap-frontend/blob/master/src/contexts/Application.jsx#L54

For SimpleExchange the flow must happen in two steps:
1. App connect to the exchange
```
get market -> pair of assays -> create the UI
```
2. App connect to the wallet
```
wallet -> get list of purses for pair of assays -> user selection -> pair of purses -> create contract
```

The pair of assays never really existed before the user selected the pair of purses. Those are necessary as soon as the app bootstraps in order to: 
- create the UI
- ask the wallet to return only the purses that match those assays

I think are right, the workflow looks the same as AutoSwap, but the pair of assays must be available before the wallet connects, and we've never had that before.

**Comment by Chris-Hibbert** [comment]
So, @jfparadis, for step 1, you say "the pair of assays must be available before the wallet connects". I'm not familiar enough with the start-up flow in the app. What messages can happen early enough to manage that? If it's just visiting the app's web page, then the app's UI ought to be in contact with the app's BE, so it should be able to get the pair of Assays before it has talked with the user or the wallet UI. 

In reading Application.jsx, it appears that `doFetch()` is used to send messages to the wallet UI, and `dispatch{}` is used to talk to the App's backend. Both simpleExchange and myFirstDapp have a terms() method parallel to publicAPI. Can the app access that, or should I add a copy to the publicAPI?

2. It looks like we need a new method on wallet to get a list of applicable purses. The current getPurses() returns a single undifferentiated list of purses. Would a single filtered list of purses be enough, or should it return a structure containing two separate lists for the two Assays? In order to not interfere with the existing methods, I think I'd call it filterPurses(). The only use I can think of now is this one, which wants to provide two Assays. Does it make any sense to accept an arbitrary length list of Assays?

**Comment by jfparadis** [comment]
@Chris-Hibbert, thanks for helping to define this!
1. Here is what I think is the bootstrap sequence in other therms:
- Browser connects to HTTP server and download the UI
- The UI has a configuration file, an address/port that tell it where to find the blockchain/ag-solo/else server
-  The result of the `getMarket()` is use to hydrate the UI and call `getPurses()`

The goal is to keep the assays out of the UI. Assay are serialized by ids, they are very dependent of the state of the registry, and we can't hardcode them in the UI. The specific exchange we are trying to expose must provide these to the UI.

Other comments:
- `doFetch()` and other are just low-level operations.

2. Precisely, but that's totally separate form the `getMarket()`

I looks like we might be better to solve this in a quick meet.

**Pull request closed without merging**
