### PR TITLE
refactor: remove string-based bootstrap argv in favour of data object

### PR DESCRIPTION
**Pull request by michaelfig**
A tiny PR to clean up unnecessary string parsing in the bootstrap vat.

### CODE REVIEW

**Comment by michaelfig** [comment]
@FUDCo apparently there's a flakey test in swingset-runner: https://github.com/Agoric/agoric-sdk/pull/1678/checks?check_run_id=1064886156#step:32:18
Can you PTAL at it?

**Comment by michaelfig** [comment]
> Can you PTAL at it?

This is apparently germane.  I reproduced it once in about 15 tries... there's some race of some kind between the different storages and the on-disk state:

```
UnhandledPromiseRejectionWarning: [Error <Object <[Object: null prototype] {}>>: Bundle bundle-bot not found
  at create (kernel/packages/SwingSet/src/kernel/dynamicVat.js:67:13)
  at recreateVatDynamically (kernel/packages/SwingSet/src/kernel/dynamicVat.js:60:12)
  at Object.start (kernel/packages/SwingSet/src/kernel/kernel.js:842:13)
  at async buildVatController (/Users/michael/agoric/agoric-sdk/packages/SwingSet/src/controller.js:518:27)
  at async main (/Users/michael/agoric/agoric-sdk/packages/swingset-runner/src/main.js:343:22)]
  run encouragmentBot demo with lmdb
```

**Comment by FUDCo** [comment]
> @FUDCo apparently there's a flakey test in swingset-runner: https://github.com/Agoric/agoric-sdk/pull/1678/checks?check_run_id=1064886156#step:32:18
> Can you PTAL at it?

I hit this one myself late this afternoon.  It's a database reentrancy problem triggered by Ava running multiple swingset-runner tests at the same time.  I've already got a fix ready and should have a PR out for it RSN.

**Review by FUDCo — APPROVED** [review]
If you're not taking 'em from the command line, seems fine.  If you are, might be a problem.  But it doesn't look like you are.

**Pull request merged**
