### PR TITLE
fix feeDistributor bootstrap

### LINKED ISSUE #7046: wrong args to makeOfferDestination in setting up reserve, fee distribution
### Discussed in https://github.com/Agoric/agoric-sdk/discussions/6967

<div type='discussions-op-text'>

<sup>Originally posted by **anilhelvaci** February 10, 2023</sup>
## Context
In [The Inter Protocol Whitepaper's](https://inter.trade/static/whitepaper-6106f841c1ed6c564afd2fc3238240a9.pdf) `Section 2.4`, there mentioned a `Reserve Pool`. I assume that `Reserve Pool` is the one in [packages/interProtocol/src/reserve/assetReserve.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/reserve/assetReserve.js) when I'm asking my question. If I'm wrong please point me to the correct `Reserve Pool`.

## Question

I don't quite understand how the distribution of fees collected from `vaultFactory`, `amm` and `stakeFactory` end up in [assetReserve.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/reserve/assetReserve.js). In [econ-behaviors' startRewardDistributer method](https://github.com/Agoric/agoric-sdk/blob/4189c0d0934660f1f399d60ae12db6eb79a282f9/packages/inter-protocol/src/proposals/econ-behaviors.js#L533) there's [this code](https://github.com/Agoric/agoric-sdk/blob/4189c0d0934660f1f399d60ae12db6eb79a282f9/packages/inter-protocol/src/proposals/econ-behaviors.js#L597-L600).  Below is the snippet:

```js
await E(instanceKit.creatorFacet).setDestinations({
    RewardDistributor:
      rewardDistributorDepositFacet &&
      E(instanceKit.creatorFacet).makeDepositFacetDestination(
        rewardDistributorDepositFacet,
      ),
    Reserve: E(instanceKit.creatorFacet).makeOfferDestination(
      'Collateral',
      E.get(reserveKit).publicFacet,
      'makeAddCollateralInvitation',
    ),
  });
```
As far as I can understand here's the flow;

```mermaid
sequenceDiagram
    boot->>+feeDistributer: Set destinations
    Note over boot,feeDistributer: Reward, Reserve
    feeDistributer ->> feeDistributer: update shareConfig
    feeDistributer ->> vaultFacotry/amm/stakeFactory: collectFees
    feeDistributer ->> bank (Reward Pool): pushPayment
    feeDistributer ->> assetReserve (Reserve Pool): pushPayment
```

My questions;
The signature of `makeOfferDestination` is like below;
```js
 /**
     * Create a destination that generates invitations and makes Zoe offers.
     *
     * @param {ERef<ZoeService>} zoe
     * @param {string} keyword
     * @param {unknown} target
     * @param {PropertyKey} makeInvitationMethod
     * @param {unknown[]} [args]
     */
    makeOfferDestination: (
      zoe,
      keyword,
      target,
      makeInvitationMethod,
      args = [],
    ) => {
    // Method body...
    }
``` 

But in `startRewardDistributor`'s ;

```js
Reserve: E(instanceKit.creatorFacet).makeOfferDestination(
      'Collateral',
      E.get(reserveKit).publicFacet,
      'makeAddCollateralInvitation',
```

1. The method is called without the first argument which is `zoe`
2. The keyword is `Collateral`, shouldn't it be `Fee` as the IST is collected under the keyword `Fee` in [collectFees.js](https://github.com/Agoric/agoric-sdk/blob/4189c0d0934660f1f399d60ae12db6eb79a282f9/packages/inter-protocol/src/collectFees.js#L18) like below;
   ```js
    const collectFees = seat => {
      const amount = feeSeat.getAmountAllocated(keyword, feeBrand);
      atomicTransfer(zcf, feeSeat, seat, { [keyword]: amount }, { Fee: amount }); // To keyword is `Fee`

      seat.exit();
      return `paid out ${amount.value}`;
    };
   ```

Am I wrong or is this a bug? @dckc . If I'm wrong, can someone please point me to the correct direction? 

Thanks 🙏 
   </div>

cc @Chris-Hibbert @turadg

### PR DESCRIPTION
**Pull request by dckc**
closes: #7046

## Description

 - fix args to feeDistributor setup
 - route all rewards to the reserve

### Security, Scaling Considerations

none

### Documentation Considerations

@otoole-brendan I trust Inter docs cover this initial fee distribution policy.

### Testing Considerations

I didn't add any tests.

### CODE REVIEW

**Review by Chris-Hibbert — APPROVED** [review]
If it's correct to send everything to the reserve, this does that.

**Comment by mhofman** [comment]
@mergify unqueue

**Comment by mhofman** [comment]
@mergifyio requeue

**Comment by mhofman** [comment]
@mergifyio refresh

**Pull request merged**
