### PR TITLE
remove Data from marshal and all packages that used it

### PR DESCRIPTION
**Pull request by warner**
This completes the "empty objects should be pass-by-copy" transition plan.

refs #2018

### CODE REVIEW

**Review by erights — APPROVED** [review]
LGTM, including all the changes to marshal.

**Comment by warner** [comment]
This currently fails CI in a Zoe unit test when run under XS. We think this is because of a weird XS bug that we're still trying to narrow down (maybe related to https://github.com/Agoric/agoric-sdk/pull/2633). I won't land it while that bug is causing CI to fail, but if we change CI to not have XS failures flunk the overall build (until we get XS working with the full test suite), then I could land it while an XS-specific problem was still happening.

**Comment by warner** [comment]
The XS bug is going to be fun. There are 72 tests in `test-zcf.js`, and it is the 58th test that fails. If I delete the 60th test and beyond, the bug persists. If I then delete the *59th* test (the one immedately following the failure), the bug goes away. The bug is somehow looking into the near future. Very much smells like a GC issue. Also, I can make the bug go away by allocating 800 or more empty objects in an earlier test (allocating 790 or fewer retains the failure).

**Comment by warner** [comment]
Rats, the error persists even after upgrading to the newer XS code drop (#2655) that touched GC and WeakMaps somehow.

Because it provides a somewhat-stable trigger of this error, I'm going to hold off landing this while we continue to investigate.

**Comment by katelynsills** [comment]
> Rats, the error persists even after upgrading to the newer XS code drop (#2655) that touched GC and WeakMaps somehow.

Yup, it does. I was able to confirm this yesterday.

**Comment by warner** [comment]
Huh, well now it passes, both here and locally. I was sure I rebuilt everything the right way, so I don't know what changed. Joy.

I guess I'll land this now and keep my eyes open for any other XS failures.

**Pull request merged**
