### PR TITLE
use Corepack

### PR DESCRIPTION
**Pull request by turadg**
## Description

https://github.com/Agoric/agoric-sdk/pull/6400 added support for Corepack. We couldn't require it because it wasn't available in all the version of Node the SDK supported.

https://github.com/Agoric/agoric-sdk/pull/7293 updated the root package.json to require 16 LTS, but not all the packages.

This updates the rest of the packages to match root.

Most importantly, it removes `.yarn` and `.yarnrc`. Instead we'll use [Node's Corepack](https://nodejs.org/api/corepack.html) to activate the version of Yarn declared in the `packageManager` property. That's done with `corepack enable`.

### Documentation Considerations

How should we alert all devs that they need to run `corepack enable` after updating to master? Should we put it in a build or doctor script?

### Testing Considerations

- [x] test with `corepack enable` and nodenv

### CODE REVIEW

**Comment by michaelfig** [comment]
Is there any way to do a two-stage migration?  Something like:
1. enable corepack support, deprecate direct use of `yarn`
2. remove `yarn` without corepack

**Comment by michaelfig** [comment]
OIC this is the second stage.  In that case, we should first describe our dependence on corepack on Agoric's official docs site.

**Comment by michaelfig** [comment]
The following text from [Node.js 20's Corepack page](https://nodejs.org/api/corepack.html#corepack) makes me wonder if we should be early adopters or just wait for the feature to make it into "Stable":

> Due to its experimental status, Corepack currently needs to be explicitly enabled to have any effect.

**Comment by turadg** [comment]
Yeah I've had second thoughts as well. Closing.

**Pull request closed without merging**
