### PR TITLE
chore: add a manual dapp testing checklist as issue template

### PR DESCRIPTION
**Pull request by katelynsills**
refs: #3962

## Description

This PR adds an issue template that creates a checklist for manual dapp testing. We should update this checklist with our expectations for which dapps are broken and which should be working. 

Directing users and potential hires to broken dapps is a bad experience, so we want to make sure that 1) the list of dapps which should be maintained is common knowledge, and 2) those dapps aren't broken. (Hey, maybe this will mean we allocate resources to automating testing :))

### CODE REVIEW

**Review by warner — APPROVED** [review]
Sounds good.. when should we create a new issue (using this template)? Is it when we make a change that might impact dapp compatibility? Or maybe N days before we're due to cut a release, so we can make sure that compatibility is a blocking requirement for the release process?

If we have a good answer for that, we should either add it to the metadata (maybe `about`?) so it gets displayed in the list of templates (so someone filing an issue can see it before they choose a template), or in the body (so after they've made that choice, they can be reassured that they made the right one).

**Comment by katelynsills** [comment]
> When should we create a new issue (using this template)? Is it when we make a change that might impact dapp compatibility? Or maybe N days before we're due to cut a release, so we can make sure that compatibility is a blocking requirement for the release process?

Here's what I was thinking: For any PR where we think it will break dapps, we use this template to do the manual testing before the PR gets merged. Then, to catch anything that we missed, we can use this template to create an issue every other week. That way we have at least bi-weekly assurance that our users have a good experience. Possibly we can spread the testing load around the engineering team like we've been doing with dependabot. 

The problem with connecting it to releases is that only testnet and devnet users use releases. Right now, any user or potential hire is going to be following the instructions in our documentation, which tell them to use `agoric-sdk` master. So I think connecting it to releases won't make sense until our documentation instructions tell users to use releases.

> If we have a good answer for that, we should either add it to the metadata (maybe `about`?) so it gets displayed in the list of templates (so someone filing an issue can see it before they choose a template), or in the body (so after they've made that choice, they can be reassured that they made the right one).

Let me know if my plan above sounds good to you! (maybe it needs to be socialized in keybase?) If so, I'll add it to the template like you suggest.

**Comment by katelynsills** [comment]
Just talked to Dean in eng_dapps and the decision is: we pursue automated testing for these dapps. In the meantime, we will do manual testing once per week and @samsiegart will drive both the automated testing and the manual testing for this week. 

This means that we have no expectation at the product level that dapps will work at any one moment. However, any bugs will be identified in at most a week, and hopefully fixed soon after.

Remaining management questions:
* Who is doing the manual testing after this week?
* Who responsible for fixing the dapps when testing finds bugs?

**Comment by katelynsills** [comment]
@warner I added instructions to the "about" metadata.

**Pull request merged**
