### PR TITLE
chore: use new -resm logic to handle npm-installed package caches

### PR DESCRIPTION
**Pull request by michaelfig**
This helps eliminate drift between the ESM cache and the actual installed files without sacrificing the performance gains enabled by that cache.

The ESM changes were taken from https://github.com/standard-things/esm/pull/832  When an official release is made (post `esm@3.2.25`), we should upgrade to that instead.

### CODE REVIEW

**Review by kriskowal — APPROVED** [review]
How do we ensure we remember to back this out when we catch the new `esm` version from @jdalton?

**Comment by warner** [comment]
Yeah, same question here. I've added to this problem with my earlier introduction of `patch-package`.

@michaelfig do you think you could whip up a CI script that would check to see if the indicated version is available on NPM and flunk the build if so, with a message saying "please remove the `patch-package` file and also this check"?

**Review by warner — APPROVED** [review]
Other than that issue, this seems good

**Comment by michaelfig** [comment]
> How do we ensure we remember to back this out when we catch the new `esm` version from @jdalton?

I took @warner's advice and created a CI job to fail when we should upgrade and remove the patch.

**Pull request merged**
