### PR TITLE
chore(release): publish agoric-upgrade-12

### PR DESCRIPTION
**Pull request by mhofman**
## Packages that have NEWS.md updates

```diff
--- a/golang/cosmos/CHANGELOG.md
+++ b/golang/cosmos/CHANGELOG.md
@@ -3,6 +3,26 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+## [0.35.0-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/cosmos@0.35.0-u11wf.0...@agoric/cosmos@0.35.0-u12.0) (2023-11-10)
+
+
+### ⚠ BREAKING CHANGES
+
+* **vstorage:** Enforce path validation
+
+### Features
+
+* **cosmos:** Lower `BlockParams.MaxBytes` to 5MB ([84908e5](https://github.com/Agoric/agoric-sdk/commit/84908e5a5a181e3f64da0e298d0105fedb97570a))
+
+### Bug Fixes
+
+* **vibc:** accommodate ibc-go v3 breaking changes ([f582901](https://github.com/Agoric/agoric-sdk/commit/f582901fb3835d95d493c777aac6a63fc3ee4681))
+* **vibc:** put extraneous `CounterpartyChannelID` in `Counterparty` struct ([9469971](https://github.com/Agoric/agoric-sdk/commit/946997192cec0ed6b07fdaa18d8f380f460ab004))
+* **vstorage:** Enforce path validation ([d8db331](https://github.com/Agoric/agoric-sdk/commit/d8db3310fb21a8546388694752889f3563733010)), closes [#8337](https://github.com/Agoric/agoric-sdk/issues/8337)
+* **cosmos:** Update cosmos-sdk with fix for state-sync restore of large payloads ([e04b398](https://github.com/Agoric/agoric-sdk/commit/e04b398bf16d884fa4708c16d4c03b39cc4e0f1b)), closes [#8325](https://github.com/Agoric/agoric-sdk/issues/8325)
+
+
+
 ## [0.35.0-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/cosmos@0.35.0-u11.0...@agoric/cosmos@0.35.0-u11wf.0) (2023-09-23)
 
 **Note:** Version bump only for package @agoric/cosmos
--- a/packages/SwingSet/CHANGELOG.md
+++ b/packages/SwingSet/CHANGELOG.md
@@ -3,6 +3,16 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+### [0.32.3-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/swingset-vat@0.32.3-u11wf.0...@agoric/swingset-vat@0.32.3-u12.0) (2023-11-10)
+
+
+### Features
+
+* **swing-store:** faster import of swing-store ([35aef87](https://github.com/Agoric/agoric-sdk/commit/35aef87ec0f10b7f0cdce462ac0509296e8bd752))
+* **swing-store:** prevent SwingSet usage of imported swing-store ([03f642d](https://github.com/Agoric/agoric-sdk/commit/03f642d39f90ef9465a439723c3a69beef73bd61))
+
+
+
 ### [0.32.3-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/swingset-vat@0.32.3-u11.0...@agoric/swingset-vat@0.32.3-u11wf.0) (2023-09-23)
 
 **Note:** Version bump only for package @agoric/swingset-vat
--- a/packages/cosmic-swingset/CHANGELOG.md
+++ b/packages/cosmic-swingset/CHANGELOG.md
@@ -3,6 +3,15 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+## [0.42.0-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/cosmic-swingset@0.42.0-u11wf.0...@agoric/cosmic-swingset@0.42.0-u12.0) (2023-11-10)
+
+
+### Features
+
+* **cosmic-swingset:** add begin block check and transaction ([#8432](https://github.com/Agoric/agoric-sdk/issues/8432)) ([06302a2](https://github.com/Agoric/agoric-sdk/commit/06302a2d28271e1a962545e2952703af77a28f53))
+
+
+
 ## [0.42.0-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/cosmic-swingset@0.42.0-u11.0...@agoric/cosmic-swingset@0.42.0-u11wf.0) (2023-09-23)
 
 **Note:** Version bump only for package @agoric/cosmic-swingset
--- a/packages/deployment/CHANGELOG.md
+++ b/packages/deployment/CHANGELOG.md
@@ -3,6 +3,21 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+## [4.0.0-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/deployment@4.0.0-u11wf.0...@agoric/deployment@4.0.0-u12.0) (2023-11-10)
+
+
+### Features
+
+* **Docker:** make shell ([b217c44](https://github.com/Agoric/agoric-sdk/commit/b217c440385cc546f288e9b4c4bd266c465f538e))
+* port bash tests to javascript ([90b1a06](https://github.com/Agoric/agoric-sdk/commit/90b1a06cc6dfe1320005d3a17867108c2111a475))
+
+
+### Bug Fixes
+
+* hard code working agoric-3-proposals image ([664f59f](https://github.com/Agoric/agoric-sdk/commit/664f59f698934ce4cb4bf34bc7d3bb2eed1e7ebd))
+
+
+
 ## [4.0.0-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/ssh-node@4.0.0-u11.0...@agoric/deployment@4.0.0-u11wf.0) (2023-09-23)
 
 **Note:** Packaged renamed from @agoric/ssh-node to @agoric/deployment
--- a/packages/eslint-config/CHANGELOG.md
+++ b/packages/eslint-config/CHANGELOG.md
@@ -3,6 +3,15 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+### [0.4.1-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/eslint-config@0.4.1-u11wf.0...@agoric/eslint-config@0.4.1-u12.0) (2023-11-10)
+
+
+### Bug Fixes
+
+* export of eslint-config.cjs ([3f6b83b](https://github.com/Agoric/agoric-sdk/commit/3f6b83b55c320c710aa57c796a6c166ae396fe38))
+
+
+
 ### [0.4.1-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/eslint-config@0.4.0...@agoric/eslint-config@0.4.1-u11wf.0) (2023-09-23)
 
 **Note:** Version bump only for package @agoric/eslint-config
--- a/packages/governance/CHANGELOG.md
+++ b/packages/governance/CHANGELOG.md
@@ -3,6 +3,15 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+### [0.10.4-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/governance@0.10.4-u11wf.0...@agoric/governance@0.10.4-u12.0) (2023-11-10)
+
+
+### Features
+
+* puppetGovernor pass the Issuerkeywordrecord through ([#8351](https://github.com/Agoric/agoric-sdk/issues/8351)) ([90f43ba](https://github.com/Agoric/agoric-sdk/commit/90f43ba8a2430804ceccfd1152cd21fc812242a6)), closes [#8350](https://github.com/Agoric/agoric-sdk/issues/8350)
+
+
+
 ### [0.10.4-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/governance@0.10.4-u11.0...@agoric/governance@0.10.4-u11wf.0) (2023-09-23)
 
 **Note:** Version bump only for package @agoric/governance
--- a/packages/internal/CHANGELOG.md
+++ b/packages/internal/CHANGELOG.md
@@ -3,6 +3,20 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+## [0.4.0-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/internal@0.3.3-u11wf.0...@agoric/internal@0.4.0-u12.0) (2023-11-10)
+
+
+### ⚠ BREAKING CHANGES
+
+* **vstorage:** Enforce path validation
+
+### Bug Fixes
+
+* **internal:** severe override taming for bundle-source ([9486c77](https://github.com/Agoric/agoric-sdk/commit/9486c772ab7daaebad0a19ac85653307ba461065))
+* **vstorage:** Enforce path validation ([d8db331](https://github.com/Agoric/agoric-sdk/commit/d8db3310fb21a8546388694752889f3563733010)), closes [#8337](https://github.com/Agoric/agoric-sdk/issues/8337)
+
+
+
 ### [0.3.3-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/internal@0.3.3-u11.0...@agoric/internal@0.3.3-u11wf.0) (2023-09-23)
 
 
--- a/packages/smart-wallet/CHANGELOG.md
+++ b/packages/smart-wallet/CHANGELOG.md
@@ -3,6 +3,15 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+### [0.5.4-u12.0](https://github.com/Agoric/agoric/compare/@agoric/smart-wallet@0.5.4-u11wf.0...@agoric/smart-wallet@0.5.4-u12.0) (2023-11-10)
+
+
+### Bug Fixes
+
+* **walletFactory:** move upgrading check before baggage is populated ([#8322](https://github.com/Agoric/agoric/issues/8322)) ([330b7a2](https://github.com/Agoric/agoric/commit/330b7a26da9a8eefb95e3e0fd082714fdfad7873))
+
+
+
 ### [0.5.4-u11wf.0](https://github.com/Agoric/agoric/compare/@agoric/smart-wallet@0.5.4-u11.0...@agoric/smart-wallet@0.5.4-u11wf.0) (2023-09-23)
 
 
--- a/packages/solo/CHANGELOG.md
+++ b/packages/solo/CHANGELOG.md
@@ -3,6 +3,16 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+### [0.10.4-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/solo@0.10.4-u11wf.0...@agoric/solo@0.10.4-u12.0) (2023-11-10)
+
+
+### Bug Fixes
+
+* **solo:** correct lookup of wallet-ui ([670fc25](https://github.com/Agoric/agoric-sdk/commit/670fc25f30964c40fc887fac77ebf54bf58c7b8e))
+* **solo:** use alternative endo init ([60a680a](https://github.com/Agoric/agoric-sdk/commit/60a680a2124ee9868ba3b8352a3a5a9f30ce7ab6))
+
+
+
 ### [0.10.4-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/solo@0.10.4-u11.0...@agoric/solo@0.10.4-u11wf.0) (2023-09-23)
 
 **Note:** Version bump only for package @agoric/solo
--- a/packages/swing-store/CHANGELOG.md
+++ b/packages/swing-store/CHANGELOG.md
@@ -3,6 +3,21 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+### [0.9.2-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/swing-store@0.9.2-u11wf.0...@agoric/swing-store@0.9.2-u12.0) (2023-11-10)
+
+
+### Features
+
+* **swing-store:** faster import of swing-store ([35aef87](https://github.com/Agoric/agoric-sdk/commit/35aef87ec0f10b7f0cdce462ac0509296e8bd752))
+* **swing-store:** prevent SwingSet usage of imported swing-store ([03f642d](https://github.com/Agoric/agoric-sdk/commit/03f642d39f90ef9465a439723c3a69beef73bd61))
+
+
+### Bug Fixes
+
+* **swing-store:** ensure crank savepoint is wrapped in transaction ([8d738c6](https://github.com/Agoric/agoric-sdk/commit/8d738c65ed37b9159e94fbcf291ed7fe8478ee5a))
+
+
+
 ### [0.9.2-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/swing-store@0.9.2-u11.0...@agoric/swing-store@0.9.2-u11wf.0) (2023-09-23)
 
 **Note:** Version bump only for package @agoric/swing-store
--- a/packages/wallet/CHANGELOG.md
+++ b/packages/wallet/CHANGELOG.md
@@ -3,6 +3,15 @@
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+### [0.18.4-u12.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/wallet@0.18.4-u11wf.0...@agoric/wallet@0.18.4-u12.0) (2023-11-10)
+
+
+### Bug Fixes
+
+* **wallet:** don't assume node_modules layout ([a17b5cc](https://github.com/Agoric/agoric-sdk/commit/a17b5ccabad92a91de7db4a61f7812b9f696ef71))
+
+
+
 ### [0.18.4-u11wf.0](https://github.com/Agoric/agoric-sdk/compare/@agoric/wallet@0.18.4-u11.0...@agoric/wallet@0.18.4-u11wf.0) (2023-09-23)
 
 **Note:** Version bump only for package @agoric/wallet
```

### CODE REVIEW

**Comment by mhofman** [comment]
Summary of package changes:

 - @agoric/cosmos: 0.35.0-u11wf.0 => 0.35.0-u12.0
 - @agoric/ertp: 0.16.3-u11wf.0 => 0.16.3-u12.0
 - @agoric/swingset-vat: 0.32.3-u11wf.0 => 0.32.3-u12.0
 - agoric: 0.21.2-u11wf.0 => 0.21.2-u12.0
 - @agoric/cache: 0.3.3-u11wf.0 => 0.3.3-u12.0
 - @agoric/casting: 0.4.3-u11wf.0 => 0.4.3-u12.0
 - @agoric/cosmic-swingset: 0.42.0-u11wf.0 => 0.42.0-u12.0
 - @agoric/deploy-script-support: 0.10.4-u11wf.0 => 0.10.4-u12.0
 - @agoric/deployment: 4.0.0-u11wf.0 => 4.0.0-u12.0 (private)
 - @agoric/eslint-config: 0.4.1-u11wf.0 => 0.4.1-u12.0
 - @agoric/governance: 0.10.4-u11wf.0 => 0.10.4-u12.0
 - @agoric/import-manager: 0.3.12-u11wf.0 => 0.3.12-u12.0
 - @agoric/inter-protocol: 0.16.2-u11wf.0 => 0.16.2-u12.0
 - @agoric/internal: 0.3.3-u11wf.0 => 0.4.0-u12.0
 - @agoric/notifier: 0.6.3-u11wf.0 => 0.6.3-u12.0
 - @agoric/pegasus: 0.7.13-u11wf.0 => 0.7.13-u12.0
 - @agoric/same-structure: 0.2.8-u11wf.0 => 0.2.8-u12.0
 - @agoric/sharing-service: 0.2.12-u11wf.0 => 0.2.12-u12.0
 - @agoric/smart-wallet: 0.5.4-u11wf.0 => 0.5.4-u12.0
 - @agoric/solo: 0.10.4-u11wf.0 => 0.10.4-u12.0
 - @agoric/spawner: 0.6.9-u11wf.0 => 0.6.9-u12.0
 - @agoric/store: 0.9.3-u11wf.0 => 0.9.3-u12.0
 - @agoric/swing-store: 0.9.2-u11wf.0 => 0.9.2-u12.0
 - @agoric/swingset-liveslots: 0.10.3-u11wf.0 => 0.10.3-u12.0
 - @agoric/swingset-runner: 0.22.3-u11wf.0 => 0.22.3-u12.0 (private)
 - @agoric/swingset-xsnap-supervisor: 0.10.3-u11wf.0 => 0.10.3-u12.0
 - @agoric/telemetry: 0.6.3-u11wf.0 => 0.6.3-u12.0
 - @agoric/time: 0.3.3-u11wf.0 => 0.3.3-u12.0
 - @agoric/ui-components: 0.3.9-u11wf.0 => 0.3.9-u12.0
 - @agoric/vat-data: 0.5.3-u11wf.0 => 0.5.3-u12.0
 - @agoric/vats: 0.15.2-u11wf.0 => 0.15.2-u12.0
 - @agoric/wallet-connection: 0.1.18-u11wf.0 => 0.1.18-u12.0
 - @agoric/wallet: 0.18.4-u11wf.0 => 0.18.4-u12.0
 - @agoric/web-components: 0.6.4-u11wf.0 => 0.6.4-u12.0
 - @agoric/xsnap: 0.14.3-u11wf.0 => 0.14.3-u12.0
 - @agoric/zoe: 0.26.3-u11wf.0 => 0.26.3-u12.0
 - @agoric/zone: 0.2.3-u11wf.0 => 0.2.3-u12.0
 - @agoric/wallet-backend: 0.14.4-u11wf.0 => 0.14.4-u12.0

**Comment by mhofman** [comment]
Looks like I mistakenly labelled some changes as `chore` and they don't show up in the changelog. In particular the state-sync fix and the `BlockParams.MaxBytes` change. I might manually edit.

**Comment by mhofman** [comment]
[Updated the cosmos changelog](https://github.com/Agoric/agoric-sdk/compare/47a0259a3d214db0a1188c89ad3eb4f264a7fc33..ee5a5fdad9187a6b1b7b26b772b6564c0db3062e), and manually recreated the tags locally.

**Review by warner — APPROVED** [review]
LGTM

**Pull request merged**
