### PR TITLE
Zoe chainmail

### PR DESCRIPTION
**Pull request by DavidBruant**
I've tried to improve the zoe chainmail file

Live pic of me trying to write chainmail syntax:
clueless dog

### CODE REVIEW

**Review by katelynsills — APPROVED** [review]
looks good to me!

**Comment by katelynsills** [comment]
@DavidBruant Have we checked that the file still parses? If not, it's not a big deal if we are rewriting this as typescript manually, but it'd be good to know. 

This PR is a huge improvement, thanks!

**Comment by DavidBruant** [comment]
> Have we checked that the file still parses?

I do not know how to check whether a chainmail file parses succesfully. Is there a tool for this purpose?

**Comment by katelynsills** [comment]
> I do not know how to check whether a chainmail file parses succesfully. Is there a tool for this purpose?

We have a parser (instructions here: https://github.com/Agoric/agoric-sdk/blob/master/CHAINMAIL.md) but I expect it may not parse, even before your changes.

**Comment by DavidBruant** [comment]
Since work is ongoing to add TypeScript check with JSDoc annotations, should we give up on chainmail compilation?

Proposal for squash-merge commit message:

> docs(zoe): make chainmail file up-to-date with the current API

**Comment by erights** [comment]
> Since work is ongoing to add TypeScript check with JSDoc annotations, should we give up on chainmail compilation?

Yes. This should fully replace our current uses of chainmail

**Review by katelynsills — APPROVED** [review]
Looks good to me. Let's get this merged

**Pull request merged**
