### PR TITLE
fix(orchestration): Resolve module import issues

### PR DESCRIPTION
**Pull request by 0xpatrickdev**
refs: #10086

## Description

- add types.js indirection layer to fix ERR_MODULE_NOT_FOUND error.
- maintains public API shape for intra-monorepo and npm installs.

### Security Considerations
n/a

### Scaling Considerations
n/a

### Documentation Considerations
n/a

### Testing Considerations
Includes a test in `packages/builders` that ensures `@agoric/orchestration` exports are reachable from a js file.

### Upgrade Considerations
Library code for NPM Orch release

### CODE REVIEW

**Comment by 0xpatrickdev** [comment]
Manually tested with instructions in linked issue. 
```js
// test-orchestration-import.js
import * as orch from '@agoric/orchestration';

console.log(orch);
```
```sh
node --experimental-specifier-resolution=node test-orchestration.js
```


No longer seeing:
```log
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/0xpatrick/repos/agoric-sdk/packages/orchestration/src/types.js' imported from /Users/0xpatrick/repos/agoric-sdk/packages/orchestration/index.js
```

However, I am seeing:
```log
Error: Cannot initialize @endo/errors, missing globalThis.assert, import 'ses' before '@endo/errors'
    at file:///Users/0xpatrick/repos/agoric-sdk/node_modules/@endo/errors/index.js:19:9
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)
 ```
Unclear if this is something to be concerned with, or expected since the test file does not import ses. I am thinking the latter.

**Review by mhofman — CHANGES_REQUESTED** [review]
I don't think this will work as there is already a `src/types.ts` which would want to override the `src` files added here when compiled.

I believe that what I suggested in https://github.com/Agoric/agoric-sdk/issues/10086#issuecomment-2350310443 is the following:
- `orchestration/src/types.ts` kept as-is
- adding a `orchestration/types.d.ts` that `export * from './src/types.ts';` and an "empty" `orchestration/types.js` (must contain `export {}` to remain an ES module)
- Modify `orchestration/index.js` to `export * from './types.js';` (instead of `./src/types.js`)

> closes: https://github.com/Agoric/agoric-sdk/issues/10073

This looks like the wrong issue referenced here

**Comment by mhofman** [comment]
I would also like to see one of the repro from the original issue added as test since we don't seem to have any integration test that catches this issue currently.

**Comment by 0xpatrickdev** [comment]
Apologies for the oversights in the first iteration. 

> I would also like to see one of the repro from the original issue added as test since we don't seem to have any integration test that catches this issue currently.

I am not sure the best place to include this - I've added it to `packages/builders` for now. The test fails with `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/../agoric-sdk/packages/orchestration/src/types.js' imported from /Users/../agoric-sdk/packages/orchestration/index.js` without the changes in the prior commit.

I suspect we might want another test that ensures the types are exported. I've adjusted this to `refs` instead of `closes` since I'll be out for the rest of the week, and can tackle that in a follow up PR. Merging something here seems it'll help unblock `dapp-orchestration-basics` testing.

**Review by mhofman — APPROVED** [review]

**Pull request merged**
