### PR TITLE
[Zoe] Remove: `cancelObj` in favor of `completeObj` 

### PR DESCRIPTION
**Pull request by developerfred**
#1008

### CODE REVIEW

**Comment by katelynsills** [comment]
Hey @developerfred, this is awesome!! Welcome to the Agoric family! 🎉

This particular change, we will need after #1003 lands in Zoe 0.6.0. We will need to have `cancelObj` and `completeObj` both present for a least a week or so for backwards compatibility. But after that, it'd be great to remove `cancelObj`. Would you be ok with changing this PR so that builds on #1003 (soon to be merged into master)? That way we can use your PR out of the box when we want to remove `cancelObj`. 

Thanks so much for your help! Is there anything you're interested in working on? Feel free to join us in Keybase (agoric.support#general) to meet the rest of the team.

**Comment by developerfred** [comment]
@katelynsills of course!

**Comment by katelynsills** [comment]
Hi @developerfred, do you mind rebasing on master now that Zoe v0.6.0 has been merged?

**Comment by developerfred** [comment]
hi @katelynsills done!

**Comment by katelynsills** [comment]
Updated in https://github.com/Agoric/agoric-sdk/pull/1236. Thank you so much for the contribution @developerfred. Hope to work with you again!

**Pull request closed without merging**
