### PR TITLE
refactor(xsnap): Externalize netstring IO dependency

### LINKED ISSUE #2970: Refactor xsnap to use `@endo/netstring` package
## What is the Problem Being Solved?

In creating a public package for `netstring`, there is a temporary duplication of code between `xsnap` and that package that can be eliminated by taking on a dependency.

https://github.com/endojs/endo/pull/690

### PR DESCRIPTION
**Pull request by kriskowal**
closes: #2970

## Description

This change completes the work begun with https://github.com/endojs/endo/pull/690, to move the netstring IO library to the Endo repository as a general purpose package with multiple possible applications.  The netstring library and tests have been removed from xsnap and a dependency has been introduced instead.

### Security Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

Existing tests should be sufficient to cover usage of netstring. The tests were moved as well.

### CODE REVIEW

**Review by dckc — APPROVED** [review]
this is going to cost me a bit of rebasing, but I suppose it's The Right Thing...

**Comment by kriskowal** [comment]
@dckc Will there be a better time to reprise this PR? I do not mind taking on the rebasery.

**Comment by dckc** [comment]
> Will there be a better time ...

not sufficiently better to add more coordination costs. Onward.

**Comment by kriskowal** [comment]
Lint will not pass without a netstring patch https://github.com/endojs/endo/pull/700

It’s _concerning_ that TypeScript surfaces a lint error in a dependee but not in itself.

**Comment by dckc** [comment]
@kriskowal while you're in the `xsnap` package neighborhood, how about finishing this off? LMK if you want / need help.

**Comment by kriskowal** [comment]
Good idea!

**Pull request merged**
