### PR TITLE
fix: update to new style taming options

### PR DESCRIPTION
**Pull request by erights**

### CODE REVIEW

**Comment by kriskowal** [comment]
Thanks, @erights. I see this. I recognize that this is a draft because it is dependent upon the next SES release, probably numbered v0.8.0 planned to land next week.

**Comment by erights** [comment]
I just changed from Draft to Ready to Review. But it won't pass or be a candidate for merging until agoric-sdk upgrades its ses dependency to 0.8.0

**Comment by warner** [comment]
I'll take care of this as part of the new-SES work. All of the files changed in this PR are deleted in that branch, and there's a new `@agoric/install-ses` package which is the one and only place that does `lockdown()`.

**Comment by erights** [comment]
In light of @warner 's comment, closing as no longer relevant

**Pull request closed without merging**
