### PR TITLE
7246 fix vaults list

### LINKED ISSUE #7246: agops vaults list does not show open vaults
## Describe the bug
running `yarn run agops vaults list  --from gov1 --keyring-backend=test`  does not yield a list of open vaults, despite the UI showing one open vault for that address.

## To Reproduce
1. Open a vault in gov1 in ollinet
2. run `yarn run agops vaults list  --from gov1 --keyring-backend=test` in the `agoric-sdk` directory
3. No vaults are shown

## Expected behavior
Vaults to be returned in the CLI

## Platform Environment
 - what OS are you using? what version of Node.js?

v16.19.1, macOS

 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
7989b8857a728c7b7b937077757520f0cadeebde

### PR DESCRIPTION
**Pull request by turadg**
closes: #7246

## Description

Fixes getting stale `vaults list` data by reading the wrong end of the array at the latest block height.

Also refactors rpcUtils to DRY out vstorage deserialization to avoid such errors in the future.

Stacked on https://github.com/Agoric/agoric-sdk/pull/7132

### CODE REVIEW

**Review by dckc — APPROVED** [review]
Presuming rebase as appropriate...

**Comment by mhofman** [comment]
@mergifyio requeue

**Comment by mhofman** [comment]
@mergifyio requeue

**Comment by mhofman** [comment]
@mergifyio refresh

**Pull request merged**
