### PR TITLE
chore(swingset): more misc-tools updates

### PR DESCRIPTION
**Pull request by warner**
This refactors timestamp correlation into a library, handles 'console'
events correctly (which are not syscalls but still insert timestamps
into the metering results), and adds a generic pair-deltas.py for
statistical measurements of time between two arbitrary event types.

### CODE REVIEW

**Comment by warner** [comment]
Another rubber-stamp for you :)

**Comment by warner** [comment]
I have some more tools to include, hold off on review for a minute

**Comment by warner** [comment]
ok ready now

**Review by dckc — APPROVED** [review]
thanks for sharing! yes, let's archive these with the rest.

**Pull request merged**
