### PR TITLE
fix: reject symbols and unenumerated properties as intended

### PR DESCRIPTION
**Pull request by warner**
(This PR targets, and builds upon, the 2018-add-tests branch.)

This changes marshal.js to reject symbol-named and unenumerated properties, as I believe was originally intended.

It carves out exceptions for `Symbol.toStringTag` and a non-enumerable `toString`, because `Remotable()` adds those to the prototype of the newly-generated object, and that prototype is subject to the same requirements as pass-by-reference objects in general. I'm not sure why it does it this way, so perhaps we should not carve out these exceptions, and instead change `Remoteable()` somehow. @erights and @michaelfig I'm especially interested in your opinion on this question.

This is in the context of #2018 (handle empty objects better), but so far this is all just prep work. This should not change any behavior observed by sensible user-level code (where "sensible" means "not fooling around with Symbols or `enumerable: false`).

@warner and @erights agreed to reassign this to @erights and to add @warner as a reviewer. However, github doesn't let us add @warner as a reviewer since he originally filed the PR. So noting here that @warner is de facto reviewer.

### CODE REVIEW

**Comment by warner** [comment]
Based upon the understanding achieved in https://github.com/Agoric/agoric-sdk/issues/2018#issuecomment-773627059 , I'll change this to *not* tolerate `Symbol.toStringTag` or `toString`, as we won't be subjecting objects with these to `mustPassByReference`. Instead, at this stage, I'll change liveslots to use `passStyleOf()` instead of `mustPassByReference`, as long as that performs all of the early checks that it needs to (which I think will actually happen during the call to `Remotable`).

**Comment by warner** [comment]
Huh, ok, that fails an awful lot of tests, with a failure mode like:

```
  TypeError {
    message: 'Remotables must not have symbol-named properties: Symbol(Symbol.toStringTag)',
  }

  › assertCanBeRemotable (/bundled-source/packages/marshal/src/marshal.js:260:11)
  › mustPassByRemote (/bundled-source/packages/marshal/src/marshal.js:291:5)
  › mustPassByRemote (/bundled-source/packages/marshal/src/marshal.js:297:5)
  › Object.passStyleOf (/bundled-source/packages/marshal/src/marshal.js:385:9)
  › mustBeSameStructureInternal (/bundled-source/packages/same-structure/src/sameStructure.js:186:29)
  › mustBeSameStructure (/bundled-source/packages/same-structure/src/sameStructure.js:255:3)
  › Object.mustBeComparable (/bundled-source/packages/same-structure/src/sameStructure.js:266:3)
  › Object.makeAmountMath (/bundled-source/packages/ERTP/src/amountMath.js:79:17)
  › initIssuer (/bundled-source/packages/zoe/src/issuerTable.js:66:39)
  › async Object.executeContract (/bundled-source/packages/zoe/src/contractFacet/contractFacet.js:93:27)
```

I'm guessing that my "no-symbols" check means `Remotable` no longer gets along with `sameStructure`.

Ok, so I like these tests, but maybe I'm applying them too early. I'm going to rewrite `Remotable` as described in https://github.com/Agoric/agoric-sdk/issues/2018#issuecomment-773627059 first, and once we're no longer inserting a prototype with `toStringTag`, I'll bring these tests in on top of that.

**Comment by warner** [comment]
`cd packages/zoe && yarn test test/unitTests/contracts/test-autoswap.js` is one of the tests that fail.

**Comment by erights** [comment]
@warner and @erights agreed to reassign this to @erights and to add @warner as a reviewer. However, github doesn't let us add @warner as a reviewer since he originally filed the PR. So noting here that @warner is de facto reviewer.

**Comment by erights** [comment]
Can I close this in favor of #2306 ? That one is ready for review as a substitute for this, so moving all my reviewers there.

**Comment by warner** [comment]
Yep, #2306 subsumes this one. The test cases are slightly different (the specific error raised is different), but I believe they exercise the same things.

**Pull request closed without merging**
