### PR TITLE
Allow vats under SwingSet to unwrap their promises

### LINKED ISSUE #682: have swingset import/use make-promise
> This looks good. I think there was some previous discussion about reusing the package @agoric/make-promise. Was there a reason not to do that? I can't remember

Oh!  I didn't remember about `@agoric/make-promise`.  @warner, can we introduce it as a SwingSet dependency?

_Originally posted by @michaelfig in https://github.com/Agoric/agoric-sdk/pull/674#issuecomment-598600773_

### PR DESCRIPTION
**Pull request by michaelfig**
Refs #74

Closes #682

Use `@agoric/make-promise` instead of the builtin `makePromise.js` that doesn't properly unwrap.

### CODE REVIEW

**Review by warner — APPROVED** [review]
Sounds ok to me. I'll defer to @erights about whether `unwrap` is ocap-safe, but I don't think I've heard him object.

**Review by katelynsills — APPROVED** [review]
This looks good. I think there was some previous discussion about reusing the package @agoric/make-promise. Was there a reason not to do that? I can't remember

**Comment by michaelfig** [comment]
> This looks good. I think there was some previous discussion about reusing the package @agoric/make-promise. Was there a reason not to do that? I can't remember

Oh!  I didn't remember about `@agoric/make-promise`.  @warner, can we introduce it as a SwingSet dependency?

**Comment by warner** [comment]
yep, just opened an issue

**Comment by DavidBruant** [comment]
The same fix was recently implemented in https://github.com/Agoric/agoric-sdk/pull/623/files#diff-f63ab4d221058b2338f0582969e18090

> Oh! I didn't remember about @agoric/make-promise. @warner, can we introduce it as a SwingSet dependency?

+1

**Comment by warner** [comment]
Huh, ok github's "open related issue" didn't do what I expected. Landing this (#674) PR will *not* resolve the new (#682) bug.. we need to change SwingSet to depend on make-promise (and use it internally, in lieu of it's own copy) to resolve #682.

Did github edit the top comment of this PR when I used the "open related issue" button?

I think we should edit the top comment to remove the claim that it closes the new ticket.

**Comment by DavidBruant** [comment]
> Did github edit the top comment of this PR when I used the "open related issue" button?

no, i think mfig did (3 hours ago)

image

**Comment by michaelfig** [comment]
Yep, was in the midst of pushing new state and updated the issue in the wrong order.

**Comment by warner** [comment]
I edited the comment to remove the magic bug-closing words

**Comment by michaelfig** [comment]
> I edited the comment to remove the magic bug-closing words

I put back the bug-closing words since that's now what this PR does. :wink:

I should not have updated it preemptively.  Too many balls in the air.

**Review by warner — APPROVED** [review]
looks good, and yeah that closes the other ticket now

**Pull request merged**
