### PR TITLE
chore: Evict promise-kit

### PR DESCRIPTION
**Pull request by kriskowal**
This change removes the copy of promise-kit at rest in Agoric SDK and replaces it universally with the version from the Endo repository through its published artifact in npm.

- chore: Remove promise-kit
- refactor: git grep '@agoric/promise-kit' | cut -d: -f1 | xargs sed -i '' 's|@agoric/promise-kit|@endo/promise-kit|g'
- chore: Sync Endo versions
- chore: Remove promise-kit workspace
- chore: Update yarn.lock

refs: https://github.com/endojs/endo/issues/506

### CODE REVIEW

**Comment by michaelfig** [comment]
Ah, failing tests.  Please ping me again when they pass.

**Comment by kriskowal** [comment]
> Ah, failing tests. Please ping me again when they pass.

Tests are green now.

**Review by michaelfig — APPROVED** [review]
I reviewed it.  Every last line. :)

**Comment by kriskowal** [comment]
> I reviewed it. Every last line. :)

Thank you. Sed only makes half of the work go by fast :(

**Pull request merged**
