### PR TITLE
refactor(ertp): Rename identity to additiveIdentity

### LINKED ISSUE #3587: ERTP: rename `identity` to `additiveIdentity`
0 is the additive identity. 1 is the multiplicative identity. So, when we reference 0 as the identity element, we really mean additive. We should rename so it isn't confusing.

### PR DESCRIPTION
**Pull request by kriskowal**
Fixes #3587

This is an exceedingly, almost inappropriately pedantic narrowing of the meaning of identity to specifically additive identity, as distinguished from multiplicative identity.

This is stacked on #3592

### CODE REVIEW

**Comment by erights** [comment]
"empty"?

**Comment by kriskowal** [comment]
> "empty"?

I like “empty”.

**Comment by katelynsills** [comment]
> > "empty"?
> 
> I like “empty”.

Empty works for me!

**Comment by katelynsills** [comment]
@kriskowal let me know if I can help with changing `identity` to `empty`. Otherwise, I'll come back to this PR after we make that change. Also, can we change the base of this PR? I think Github doesn't realize it's stacked so there's a whole bunch of other changes as well. I expect as we merge in other PRs that will fix itself.

**Comment by kriskowal** [comment]
Fixed the base, renamed empty.

**Review by katelynsills — APPROVED** [review]
Awesome! Thanks so much!

**Pull request merged**
