### PR TITLE
agoric-upgrade-13

### PR DESCRIPTION
**Pull request by mhofman**
refs: #8578

## Description

This prepares the `dev-upgrade-13` branch for the next chain software upgrade, `agoric-upgrade-13`. The branch is based on `release-mainnet1B` after `agoric-upgrade-12`. This PR is the equivalent of #8587 but for the the `agoric-upgrade-13` release.

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

Docker upgrade-test Readme updated with the same changes as #8587

### Testing Considerations

Docker upgrade tests coverage should be sufficient

### Upgrade Considerations

This sets up the upgrade tests for the next chain software upgrade. Because of the different image naming, cherry-picking from master may require manual conflict resolution.

### CODE REVIEW

**Review by turadg — APPROVED** [review]
LGTM. Though you may want to wait for https://github.com/Agoric/agoric-sdk/pull/8587 to land so you can re-use the actual commits to master

**Comment by mhofman** [comment]
> LGTM. Though you may want to wait for #8587 to land so you can re-use the actual commits to master

The commits are slightly different. The plan is to have master and the release branch diverge here. However I'll wait to update the base branch first.

**Comment by turadg** [comment]
> The plan is to have master and the release branch diverge here

I presumed you would not want the documentation to diverge

**Comment by mhofman** [comment]
> I presumed you would not want the documentation to diverge

Ah yeah that commit is the same

**Pull request merged**
