### PR TITLE
refactor(inter-protocol): jessie-check where easy

### PR DESCRIPTION
**Pull request by erights**
Adds @jessie-check directives to inter-protocol src/**/*.js files when doing so has zero problems. 

See 
https://github.com/Agoric/agoric-sdk/pull/3876
https://github.com/Agoric/agoric-sdk/pull/5497
https://github.com/Agoric/agoric-sdk/pull/7481
https://github.com/Agoric/agoric-sdk/pull/7487

### CODE REVIEW

**Review by dckc — COMMENTED** [review]
This looks good except...

> Staged on #7481

I'd rather not gate this on changes to swingset etc.

**Review by turadg — APPROVED** [review]
> I'd rather not gate this on changes to swingset etc.

IMO the changes here are fine insofar as they pass CI. Since it can't merge without that I'll approve.

I don't know whether #7481 should get in before vaults release but these checks are (slightly) useful for inter protocol confidence.

**Comment by erights** [comment]
turns out that this PR and https://github.com/Agoric/agoric-sdk/pull/7481 happened to be disjoint, so proceeding on this one independently.

**Comment by erights** [comment]
> This looks good except...
> 
> > Staged on #7481
> 
> I'd rather not gate this on changes to swingset etc.

Unstaged

**Pull request merged**
