### PR TITLE
chore(agoric-cli): Document external consumption of gettingStartedWorkflowTest

### PR DESCRIPTION
**Pull request by gibson042**
## Description
Without this, packages/agoric-cli/integration-tests/workflow.test.js is an essentially empty wrapper.

### Security Considerations
n/a

### Scaling Considerations
n/a

### Documentation Considerations
n/a

### Testing Considerations
n/a

### Upgrade Considerations
n/a

### CODE REVIEW

**Review by turadg — DISMISSED** [review]
Files in `tools` are the public API of the package. 

https://github.com/search?q=org%3AAgoric+getting-started.js&type=code shows it's used in other repos. E.g. https://github.com/Agoric/dapp-fungible-faucet/blob/b1ce19d6f9fbbdb69875b0b3554a827fccddd6c8/integration-test/test-getting-started-workflow.mjs#L4

I only see it used in archived repositories so I'm not opposed to breaking it, but it should be marked as a BREAKING CHANGE.

**Comment by gibson042** [comment]
Fair enough; done.

**Review by michaelfig — COMMENTED** [review]
I did a quick search, and we have some (older) dapps that do:

```js
import { gettingStartedWorkflowTest } from 'agoric/tools/getting-started.js';
```

notably,

- `Agoric/dapp-fungible-faucet`
- `Agoric/dapp-nft-drop`
- `agoric-labs/interaccounts`
- Calypso

Would it be better to document that dependency at the top of `getting-started.js`  (with a reminder that `agoric-cli/tools` is part of the package's public API) and `workflow.test.js` instead?  Chesterton's fence and all?

**Review by michaelfig — APPROVED** [review]
Ah, I saw @turadg got to the search faster than I did.  I'm okay with whichever direction you go.

**Comment by gibson042** [comment]
This seems like the kind of thing that could blow up, so I've replaced the breaking change with some documentation. Thanks @turadg @michaelfig!

**Pull request merged**
