### PR TITLE
Mostly "lint-fix"es. Remove some jsx and react dependencies

### PR DESCRIPTION
**Pull request by erights**
Removed remaining jsx patterns in all package.json files except the one in agoric-cli
Removed eslint-plugin-react dependency from root package.json
Changed remaining 'airbnb' eslint dependencies to 'airbnb-base'

lint-fix everything. I don't see anything but whitespace changes but may have missed something.
Tests still pass.

### CODE REVIEW

**Comment by katelynsills** [comment]
Hi Mark, was this in response to https://github.com/Agoric/agoric-sdk/issues/111 ? I think Brian told me that he did intend for us to include the two frontend repos in this monorepo, so that would mean that we would want to keep the react-related packages as far as I know.

**Comment by erights** [comment]
> Hi Mark, was this in response to #111 ?

No. Mostly it is to get more of our sources to be eslint clean, to make them easier to read. Once https://github.com/Agoric/agoric-sdk/issues/367 is fixed, then we'll be able to keep things lint clean more automatically. Notice the react complaints in the first message in that issue that disappear in the second one.

**Comment by katelynsills** [comment]
Got it. Is there a reason that we would remove 'airbnb' and 'eslint-plugin-react' if we intend to include the frontend repos that do use react?

**Comment by erights** [comment]
> Got it. Is there a reason that we would remove 'airbnb' and 'eslint-plugin-react' if we intend to include the frontend repos that do use react?

Dunno. My real concern is #367 so that we can automate lint cleaning and maintain our sources in a lint-clean state.

**Review by warner — APPROVED** [review]
looks good to me. thanks for avoiding semantic changes, that helps the review process

It looks like this needs to be rebased to current trunk, github reports there are some conflicts.

+1 after rebasing

**Comment by warner** [comment]
I've got a rebased and un-bit-rotted version of this which I'll force-push to replace the `more-prettier` branch. We should give it another scan. I may or may not land it right away, I think I might like to see #410 landed first.. will check to see how much they overlap.

**Comment by warner** [comment]
I'm going to land this in a moment.. we can bring the react plugins back in as we get all our packages fully lint-clean.

**Pull request merged**
