### PR TITLE
Optimise monorepo builds

### PR DESCRIPTION
**Pull request by michaelfig**
Begin distinguishing `yarn build` that is used just to create a CJS or UMD bundle, and builds that are necessary for other features.  Avoid building the Golang/node-gyp parts of `cosmic-swingset` unless actually running scenario2 or doing a Docker build.

Export and depend on ESM packages directly rather than their Rollup esm bundle.

Refs #267

### CODE REVIEW

**Review by jfparadis — COMMENTED** [review]
Looks good. While at it might want to fix all `package.json`. 
- ERTP/package.json has incorrect "main"
- others?
Also maybe todo?
- Marshall and Zoe should probably have a src directory instead of putting source on root

**Comment by michaelfig** [comment]
> * ERTP/package.json has incorrect "main"
> * Marshal and Zoe should probably have a src directory instead of putting source on root

@katelynsills, @erights do you have thoughts about these?

**Comment by katelynsills** [comment]
>  * ERTP/package.json has incorrect "main"

Good point. I think once we rework ERTP such that it is much simpler, it will be `mint.js`. We could switch to that now, as well.
>  * Marshal and Zoe should probably have a src directory instead of putting source on root

What are the benefits of a `src` directory? I could see it being easy to mention in "files" like: "src/*.js". Any other benefits?

**Comment by jfparadis** [comment]
> What are the benefits of a src directory? I could see it being easy to mention in "files" like: "src/*.js". Any other benefits?


- To follow the same pattern that see test in "test" directory
- For consistency across packages in the monorepo

**Comment by katelynsills** [comment]
Ok, sure. I'm ok doing it for consistency

**Review by warner — APPROVED** [review]
That sounds pretty good to me

**Comment by michaelfig** [comment]
> * ERTP/package.json has incorrect "main"

I've fixed this and the others I found.

> * Marshall and Zoe should probably have a src directory instead of putting source on root

I'll defer this to a different PR, but I agree, this is a consistency issue that should be addressed.

**Comment by katelynsills** [comment]
> > * Marshall and Zoe should probably have a src directory instead of putting source on root

> I'll defer this to a different PR, but I agree, this is a consistency issue that should be addressed.

I added issues for moving the files in ERTP and Zoe to src/, so that's on my radar for the near future.

**Pull request merged**
