### PR TITLE
upgrade-test: deploy KREAd contract

### LINKED ISSUE #8329: deployment upgrade test of Kread
## What is the Problem Being Solved?

We need to test our code against current and future states of Mainnet. https://github.com/Kryha/KREAd/ is destined for Mainnet so we need a test of in the upgrade layers.

## Description of the Design

Add a test like `11wf` for the KRead core proposal

## Upgrade Considerations

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/8228
```

### PR DESCRIPTION
**Pull request by dckc**
closes: #8329
refs: #XXXX

various bits still todo:

 - ~backport to upgrade11 branch? (that is: start over)~
 - [x] integrate governance #8228
     - [x] sync bundle id using `agoric run`
 - [x] repo connection: have someone reproduce my results (@turadg)
 - ~repo connection: teach github actions to do it?~ (eventually: https://github.com/Agoric/agoric-sdk/issues/8376 ) 
 - [x] sync royalty / platform fee address
 - [x] make it noop when there's no MN2 proposal to test (so that it's safe in master, and can be awoken for partner tests)

### CODE REVIEW

**Comment by dckc** [comment]
Integrating governance looks like porting the `kread-committee` and `start-kread` targets from the Makefile in https://github.com/Kryha/KREAd/pull/3

https://github.com/agoric-labs/KREAd/blob/09bf292cc4a92b6a3d015a87c159b7f4db94894e/agoric/Makefile#L43-L61

**Comment by dckc** [comment]
@turadg , @Chris-Hibbert , It's not completely working (TODO: provision wallets), but I integrated the governance and `agoric run` style stuff:

[mn2-start.test.js](https://github.com/Agoric/agoric-sdk/blob/dc-mn2-test/packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-12/mn2-start.test.js) has a `@file` comment explaining how it's supposed to work.
currently: c5964fe

it depends on https://github.com/agoric-labs/KREAd/pull/1

**Comment by dckc** [comment]
I wonder how much git history clean-up is worthwhile here...

**Comment by turadg** [comment]
> I wonder how much git history clean-up is worthwhile here...

I could see this going into one squash once the changes are cleaned up. I think we want to:
- drop the NO_BUILD thing since it doesn't work, and fix that separately
- have the agops update happen in a COPY for the layer that needs it (can copy from master now that it's in there)
- clean up superfluous docs changes (like newlines)

**Comment by Chris-Hibbert** [comment]
> I wonder how much git history clean-up is worthwhile here...

Maybe this is obvious, but with 46 commits on 29 files, I only see two plausible choices: (1) squash the whole thing, or (2) if there are two or three main features, then all the changes could be split into a few commits.

**Comment by dckc** [comment]
I reduced the 46 commits to 14 without changing any bytes in the results (351eb2a vs. 81201cc). 

> I think we want to:
>
>  - drop the NO_BUILD thing since it doesn't work, and fix that separately

For now, I moved it last

2023-09-22 18:20 81201cc56 feat: agd NO_BUILD option

> have the agops update happen in a COPY for the layer that needs it (can copy from master now that it's in there)

I'm not sure I understand that; might need help.

I moved this change to its own commit:

2023-10-05 21:02 14ab8558a @@@ agops unversioned???

> clean up superfluous docs changes (like newlines)

This change talks about tmux, but it's a bunch of README tweaks. I'm not sure if that's a result of me separating it from the actual tmux change or something...

2023-09-25 14:54 76116e2c1 test: remove tmux from upgrade-tests

**Comment by turadg** [comment]
> 2023-09-22 18:20 https://github.com/Agoric/agoric-sdk/commit/81201cc566f6e1ab7a6cb9a33c7150780997a03e feat: agd NO_BUILD option

I've never seen it work. Does it work for you? Adding a broken option does more harm than good. 

>> have the agops update happen in a COPY for the layer that needs it (can copy from master now that it's in there)
> I'm not sure I understand that; might need help.

The README has a section, `# Patch agoric-cli`. Instead the Dockerfile should take care of that.

Happy to help tho

> 2023-10-05 21:02 https://github.com/Agoric/agoric-sdk/commit/14ab8558a0aa5e4b890b9140514c39633a9e68a5 @@@ agops unversioned???

That commit should just be dropped. "docker" was just for the version that lived only in Docker. But now it comes from agoric-cli. (Where it's `--version` is "unversioned"; if you propose changing that we could but it's far from the scope of this PR)

> 2023-09-25 14:54 https://github.com/Agoric/agoric-sdk/commit/76116e2c1cce42b8d5df673ff373c51325b87ee2 test: remove tmux from upgrade-tests

Should be dropped. The tmux changes made it into master separately. https://github.com/Agoric/agoric-sdk/pull/8393

**Comment by dckc** [comment]
obsolete in favor of https://github.com/Agoric/agoric-3-proposals/tree/main/proposals/53%3Akread-start `24a16f3`

**Pull request closed without merging**
