### PR TITLE
Add getOfferDescriptions() to allow the App to request offers

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
This approach has the wallet providing all the details so the exchange
doesn't need to request further details from the contract.

### CODE REVIEW

**Comment by Chris-Hibbert** [comment]
The meat of this is the addition of `getOfferDescriptions()`. There are also some clean-ups to adapt to two assays for simple exchange (autoswap used three.)

**Review by katelynsills — APPROVED** [review]
Looks good to me!

**Comment by Chris-Hibbert** [comment]
@jfparadis 

In response to https://github.com/Agoric/agoric-sdk/issues/612, is this what you were looking for? @katelynsills  explained that the UI framework wants objects to have ids in order to display them in lists. I'm not expecting descriptions to be saved or lists from different sources to be mixed together, so giving them ephemeral IDs ought to be enough.

**Comment by Chris-Hibbert** [comment]
Having looked at @jfparadis's issue on [sorting and UUIDs](https://github.com/Agoric/agoric-sdk/issues/612), I've changed this to use the date on the records as the ID. It is already being used between the wallet frontend and backend to identify particular orders when creating, accepting and declining them. If that should change to something less predicable and informative, then it has to be changed across the wallet already. The index wasn't adding anything extra.

**Pull request merged**
