### PR TITLE
WIP: experiment consolidation of packages

### PR DESCRIPTION
**Pull request by erights**
An experiment in a less-fine-grain division into packages.

Currently we have a lot of packages that only have one source file in them. I find more natural to group tightly related files together into a package. Here, 
   * I move weak-map.js into the store package
   * I move same_structure.js into the marshal package

What do y'all think of this structure? Do you find it more or less natural than the current finer-grain-structure? Should we do more of this?

### CODE REVIEW

**Comment by FUDCo** [comment]
In general I dislike having a bunch of fine grained packages, simply because the module mechanism makes that a bit clunky.  I like grouping related things together.  On the other hand, a good heuristic for packaging is to group together things that will be used together.  In that sense putting `sameStructure` into `marshal` seems reasonable, whereas grouping `store` and `weakStore` seems a bit less so.

Observing my own practice, as I've been working the past couple of days on the kernel persistence machinery, I've ended up putting things in separate packages because each package represents a different storage medium and these packages are organized to be alternatives to each other, which I suppose is the extreme of things that are not going to be used together.

**Comment by jfparadis** [comment]
Creating packages in a monorepo is like dividing a book in chapters. It's about meta organization. Although the total count of packages and the complexity of each one can become a criteria to decide between consolidation and separation, several other factors are at play.

> Observing my own practice, as I've been working the past couple of days on the kernel persistence machinery, I've ended up putting things in separate packages because each package represents a different storage medium and these packages are organized to be alternatives to each other, which I suppose is the extreme of things that are not going to be used together.

In SES, I also created more packages than in the original source to better separate the concerns (and apply SOLID in general). In my mind, a package encapsulates a well-defined role. A package helps you think about a problem, put it aside once it's resolved, and only use the result of that thinking. When a package is completed, and that includes its tests, then it doesn't have to be reopened as the rest of the project evolves.

The same can be said of functions and modules... so what else?

Packages also allow you to separate the tests, and I found this to be an important criteria in SES. For example when I added test262 to some packages, it became clear that taming for Date() has nothing to do with Error(). Each package has hundred of tests running against it. If all taming was done in one package, then there would more retest or republish when something unrelated evolves. 

Isolating the taming for Error() in one package played well: we are able to replace it with a new approach and a proposal to tame Error(). In the overall architecture of the project, then taming of error points to a project and can remain unspecified.

What is the industry doing?

- Babel has 138 packages, and joking aside, they form a very nice structure of plugins and modularity.  Many packages are single file. 
https://github.com/babel/babel/tree/master/packages

- React has 31 packages: 
https://github.com/facebook/react/tree/master/packages

- Meteor has 144 packages:
https://github.com/meteor/meteor/tree/devel/packages

Those numbers make sense as they follow the architecture: React is a client-side web application framework, Babel is JS transpiler with many plugins, and Meteor is a server-side and client-side web application framework.

The architecture should be the driving factor. It's something we have in our mind and it evolves when developing the code, but the exercise is important and should be done in parallel.

**Comment by katelynsills** [comment]
@erights Thanks for putting this together! I'm mostly indifferent to how we group these, since we don't have a lot of usage of the packages that would further inform how we want to market and split them. 

A few questions:

Are we needing to/wanting to publish the packages to npm as well as have them in the monorepo? If so, we (I made this mistake) need to be more careful about what we name things and how we divide them up. I already talked to @FUDCo about how `@agoric/store` and `@agoric/weak-store` probably took a name that should have been used for Chip's database work. 

If/when we make changes to store and weak-store, can we make sure to rename the store and weak-store package to something to do with Maps, since they are modified maps? I know they don't have the exact map interface, but I think throwing out the map name entirely for that reason is a bit hasty. 

Do we need to remove the npm packages that already exist that would be deprecated due to this change? Previously, the list would include `@agoric/insist` (now @agoric/assert), and it looks like now the full list would be:

- [ ] @agoric/insist
- [ ] @agoric/store (or reused by Chip for another purpose)
- [ ] @agoric/weak-store
- [ ] @agoric/same-structure

Lastly, can we push these changes to after Zoe Alpha? It seems lower priority but a good clean up.

**Comment by erights** [comment]
> Lastly, can we push these changes to after Zoe Alpha? It seems lower priority but a good clean up.

Just want to discuss for now. Actually merging anything along these lines can wait till after Zoe alpha.

**Comment by warner** [comment]
Smaller pieces feels better from an internal code-organization point of view, although the actual dividing lines seem like a matter of personal taste. My deeper concern is with Kate's point: how/whether we present this modules to the outside world. The downside of the monorepo is that we're no longer thinking of these packages as individual products, and it's way harder to support downstream users of just one such package. We can be pretty casual about making incompatible changes when we think the only consumers live in the same monorepo, and we can modify both sides of the API boundary in the same commit. But we might have just broken some external consumer without noticing. We're less inclined to tag and publish releases of each package (since our day-to-day work uses the entire repo as a single unit, not separate packages downloaded from NPM), so that's starting to lag. It's a tradeoff, the monorepo improves development velocity for us, but makes the external presentation somewhat worse.

**Comment by jfparadis** [comment]
> But we might have just broken some external consumer without noticing.

I'm not convinced that the monorepo is the cause vs some other programming practice:
- Be very clear about your packages interfaces. Any package should provide a clear API, monorepo or not.
- If something breaks because of a change, a test should have caught it, monorepo or not.
- Is there a deeper change required in the monorepo? 

I mean, be very clear about what's part or not of the monorepo. There is a huge difference between a monorepo made for ease of development, aka "let's put all code together", vs a monorepo that's used to develop tightly related packages. 

Maybe `agoric-sdk` needs to be broken in two: combining the examples with the kernel code in the same monorepo makes is very hard to consider a monoversion. It's probably better to have kernel on one side, and the applications on the other, with a well defined contact between them.

Several monorepo use a monoversion: as soon as something changes in the monorepo, a new version of all packages is issued.

This works very well with large repos like Babel that are made of several small packages . When you make a dependency on any package from Babel, if all versions are the same, you have a guaranteed compatibility.

**Comment by katelynsills** [comment]
@erights are we still moving forward with this?

**Comment by erights** [comment]
> @erights are we still moving forward with this?

I intend to, yes. Probably as a prelude to passable-collections. Just not urgent right now.

**Comment by michaelfig** [comment]
@erights this PR seems to be stale.  Do you want to keep it open, or will we have to redo the work anyway?

**Comment by erights** [comment]
> @erights this PR seems to be stale. Do you want to keep it open, or will we have to redo the work anyway?

Would redo. So closing this one. Thanks.

**Pull request closed without merging**
