### PR TITLE
ci: merge endo integration branch

### PR DESCRIPTION
**Pull request by mhofman**
## Description

For CI runs which run using an endo branch instead of NPM packages, merge in a branch named `integration-endo-${endoBranchName}` if it exists. This allows staging changes to support the upcoming endo release, including any known breaking changes.

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

TBD (integration branch name should be added to any place that document this endo integration feature)

### Testing Considerations

The `integration-endo-master` branch is being used by this PR which uses the `master` branch of endo for its checks.

```
#endo-branch: master
```

### Upgrade Considerations

None

### CODE REVIEW

**Comment by mhofman** [comment]
@michaelfig I believe you already planned to integrate the currently breaking endo changes? Can you stage those in an `integration-endo-master` branch ?

**Comment by mhofman** [comment]
@michaelfig it looks like `integration-endo-master` is still an ancestor of `master` so no branch merge is being created. Until then I cannot mark this PR as ready for review.

**Comment by michaelfig** [comment]
> it looks like `integration-endo-master` is still an ancestor of `master`

I'm just curious how you think we should manage `integration-endo-master`.  Should it be the branch for a PR based on master that becomes the complete Endo sync PR and we merge it when ready?  Then would we recreate the same branch name with a new PR every time after that process?

**Comment by mhofman** [comment]
> > it looks like `integration-endo-master` is still an ancestor of `master`
> 
> I'm just curious how you think we should manage `integration-endo-master`. Should it be the branch for a PR based on master that becomes the complete Endo sync PR and we merge it when ready? Then would we recreate the same branch name with a new PR every time after that process?

It doesn't need to be the branch name used for the PR, but yes I would expect it to contain the commits we want to land on agoric-sdk when we cut a release of Endo. It's ok for it to be a direct ancestor of master when there are no commits required to make agoric-sdk compatible. But like now I would expect it to contain a staging of the commits to fix agoric-sdk and make the daily integration CI job green.

**Comment by mhofman** [comment]
Confirmed that it created a merge commit using the `integration-endo-master` branch, which is an actual branch and not pointing at a predecessor, so R4R!

**Review by michaelfig — APPROVED** [review]
LGTM!

**Pull request merged**
