### PR TITLE
Handle transient 0 refCounts correctly

### LINKED ISSUE #2923: test-message-patterns assert failures in refcounts
## Describe the bug

I was running tests in `packages/SwingSet` on current trunk tonight (80898e192574365b5a3a2d48c393b7edc1c544c5), and noticed `test-message-patterns.js` emitting some assertions that look troubling. They don't cause the test to fail, which is more troubling.

```
warner@turing:~/stuff/agoric/agoric-sdk/packages/SwingSet$ yarn test -s -v test/test-message-patterns.js
yarn run v1.22.5
$ ava -s -v test/test-message-patterns.js

  ✔ test pattern a10 local (266ms)
  ✔ test pattern a100 local (228ms)
  ✔ test pattern a11 local (180ms)
  ✔ test pattern a12 local (177ms)
  ✔ test pattern a20 local (191ms)
  ✔ test pattern a21 local (186ms)
  ✔ test pattern a30 local (167ms)
  ✔ test pattern a31 local (188ms)
  ✔ test pattern a40 local (192ms)
  ✔ test pattern a41 local (173ms)
  ✔ test pattern a42 local (206ms)
  ✔ test pattern a43 local (173ms)
  ✔ test pattern a44 local (191ms)
  ✔ test pattern a50 local (173ms)
  ✔ test pattern a52 local (172ms)
  ✔ test pattern a53 local (179ms)
  ✔ test pattern a60 local (186ms)
  ✔ test pattern a61 local (164ms)
  ✔ test pattern a62 local (193ms)
  ✔ test pattern a63 local (186ms)
  ✔ test pattern a64 local (242ms)
  ✔ test pattern a65 local (245ms)
  ✔ test pattern a70 local (168ms)
  ✔ test pattern a71 local (194ms)
  ✔ test pattern a72 local (190ms)
  ✔ test pattern a73 local (174ms)
  ✔ test pattern a80 local (180ms)
  ✔ test pattern a81 local (178ms)
  ✔ test pattern a82 local (178ms)
  ✔ test pattern a83 local (175ms)
  ✔ test pattern a84 local (186ms)
  ✔ test pattern a85 local (183ms)
  ✔ test pattern a86 local (180ms)
  ✔ test pattern a87 local (171ms)
  ✔ test pattern a90 local (176ms)
  ✔ test pattern a91 local (178ms)
  ✔ test pattern a10 comms (668ms)
doProcess: vat[v6].notify failed: promise "lp225" in deadLocalPromises with non-zero refcount
doProcess: vat[v6].notify failed: promise "lp225" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp125" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp125" in deadLocalPromises with non-zero refcount
  ✔ test pattern a100 comms (910ms)
  ✔ test pattern a11 comms (597ms)
  ✔ test pattern a12 comms (675ms)
  ✔ test pattern a20 comms (700ms)
  ✔ test pattern a21 comms (748ms)
  ✔ test pattern a30 comms (705ms)
  ✔ test pattern a31 comms (719ms)
  ✔ test pattern a40 comms (713ms)
  ✔ test pattern a41 comms (691ms)
  ✔ test pattern a42 comms (723ms)
  ✔ test pattern a43 comms (652ms)
doProcess: vat[v6].notify failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
  ✔ test pattern a44 comms (679ms)
doProcess: vat[v6].notify failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
  ✔ test pattern a50 comms (718ms)
doProcess: vat[v6].notify failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+132].b51_2 dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
doProcess: vat[v6][o+230].receive dispatch failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v6].notify failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
  ✔ test pattern a51 comms (697ms)
doProcess: vat[v6].notify failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+132].b52_2 dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
doProcess: vat[v6][o+230].receive dispatch failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v6].notify failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
  ✔ test pattern a52 comms (740ms)
doProcess: vat[v6].notify failed: promise "lp221" in deadLocalPromises with non-zero refcount
doProcess: vat[v5][o+130].receive dispatch failed: promise "lp121" in deadLocalPromises with non-zero refcount
  ✔ test pattern a53 comms (743ms)
  ✔ test pattern a60 comms (682ms)
  ✔ test pattern a61 comms (677ms)
  ✔ test pattern a62 comms (734ms)
  ✔ test pattern a63 comms (754ms)
  ✔ test pattern a64 comms (788ms)
  ✔ test pattern a65 comms (771ms)
  ✔ test pattern a70 comms (742ms)
  ✔ test pattern a71 comms (851ms)
  ✔ test pattern a72 comms (921ms)
  ✔ test pattern a73 comms (720ms)
  ✔ test pattern a80 comms (839ms)
  ✔ test pattern a81 comms (811ms)
  ✔ test pattern a82 comms (767ms)
  ✔ test pattern a83 comms (810ms)
  ✔ test pattern a84 comms (787ms)
  ✔ test pattern a85 comms (802ms)
  ✔ test pattern a86 comms (786ms)
  ✔ test pattern a87 comms (775ms)
  ✔ test pattern a90 comms (766ms)
  ✔ test pattern a91 comms (788ms)
  ─

  73 tests passed
```

When the comms vat has a `dispatch.deliver` failure, the kernel logs-and-ignores, because vats shouldn't be able to kill the kernel. But the comms vat is clearly calling for help here. So we've got two tasks:

* figure out how to elevate these assertions so they at least cause this unit test to fail
* fix the assertions

### PR DESCRIPTION
**Pull request by FUDCo**
Fixes #2923

### CODE REVIEW

**Comment by warner** [comment]
Wait, I forgot what we just discussed. What is a pathway through which we could have a temporary zero refcount?

It feels like it's got to be for an ephemeral promise.. if it were a real one, the refcount would start at 2 (both the decider and the e.g. one downstream subscriber know about it).. the resolve from one side would drop it to 1 when we retire their ID, the act of sending the resolution downstream would leave it at 1 (because we don't retire the downstream clist until we get an ack), and finally the ack would drop it to 0.

If it were ephemeral, say as part of a `resolve` batch.. ah yeah. The ancillary promise gets added to the message sender's clist during translation of their batch. It gets resolved later in the batch, which removes it from the sender's clist, changing the refcount to zero, however the `handleResolve` is still running (the extra reference lives on the stack, basically). We add it to the outbound clist, raising the refcount to 1, then send the `resolve`. We don't drop it back to 0 until we get the ack.

Ok, could you add the following comment to `decrementRefCount` at line 202, just inside the "if refcount === 0" clause?:


*If we are still in the middle of a resolve operation, and this lref is an ancillary promise that was briefly added to the decider's clist, we'll reach here when we retire that short-lived identifier. However the lref is still in play: the resolution function hasn't finished running, and we'll add the lref to the subscriber's clist momentarily, where it will live until we get an ack and can retire it from that clist too. We add the lref to the maybe-dead set, but we do not trigger GC until the entire comms dispatch is complete and any ancillary promises are safely referenced by their subscribers clists.*


That'll help me in the future when I get similarly confused again.

**Comment by FUDCo** [comment]
Done.

**Review by warner — APPROVED** [review]
Great, thanks. Looks good, glad it was so simple.

BTW eslint might fuss about that comment having inconsistent indentation.

**Comment by FUDCo** [comment]
> BTW eslint might fuss about that comment having inconsistent indentation.

Dang.   Something somewhere in the cut-n-paste operation between your edit request and my code inserted a couple of TAB characters.  I thought I had emacs configured to never, ever, ever, ever allow a file to be saved with a tab character in it.  Anyway, it's fixed now.

**Pull request merged**
