### PR TITLE
Don't retain a vat's raw bundle string after use

### LINKED ISSUE #6981: liveslots / supervisor hold on to vat bundle longer than necessary, could save 1.2MB of ZCF bundle
I've been dissecting XS snapshot files, to understand better how XS works, and to see how our vats are holding onto data. I discovered that there is a copy of the original vat bundle still in RAM, thousands of deliveries after vat startup. In particular I see a contract vat, v11 on pismoA, holding onto a string which is a base64 encoding of a zipfile with a `compartment-map.json` that starts with:
```
{
  "entry": {
    "compartment": "@agoric/zoe-v0.25.3",
    "module": "./contractFacet.js"
  },
```

I think our supervisor is receiving this from the netstring command pipe during `setBundle`:

https://github.com/Agoric/agoric-sdk/blob/adc0836e01eab0fd6084ecf3f59687668a98ed54/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js#L194

it stores the large bundle string in the `bundle` argument, and then creates a cascade of objects, including the `buildVatNamespace` function (which will evaluate the bundle, once invoked): 

https://github.com/Agoric/agoric-sdk/blob/adc0836e01eab0fd6084ecf3f59687668a98ed54/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js#L265-L275

Then it calls `makeLiveSlots(.. buildVatNamespace ..)`.

Later, the kernel sends a `startVat` delivery, which (among other things) invokes `buildVatNamespace()`.

We only ever deliver `startVat` once, so we only invoke `buildVatNamespace()` once, and that's the only thing which actually uses the `bundle` argument that has been closed over.

But of course the JS engine doesn't know that, so it is obligated to hold on to the bundle forever.

So we could save 1.2MB of RAM by finding a way to let the engine drop that bundle. Engines are usually pretty coarse about lexical scopes: they don't analyze the code to see which names are being held, they frequently just hold the entire stack frame. So one task is to rewrite that code to avoid closing over everything.

It's probably too difficult to get liveslots to drop the `buildVatNamespace` argument (that would be a lot of refactoring). But it'd probably be sufficient to make our `buildVatNamespace` function overwrite its copy of `bundle` with an `undefined` after being called (and throw an error if it ever gets called a second time).

### PR DESCRIPTION
**Pull request by FUDCo**
Closes #6981

I'm having trouble believing this is as trivial as it appears to be, and I have no idea how to test it, but here we go.

### CODE REVIEW

**Comment by warner** [comment]
looks like test-vats had a timeout again, try rebasing and re-pushing to kick it

**Review by warner — APPROVED** [review]
Yeah, I think that'll do it. Go ahead and land this.. I'll dig up my heap-snapshot dissection tools and see if I can verify it the same way I found the problem in the first place, but let's assume that it is an improvement and land this without waiting for me.

**Comment by FUDCo** [comment]
> looks like test-vats had a timeout again, try rebasing and re-pushing to kick it

This has been happening a lot lately.  My recipe has been to keep hitting the Re-run button until it works.

**Comment by warner** [comment]
I've confirmed that the bundle string (and its ID, which was the second-longest string) is now gone from the snapshot, by ingesting the heap snapshot and then examining the strings table, using the small `vat-target.js` from `SwingSet/test/workers/test-worker.js`.

Before:

```
$ sqlite3 v6-old.sqlite 'SELECT LENGTH(string),string from strings' |sort -n |tail -5 |cut -c-200
38|root.%ReferenceErrorPrototype%.message
39|dontDecodeRemotableOrPromiseFromCapData
40|Prior lockdown (SES_ALREADY_LOCKED_DOWN)
128|08401f8abda78eb3dbbbeef27061244c743ca6a8e02263c9d910f9f846262778effba386441eaf4fc01d40b2d767e80e27b3636462d06cb3baab9883b21e4842
138900|UEsDBAoAAAAAAAAAAABYXeTx+EsAAPhLAAAUAAAAY29tcGFydG1lbnQtbWFwLmpzb257CiAgImVudHJ5IjogewogICAgImNvbXBhcnRtZW50IjogIkBhZ29yaWMvc3dpbmdzZXQtdmF0LXYwLjMwLjIiLAogICAgIm1vZHVsZSI6ICIuL3Rlc3Qvd29ya2Vyc ...
```

after:
```
$ sqlite3 v6-new.sqlite 'SELECT LENGTH(string),string from strings' |sort -n |tail -5 |cut -c-200
37|root.%TypeErrorPrototype%.constructor
37|validatePrecompiledStaticModuleRecord
38|root.%ReferenceErrorPrototype%.message
39|dontDecodeRemotableOrPromiseFromCapData
40|Prior lockdown (SES_ALREADY_LOCKED_DOWN)
```

**Pull request merged**
