### PR TITLE
test: make it possible to label representatives during debugging

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
## Description

I've been looking for a way to distinguish different opaque representatives during debugging. @warner showed me how. I've added a flag to make it simple to turn this on when needed.

### Security Considerations

In production, logs shouldn't contain this detail. During debugging, it's fine.

### Documentation Considerations

We don't tend to write this kind of thing up.

### Testing Considerations

This made it far easier for me to debug while working on #6167.  I've wanted the same ability several times before.

### CODE REVIEW

**Comment by Chris-Hibbert** [comment]
@warner I continue to find this useful while debugging. Any chance it could be added to the virtualObjectManager.js?

**Comment by Chris-Hibbert** [comment]
Actually, I have an enhancement to add. I'll ask for a review again shortly.

**Review by erights — CHANGES_REQUESTED** [review]
Just "Requesting changes" for now as an interlock, to be sure I look again before this is merged to master.

**Comment by Chris-Hibbert** [comment]
I converted this to draft in response to a request to minimize open PRs that aren't slated for merging.

This is still useful to me, but it apparently conflicts with swingset's priorities.

What I get from this code is the ability to track individual objects in logging messages across vats. Without it, remote objects are all anonymous, and it is very hard to distinguish two objects of the same type, other than by their behavior.

**Comment by turadg** [comment]
> This is still useful to me, but it apparently conflicts with swingset's priorities.

This would also be very useful to me for debugging contracts. Is there a way we can have a dev or debugging mode flag for this in master?

**Comment by erights** [comment]
I like the goal. I do not like the means. For one thing, once we upgrade to latest endo, an eventual send with a non-understood method name will produce the list of actual methods, as it used to before virtual objects. I don't like that there will appear a method with a magic per-instance method name.

Ok if I give it a shot? I added myself to the assignees for this PR. I hope to find the time to try, sometime after we've upgraded agoric-sdk to depend on a recent endo release.

There is also the separate matter of how configuration options get passed through to code in vats. This needs a separate discussion.

**Comment by Chris-Hibbert** [comment]
> There is also the separate matter of how configuration options get passed through to code in vats. This needs a separate discussion.

Is this related to how the feature could be enabled and disabled?  It would be nice to be able to control this at run-time, but not at all necessary for debugging. What other configuration options have an impact on this feature?

**Comment by erights** [comment]
Closing in favor of https://github.com/endojs/endo/pull/1554 and its upcoming agoric-sdk sibling

**Pull request closed without merging**
