### PR TITLE
[Zoe] initPublicAPI in sellerHook for sellItems and publicAuction contract

### LINKED ISSUE #1142: [Zoe] publicAuction and sellItems should initPublicAPI in sellerOfferHandle
_Originally posted by @katelynsills in https://github.com/Agoric/agoric-sdk/issues/999#issuecomment-636184319_

Mark [says](https://github.com/Agoric/agoric-sdk/issues/999#issuecomment-635643892): "In the old system a publicAPI had to exist before the first offer is made, which led to bad concurrency patterns of mutating shared variables, and checking to see if they were already mutated. In the new system, it will often be the use of the first invite to make the first offer that brings the publicAPI into existence. This is useful, because the existence of the publicAPI guarantees that an adequate first offer has already been made and acted on."

### PR DESCRIPTION
**Pull request by katelynsills**
Closes #1142. Change sellItems and publicAuction contract such that the publicAPI is only created after the seller has escrowed.

WIP because: Looking at the changes that needed to be made, I'm not sure this is an improvement. The contracts seem to be harder to read, and we can't get the publicAPI when we make the instance, so we lose the gains from the improvement that Chris made.

### CODE REVIEW

**Comment by Chris-Hibbert** [comment]
I agree that this isn't an obvious improvement.

Unlike you, I didn't have the feeling that it would be an improvement to hold off on creating publicAPI until after the seller's escrow. What did you see that I missed that made that seem likely to make things better?

**Comment by katelynsills** [comment]
> Unlike you, I didn't have the feeling that it would be an improvement to hold off on creating publicAPI until after the seller's escrow. What did you see that I missed that made that seem likely to make things better?

Hmm, I don't think I had that feeling. It was Mark who mentioned this as important: https://github.com/Agoric/agoric-sdk/issues/1142

**Comment by Chris-Hibbert** [comment]
Thanks for reiterating the link.

> It was Mark who mentioned this as important: #1142

@erights, please weigh in here.

That make more sense of it for me. It's okay that it's a little harder to create the publicAPI in some of these cases, since it's the second party (Bob) who needs it. They shouldn't be using Alice's copy of the publicAPI, they should make their own. 

I think this clarifies that the publicAPI isn't for the use of the first party to the contract, so maybe we should undo the change that I made. If the contract wants to make functionality available to the first party, it doesn't have to be in the publicAPI. Maybe that should be reserved for later parties, which is why the contract gets to decide when it has enough info to call setPublicAPI().

**Comment by katelynsills** [comment]
I'm going to close this PR since I think it is a step backward, but if/when we want to revisit, we can reopen

**Pull request closed without merging**
