### PR TITLE
refactor(swingset-liveslots): stateShape causes accessor sharing

### PR DESCRIPTION
**Pull request by erights**
When a kind is provided with a `stateShape`, we know exactly what the names are for all of the `state` fields across all instances. For that case, it is wasteful to create accessor properties per instance. So instead, when there is a `stateShape`, this PR will instead install similar accessors on a shared `statePrototype` object. Each `state` object is them a frozen empty object that inherits from that `statePrototype`. As with a shared prototype for methods, to make this work, we also introduce a separate `stateToInnerSelf` weakmap, so the accessor can get the correct `innerSelf` from its `this`, which is the empty state instance itself.

See also 
https://github.com/Agoric/agoric-sdk/pull/7289
https://github.com/Agoric/agoric-sdk/issues/6693
https://github.com/Agoric/agoric-sdk/pull/7138

### CODE REVIEW

**Comment by warner** [comment]
@erights That's really cool, and I look forward to using it. That file, however, is about to be changed drastically by https://github.com/Agoric/agoric-sdk/pull/7138 , and I'm wondering if you could instead look at the target branch (`6693-vo-lru-cache`) and see if you can make the corresponding change to it instead? I replaced `contextMap` with a `provideContext` function, and `innerSelf` disappears entirely. I think the same approach can be made (and it should be a good bit simpler), but if we land it first, I'm going to spend days trying to understand how it works and changing my PR to match, whereas I bet you could make the same changes to my branch pretty quickly.

I'm going to be rebasing my branch heavily as I get it ready for review and landing (still fighting through some unit test changes now). If you make a branch based on the current `6693-vo-lru-cache`, I'd be happy to manage any updates or rebasing that your branch needs as I make changes to my branch.

**Comment by erights** [comment]
@warner understood. Good plan. I've converted this to draft at least until I rebase and reconcile with #7138

**Comment by warner** [comment]
@erights [`7338-store-state-shape`](https://github.com/Agoric/agoric-sdk/tree/7338-store-state-shape) is the branch to base your work on, it's still in review but barring changes it's what trunk should look like in a few days

**Review by FUDCo — APPROVED** [review]
Thatsa very nice.

**Comment by erights** [comment]
Closing in favor of https://github.com/Agoric/agoric-sdk/pull/7444

**Pull request closed without merging**
