### PR TITLE
feat(inter): --fees option for sending bid tx

### LINKED ISSUE #7995: Bidding CLI tool doesn't consider gas fees
## Describe the bug
The bidding CLI tool wasn't scoped to include handling mainnet fees. It is therefore not documented and is problematic for bidders as they need to specify fees when submitting bid on mainnet (this was not a problem/requirement on testnets).

A workaround has been documented for bidders here: https://docs.inter.trade/user-how-to/bidding-for-liquidated-collateral however an actual fix is required.

Slack ref: https://agoricopco.slack.com/archives/C038TM0EUKG/p1688134435159649 (Internal)

## To Reproduce

Attempt to submit a bid
Bid fails as bidder has not specified fee option

## Expected behavior
Bidding tool should better handle mainnet fees without having to do any magic/pass too many arguments

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

### PR DESCRIPTION
**Pull request by dckc**
closes: #7995

## Description

add `--fees` option and pass thru to `agd`.

### Security / Scaling Considerations

none

### Documentation Considerations

`test-inter-cli.js.md` is updated to show the `--fees` option

Ideally, lack of fees shouldn't be treated as a crash with stack trace. But it doesn't seem too bad.
The diagnostic now includes the "insufficient fees ..." detail.

### Testing Considerations

Only manually tested. Bidding without fees failed:

```
$ AGORIC_NET=main inter bid by-price --price 7 --give 0.0011IST --from k1
(Error#1)
Error#1: failed to send tx: insufficient fees; got:  required: 2000ubld,1000uist: insufficient fee code: 13

  at sendAction (packages/agoric-cli/src/lib/wallet.js:162:17)
  at placeBid (packages/agoric-cli/src/commands/inter.js:345:26)
  at Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:431:15)
```

This tells us to use `--fees 2000ubld` (or `--fees 1000uist`), which worked:

```
$ AGORIC_NET=main inter bid by-price --price 7 --give 0.0011IST --from k1 --fees 2000ubld
2023-07-01T21:02:10.674236534Z tx not in block 10580369 retrying...
bid is broadcast:
{"timestamp":"2023-07-01T21:02:16Z","height":"10580370","offerId":"bid-1688245339595","txhash":"E2E6347EFEC03E1271FCD6355570322B7F31D68C77319B6E10216951795D27C1"}
{"id":"bid-1688245339595","price":"7 IST/ATOM","give":{"Bid":"0.0011 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}
```

### CODE REVIEW

**Review by otoole-brendan — APPROVED** [review]
@dckc tested on a tested but then realized it was only caught on mainnet so can't test there until deployed. Product can approve the '--fees X' option style for this but that's about it.

**Review by dtribble — APPROVED** [review]
The code LGTM but I have not run it yet.

**Comment by rowgraus** [comment]
Testing in mainnet and getting this response (values changed to 'xx')

```
rowlandgraus@Rowlands-MacBook-Pro agoric-sdk % inter bid by-discount --discount xx --give xxxIST --from bid-acct --fees 2000ubld                
(SyntaxError#1)
SyntaxError#1: Unexpected token D in JSON at position 0

  at JSON.parse (<anonymous>)
  at sendAction (packages/agoric-cli/src/lib/wallet.js:160:19)
  at placeBid (packages/agoric-cli/src/commands/inter.js:345:26)
  at Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:470:15)
```

**Comment by dckc** [comment]
@rowgraus the `Unexpected token D in JSON` problem was sort of a separate issue. `agd` was adding an unexpected diagnostic to its output when using a Ledger:

```
Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
```

I presume nobody minds if I include the fix (aae3179c8) in this PR. `git pull` should get it for you. Then try again?

I verified it on devnet:

```
$ AGORIC_NET=devnet inter bid by-price --price 7 --give 0.0011IST --from lx2 --fees 2000ubld
2023-07-05T23:44:40.912461503Z tx not in block 310031 retrying...
2023-07-05T23:44:46.587419647Z tx not in block 310032 retrying...
bid is broadcast:
{"timestamp":"2023-07-05T23:44:46Z","height":"310032","offerId":"bid-1688600674873","txhash":"66324C5350C7946E78E33ABDD2EC67BA3837CA8FAD15B5CCDA74B93A99B30B04"}
{"id":"bid-1688600674873","price":"7 IST/ATOM","give":{"Bid":"0.0011 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}
```

**Review by turadg — APPROVED** [review]

**Pull request merged**
