### PR TITLE
fix(telemetry): Update @opentelemetry packages

### LINKED ISSUE #6513: otel collector no longer likes our traces
## Describe the bug

Our tracing exporter no longer works out of the box with the latest version of otelcol-contrib.  It does work with otelcol-contrib on version 0.50.0 however.

Testing otelcol-config:
```
receivers:
  otlp:
    protocols:
      http:
        endpoint:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: 
        - otlp
      exporters: 
        - logging
```

Config:
```
[Unit]
Description=Agoric Cosmos daemon
After=network-online.target

[Service]
User=ari
ExecStart=/home/ari/go/bin/agd start --log_level=warn
Restart=on-failure
RestartSec=3
LimitNOFILE=65536
Environment=OTEL_EXPORTER_PROMETHEUS_PORT=26661
Environment=SLOGFILE=/home/ari/.agoric/data/chain.slog
Environment=SLOGSENDER_AGENT=process
Environment=SLOGSENDER=@agoric/telemetry/src/otel-trace.js
Environment=OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces
[Install]
WantedBy=multi-user.target
```

Expected behavior: 
- Spans will print to console when using https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.63.0
(Spans do print when using https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.50.0)

Observed behavior:
- Spans do not print at all or make it past ingest

### PR DESCRIPTION
**Pull request by mhofman**
closes: #6513

## Description

The protobufs changed some time ago in the open telemetry collector, and newer versions are no longer compatible with the version of the JS SDK we're using.

This updates the OpenTelemetry JS SDK and deals with the fallout of the API changes.
In particular:
- Histogram metrics now need to have their custom aggregation configured explicitly when creating the metricsProvider. This causes quite a bit of change in the layering between kernel-stats and the telemetry package.
- Counters now require the observable part to be initialized separately.
- The exporter now needs to be added explicitly.

### Security Considerations

Always a supply chain risk when updating versions, but all the updated dependencies come reputable sources.

### Testing Considerations

Good question? @michaelfig I'm not sure how to test this, especially the kernel-stats changes.

@arirubinstein maybe we could deploy this on a follower node, and test in the field?

### CODE REVIEW

**Review by michaelfig — APPROVED** [review]
LGTM!

As far as testing beyond basic sanity, you can configure a local otelcol instance to forward to Honeycomb (the same config as is done in instagoric) or start an instagoric cluster.

If you want to do that before merging, I can help.

**Comment by mhofman** [comment]
@arirubinstein could you use this branch on the mainnet follower node maybe? It contains the earlier fix too.

**Comment by mhofman** [comment]
> If you want to do that before merging, I can help.

I think I'm not just quite sure what to look for. I admit I don't fully understand what the `kernel-stats` stuff does.

**Comment by mhofman** [comment]
Landed in #7010

**Pull request closed without merging**
