### PR TITLE
wip: first makeKind refactoring experiment

### PR DESCRIPTION
**Pull request by erights**
First substantial experiment refactoring from objects-as-closures to makeKind. Lints but doesn't work yet. But encouraging!

To be explained.

To be debugged.

### CODE REVIEW

**Review by FUDCo — COMMENTED** [review]
Seems legit so far.  I'm sure you'll let me know about any hiccups.

**Comment by erights** [comment]
> Seems legit so far. I'm sure you'll let me know about any hiccups.

We got a hiccup. We'll let you know more tomorrow ;)

**Comment by erights** [comment]
At https://github.com/Agoric/agoric-sdk/runs/5241436212?check_suite_focus=true#step:5:527 is
```
TypeError#1: Cannot read property 'getAmountAllocated' of undefined
  at Alleged: pool.getSecondaryAmount (.../run-protocol/src/vpool-xyk-amm/pool.js:117:31)
  at makeSinglePool (.../run-protocol/src/vpool-xyk-amm/singlePool.js:25:31)
  at eval (.../run-protocol/src/vpool-xyk-amm/pool.js:212:19)
  at makeRepresentative (packages/SwingSet/src/kernel/virtualObjectManager.js:494:30)
  at makeNewInstance (packages/SwingSet/src/kernel/virtualObjectManager.js:546:9)
  at Alleged: publicFacet.addPool (.../run-protocol/src/vpool-xyk-amm/pool.js:289:18)
```
This takes us to
https://github.com/Agoric/agoric-sdk/blob/d1f19f27a5eca9fae289ca6366ec7e41c78979d2/packages/run-protocol/src/vpool-xyk-amm/pool.js#L113-L121

We fail on line 117 with the above error message, so we put in the `debugger;` statement, ran in a debug shell under vscode, stopping there in the debugger. The `state` object is empty. It seems to be a normal empty object. We don't understand why.

Help! (but tomorrow)

**Comment by erights** [comment]
Closing in favor of https://github.com/Agoric/agoric-sdk/pull/4630

**Pull request closed without merging**
