### PR TITLE
Govern add collateral

### LINKED ISSUE #3924: Enable Governance to add Collateral type to Treasury
## What is the Problem Being Solved?

Adding a Collateral type to the Treasury should be under the control of governance.

## Description of the Design

I think this requires a special purpose function, and some general purpose controls to manage and make visible the control over when the function gets invoked. 

The special purpose function includes creating a vaultManager, endowing/finding an appropriate AMM, and connecting the two up as well as setting up the parameters for the new pool & vaultMgr.

## Security Considerations

This involves governance, so the standard legibility targets apply. 

## Test Plan

Probably requires SwingSet tests including multiple voters, and a demonstration of someone validating the chain of responsibility.

as part of RUN Protocol preview:
 - [x] #5169
 - [x] #3595
 - [x] #5084
 - [x] #4714

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #3924

## Description

Add a new Collateral type to the Treasury as a result of a Governance vote.

This is a first step. More changes coming.

### Security Considerations

This is part of contract governance, so it needs to be both secure and legible.

### Documentation Considerations

Updates to Treasury doc. Updates about how governed contracts can be informed about chosen changes. 

### Testing Considerations

thorough and convincing tests, because this is part of governance.

### CODE REVIEW

**Comment by dckc** [comment]
@warner it's by design that the return value from `queueToKref` in `notifyMeterThreshold` (`kernel.js:382`) is ignored, right?

```
  function notifyMeterThreshold(meterID) {
    ...
    queueToKref(vatAdminRootKref, 'meterCrossedThreshold', args, 'logFailure');
  }
```

context: while looking at a [sequence diagram from a slog of `test/swingsetTests/treasury/test-treasury.js`](https://gist.github.com/b47c19b8d1ca8c7210adf85e0dc4363c), I don't see a resolution of `kp222`:

image

In the slog, I see a `resolve` syscall but no `notify` delivery.

This makes me wonder if some resulting garbage just accumulates. I can't imagine it's much of an issue, but I figure I might as well make a note while I have the info.

**Comment by warner** [comment]
> @warner it's by design that the return value from `queueToKref` in `notifyMeterThreshold` (`kernel.js:382`) is ignored, right?

That's fine.. no garbage should be accumulated. The `logFailure` option means it will allocate a kernel promise ID and mark it as "if this promise is rejected, announce it to console.log". That Promise will be resolved when `meterCrossedThreshold()` in `src/kernel/vatAdmin/vatAdminWrapper.js` returns, and there's only two lines in there (no `await` or other Promises), so it will happen promptly, and the kernel will clean up all the storage when the Promise is resolved. If some kernel/`vatAdminWrapper.js` bug causes that to fail, the Promise will be rejected, logged, and then cleaned up.

We might consider changing that `logFailure` to `none`, which would effectively do a `sendOnly` (no result promise at all). That would save one `syscall.resolve()`, at the cost of concealing any exception-raising bugs in `meterCrossedThreshold`.

**Comment by dckc** [comment]
This is meant to fix #3924, right?

#3913 is the internal demo.

**Comment by Chris-Hibbert** [comment]
> This is meant to fix #3924, right?

fixed. Thanks.

**Comment by Chris-Hibbert** [comment]
The next attempt will be based on API governance.

**Comment by Chris-Hibbert** [comment]
obviated by #3924

**Pull request closed without merging**
