### PR TITLE
convert acorn-eventual-send to proper ES6 module

### PR DESCRIPTION
**Pull request by warner**
and remove the `-r esm`

- [ ] eslint doesn't like the new requirements yet

### CODE REVIEW

**Comment by warner** [comment]
@jfparadis take a look, maybe you've got a clever trick to make eslint happy

**Comment by warner** [comment]
The errors are:

```
$ yarn lint-check
yarn run v1.21.1
$ eslint '**/*.js'

/home/warner/bindmounts/trees/agoric-sdk/packages/acorn-eventual-send/test/test-rollup.js
  10:38  error  Parsing error: Unexpected token import

/home/warner/bindmounts/trees/agoric-sdk/packages/acorn-eventual-send/test/test.js
  1:1   error  'tape' should be listed in the project's dependencies. Run 'npm i -S tape' to add it  import/no-extraneous-dependencies
  3:26  error  Unexpected use of file extension "js" for "../index.js"                               import/extensions

✖ 3 problems (3 errors, 0 warnings)
```

Adding `"parser": "babel-eslint",` (which I cribbed from a SES-beta repo) fixes the parsing error, and results in these problems instead:

```
$ yarn lint-check
yarn run v1.21.1
$ eslint '**/*.js'

/home/warner/bindmounts/trees/agoric-sdk/packages/acorn-eventual-send/test/test-rollup.js
  3:1   error  'tape' should be listed in the project's dependencies. Run 'npm i -S tape' to add it  import/no-extraneous-dependencies
  4:1   error  Expected 1 empty line after import statement not followed by another import           import/newline-after-import
  6:1   error  Import in body of module; reorder to top                                              import/first
  7:1   error  Import in body of module; reorder to top                                              import/first
  7:26  error  Unexpected use of file extension "js" for "../index.js"                               import/extensions

/home/warner/bindmounts/trees/agoric-sdk/packages/acorn-eventual-send/test/test.js
  1:1   error  'tape' should be listed in the project's dependencies. Run 'npm i -S tape' to add it  import/no-extraneous-dependencies
  3:26  error  Unexpected use of file extension "js" for "../index.js"                               import/extensions

✖ 7 problems (7 errors, 0 warnings)
  3 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by warner** [comment]
I'm hoping to consolidate all our testing code into the top-level `package.json` (so we're using the same versions everywhere), so I want eslint to be ok with `tape` not being in the per-package `package.json`. I don't know if eslint is aware of yarn workspaces, ideally it would see that the top-level `package.json` provides `tape` and not complain that it isn't present elsewhere.

The `../index.js` complaint is going to be a disagreement between what node's native module support requires, and what eslint thinks it should be capable of. We have to find some switch to reconcile the two.

**Comment by jfparadis** [comment]
@warner, eslint is not aware of workspaces. You have 2 main options:
1. Keep everything at the package level, so you can run/customize eslint and work around blockers. Use lerna or yarn workspaces to run eslint inside every package. That's what I do in SES shim.
2. Hoist the dependencies, and configure and run eslint from the top. It's less flexible, if you want to tighten the rules, you must do everything at once. You also should get a tighter naming convention for tests like *.test.js or *.spec.js which are commonly used.

Managing dependencies in one place by hoisting is a bit of an illusion: only the declarations are hoisted, and yarn doesn't actually install files in every package even if they are not. An even managing all dependencies in one place is cumbersome without a tool.

I much prefer to have `dependecies` and `devDependencies` work the same instead of splitting them up, and use a tool to manage them (find what's outdated, and install them). Check `lernaupdate`, it's a real time saver because it covers everything.

https://www.npmjs.com/package/lerna-update-wizard

**Comment by warner** [comment]
Ok, I've unhoisted the dependencies.. I'll give `lerna` a try for managing those in-place in all the packages.

I copied the eslint config from SES-beta to make it happy with the `.js` suffix on import names.

Still working through the other CI failures.

**Comment by michaelfig** [comment]
@warner is this PR now stale?  If so, please delete it.

**Comment by michaelfig** [comment]
Closing for now.  Please reopen if you want.

**Pull request closed without merging**
