### PR TITLE
misc types cleanup

### LINKED ISSUE #1798: v8 error taming should leverage `prepareStackTrace`
## What is the Problem Being Solved?

`Error.prepareStackTrace` can be [used by Node.js to apply source maps](https://nodejs.org/docs/latest-v16.x/api/cli.html#--enable-source-maps) to the captured stack trace. However SES sets its own `prepareStackTrace` during v8 Error taming. Instead of completely discarding it. Maybe instead it should leverage as much as possible the existing `prepareStackTrace` to prepare its own stack strings?

Furthermore, if the start compartment set a `prepareStackTrace` after lockdown, it seems the returned value will be used for the `.stack` property instead of the empty string, even if `errorTaming` is set to `'safe'`: https://github.com/endojs/endo/blob/2a85f8aa6684b4d4a92fea48ccc63d01ccddc85e/packages/ses/src/error/tame-v8-error-constructor.js#L301-L304

## Description of the Design

Use the original `prepareStackTrace` to generate the stack string.

Alternatively implement source map support in endo itself (maybe once part of the error handling logic has been ejected from SES as a trusted shim?, see #945). While [node's `prepareStackTrace` implementation is not very modular](https://github.com/nodejs/node/blob/a86c2caea9c329442bbbd8eeec6d5385b594b7ca/lib/internal/source_map/prepare_stack_trace.js#L73-L102), it should be possible to rebuild it on top of [`findSourceMap`](https://nodejs.org/api/module.html#modulefindsourcemappath).

## Security Considerations

None particularly. The start compartment is already in position to decide how lockdown should tame errors, and can also set `prepareStackTrace` after lockdown

## Scaling Considerations

None

## Test Plan

load some minified source which throws errors in Node.js with `--use-source-maps` and verify stack traces are mapped.

## Upgrade Considerations

None particular

### PR DESCRIPTION
**Pull request by turadg**
refs: https://github.com/endojs/endo/pull/1798

## Description

Adds a patch to fix https://github.com/endojs/endo/pull/1798 until  https://github.com/endojs/endo/pull/1799 is published and adopted in this repo.

Includes some other types fixes that were ready to go.

### Security Considerations

n/a

### Scaling Considerations

n/a
### Documentation Considerations

n/a

### Testing Considerations

CI

### Upgrade Considerations

n/a

### CODE REVIEW

**Review by mhofman — APPROVED** [review]
Patch is fine (same as I provided). Rest seems fine, but I didn't review thoroughly

**Review by FUDCo — APPROVED** [review]
Well ok then

**Comment by erights** [comment]
Curious how the other changes came to need the patch change. What broke when only the patch was omitted?

This question is completely non-urgent. Do not delay merging this PR to answer. Thanks.

**Comment by turadg** [comment]
>Curious how the other changes came to need the patch change. What broke when only the patch was omitted?

[83b1fc8](https://github.com/Agoric/agoric-sdk/pull/8428/commits/83b1fc89eb892c9783cc79e0f5753a076ff3a494) is the only thing needed for the stack traces. The other two commits were misc cleanup

**Comment by turadg** [comment]
reverting to draft because we're still seeing line 1 traces (e.g. `packages/boot/test/bootstrapTests/test-demo-config.ts:1:1038`)

**Comment by erights** [comment]
Hi @turadg , as a draft this was unassigned. I went ahead and assigned myself as I intend to look at the stack-trace-info-loss portion of this, and hopefully make progress.

**Comment by turadg** [comment]
Solved by https://github.com/endojs/endo/pull/2355/

**Pull request closed without merging**
