### PR TITLE
fix: message batches reduce wallet setup from 80 to 20 chain trips

### PR DESCRIPTION
**Pull request by michaelfig**
Big performance win, where the ag-solo batches its delivery to the chain by accumulating messages until 1s (configurable) passes.

### CODE REVIEW

**Review by warner — COMMENTED** [review]
This looks straightforward enough, but:

* As written, the delivery could be pushed arbitrarily far into the future, if `batchedDeliver` is called more than once every `batchTimeoutMs`. The usual Nagle algorithm doesn't reset the timer: it gets set once when the queue is empty, accumulates until it expires, then sends.
* I don't exactly remember how the simulated chain works now, but I think we could accomplish the same thing without the extra timer by accumulating outbound messages while a "block" is being executed, then delivering them at the end. This is effectively how it would work in a real chain, since the act of "sending" is really just allowing the block's outbound message to be seen in the chain state vector. We might have written the simulated chain's `deliver` function in a standalone way (i.e. `deliver` must do all of its work right away, because it can't assume anyone else will come around later to finish the job). But we could change that: `deliver` would strictly queue the messages, and then a new function we add to the end of the simulated block cycle would process the queue. That might be cleaner.

**Comment by michaelfig** [comment]
> * As written, the delivery could be pushed arbitrarily far into the future, if `batchedDeliver` is called more than once every `batchTimeoutMs`. The usual Nagle algorithm doesn't reset the timer: it gets set once when the queue is empty, accumulates until it expires, then sends.

This algorithm resets the timer when the queue is empty (of data messages).  The difference is that "acks" without any pending data messages will push the delivery out, as they try their best to piggyback.   If you think this behaviour is incorrect, I can modify it not to special-case acks.

> I think we could accomplish the same thing without the extra timer by accumulating outbound messages while a "block" is being executed, then delivering them at the end.

It's not the sim-chain that I'm trying to pace, it's the ag-solo client, which has no notion of "blocks".  The `deliver` function (whether sim-chain or real chain) is called on the client-side, not the chain side.

> But we could change that: `deliver` would strictly queue the messages, and then a new function we add to the end of the simulated block cycle would process the queue. That might be cleaner.

Yes, that's how the sim-chain already works.

**Comment by warner** [comment]
Ah, I'm sorry, I didn't read it carefully enough. You're right, this only resets the timer when the queue was previously empty. That sounds like straight-up Nagle, which is fine.

And yeah, now I see the filename, this is ag-solo not sim-chain. So for ag-solo the notion of a "block" is really just the interval from some input happening (an inbound message or the timer device firing) to the run-queue becoming empty. If we know that we're going to charge ahead and process everything in the run-queue (i.e. we aren't overloaded), then we could defer sending anything until we finish draining it, at which point we know no further outbound messages will appear until there is more input. We could defined a "block" to be that set of cranks, and we wouldn't need an outbound Nagle timer. (TCP needs one because the kernel doesn't know what userspace will do next; there's no signal that says "userspace is done now").

**Comment by michaelfig** [comment]
> And yeah, now I see the filename, this is ag-solo not sim-chain. So for ag-solo the notion of a "block" is really just the interval from some input happening (an inbound message or the timer device firing) to the run-queue becoming empty. If we know that we're going to charge ahead and process everything in the run-queue (i.e. we aren't overloaded), then we could defer sending anything until we finish draining it, at which point we know no further outbound messages will appear until there is more input.

We're doing that, but some clients (notably `@agoric/captp`-based clients such as deploy scripts) send a stream of WebSocket messages.  If we process the first message, then deliver, then process the second message, then deliver, the delay between those deliveries is much smaller than the block cadence of the chain that we often send to.

The Nagle timer is to account for multiple "blocks" being processed quickly enough to bottleneck in the transaction submission process of the chain (which could easily take a few seconds).

> We could defined a "block" to be that set of cranks, and we wouldn't need an outbound Nagle timer. (TCP needs one because the kernel doesn't know what userspace will do next; there's no signal that says "userspace is done now").

We already do that, but we also don't know what "userspace" i.e. our web clients will do next.

**Comment by warner** [comment]
ah, web. Ok, yeah, that seems like a use case that doesn't give us any other signals to work with.

r+

**Review by warner — APPROVED** [review]

**Pull request merged**
