### PR TITLE
fix(marshal): serialize empty objects as data, not pass-by-reference

### PR DESCRIPTION
**Pull request by warner**
Finally change the serialization of a plain empty object, i.e. `harden({})`,
from a pass-by-reference "marker" to plain pass-by-copy data. We think we've
identified all the places where an empty object was used represent a marker,
and changed them to use `Far(iface, {})` instead, which triggers
pass-by-reference.

refs #2018

### CODE REVIEW

**Comment by warner** [comment]
@michaelfig any idea what's making this test fail? I thought we'd caught all the empty-objects-as-handle that needed changing. The specific failure (https://github.com/Agoric/agoric-sdk/pull/2622/checks?check_run_id=2093138223#step:9:1558) is in `cosmic-swingset/test/test-home.js` line 174.

**Comment by warner** [comment]
Wait, weird, I re-ran the checks and the second time it didn't fail. I'm not sure what's going on.

**Review by erights — APPROVED** [review]
LGTM whew!

**Review by michaelfig — APPROVED** [review]
LGTM!

**Review by katelynsills — APPROVED** [review]
LGTM! I think we are ready to flip the switch

**Pull request merged**
