### PR TITLE
fix: ERef<T> is T | PromiseLike<T>

### PR DESCRIPTION
**Pull request by erights**
From https://github.com/Agoric/agoric-sdk/pull/1357#discussion_r464803618

### CODE REVIEW

**Review by michaelfig — COMMENTED** [review]
`Ref` is a little vague.  Would you instead consider making it `ERef`, to designate an eventual reference?

**Review by michaelfig — APPROVED** [review]
Otherwise, LGTM!

**Comment by erights** [comment]
`ERef` it is. Thanks!

**Comment by erights** [comment]
Everything passed except one mysterious error under appveyor that clearly has nothing to do with this PR. So merging anyway.

**Pull request merged**
