### PR TITLE
fix: cosmic_swingset_inbound_queue_length is a gauge

### LINKED ISSUE #7084: inbound_queue_length marked as counter instead of gauge
## Describe the bug
```
# HELP cosmic_swingset_inbound_queue_length inbound queue length
# TYPE cosmic_swingset_inbound_queue_length counter
cosmic_swingset_inbound_queue_length 475 1677517455948
```

The metric `cosmic_swingset_inbound_queue_length` is marked as a counter and not a gauge.  It goes up and down, so it should be marked as a gauge.

Rev: 4f17b91b5952bd747c3355365056fd66805fd4f8

### PR DESCRIPTION
**Pull request by arirubinstein**
closes: #7084 

## Description

makes length a gauge

### CODE REVIEW

**Comment by mhofman** [comment]
I don't understand this change. `cosmic_swingset_inbound_queue` is already a sort of gauge, with the "length" being the current value, "add" the number of elements ever added (up), and "remove" the number of elements ever removed(down). I agree the naming seem awkward compared to other gauges type metrics, and this could probably have be integrated better in first place, but simply making "length" a gauge doesn't seem right.

**Comment by arirubinstein** [comment]
a `counter` is a number that can only go up
a `gauge` is a number that can go up and down

ref: https://prometheus.io/docs/concepts/metric_types/

Since this is misreported as a count, time series dbs like prometheus can't reason about the value of this parameter other than the number of times it has been reported.

**Comment by mhofman** [comment]
Ok. I have to admit I'm still highly confused by this kernel-stats file, and `metricsMeter`. Is this polled only? If so we'll probably never observe transient values.

cc @michaelfig

**Comment by arirubinstein** [comment]
It is polled, via prometheus to identify trends and rate of service

**Review by michaelfig — APPROVED** [review]

**Pull request merged**
