### PR TITLE
Split marshal into passStyleOf and marshal

### PR DESCRIPTION
**Pull request by erights**
Almost purely internal cleanup. 

I moved `sameValueZero` to `same-structure` package, which is the only place it is used. I don't even export it from there. I may reverse this before merging.

### CODE REVIEW

**Comment by erights** [comment]
@michaelfig when you review this, could you also let us know here what we should do to make this dapp-card-store CI error go away? Thanks.

**Review by michaelfig — APPROVED** [review]
LGTM!

I did not go over the code copying with a fine-toothed comb.  If you changed any semantics in it, I'd like to know what that was so I can check it more carefully.

**Comment by erights** [comment]
> I did not go over the code copying with a fine-toothed comb. If you changed any semantics in it, I'd like to know what that was so I can check it more carefully.

One. As the PR comment says
> I moved `sameValueZero` to `same-structure` package, which is the only place it is used. I don't even export it from there. I may reverse this before merging.

I looked again and confirmed that the only semantic change is moving `sameValueZero` from the `marshal` to the `sameStructure` package, where it is *not* exported. This is technically a breaking change, but doesn't seem to break anything because it really seems nothing is using it. But since it is technically a breaking change, I'd like your opinion on this specifically before merging. Thanks.

**Review by michaelfig — APPROVED** [review]
Yes, the sameValueZero change is fine!

**Pull request merged**
