### PR TITLE
fix(xsnap): do not leak through vat termination race

### PR DESCRIPTION
**Pull request by mhofman**
refs: #5507 

## Description

- Fixes the promise memory leak discovered through the diagnostics added in #5637

### Security Considerations

None

### Documentation Considerations

We should have some documentation for developers regarding the memory leak risks of promises.

### Testing Considerations

Tested locally with the loadgen. The snapshot does not seem to accumulate any significant program objects.

### CODE REVIEW

**Review by arirubinstein — APPROVED** [review]

**Review by dckc — COMMENTED** [review]
I started to take a look... it's more than I can look at urgently. I don't object to this going forward, though it seems to introduce significant technical-debt to re-sync endo (in place of the patch). I'd prefer to see an issue about cleaning that up.

**Comment by mhofman** [comment]
@dckc the patches will become redundant and be removed at the next endo sync. I've used this approach before to incorporate endo changes into agoric-sdk without going through a full blown version bump, and it has worked well. cc @kriskowal

**Comment by dckc** [comment]
> @dckc the patches will become redundant and be removed at the next endo sync.

Yes; I'm asking that we make an issue now for that work later.

Just like... hm... I don't see an issue for https://github.com/Agoric/agoric-sdk/pull/5576 . So maybe that's not the norm. Oh well.

**Review by turadg — APPROVED** [review]
Reviewed just the non-Endo changes since those have separate review.

This patch approach seems fine to me. It's the norm when syncing Endo deps to remove stale patches. (These will fail otherwise.)

> The snapshot does not seem to accumulate any significant program objects.

I can't tell whether this is evidence that the motivating observation is gone.

Approving because this appears to be strictly an improvement, whether it fully solves the problem or not.

**Comment by mhofman** [comment]
Ugh sorry I didn't mean to add @turadg or @dtribble as reviewers. I had a bad push which included some of master into an out of date base branch. (I assume code-owners triggered this)

**Review by warner — APPROVED** [review]
I'm not qualified to review the implementation of `racePromises` (maybe @erights or @kriskowal ?), but the use of it within `xsnap.js` looks good to me.

**Comment by mhofman** [comment]
I re-integrated the patches of endo PR that now landed, and rebased to not layer on top of the measurement work.

@kriskowal depending on how https://github.com/Agoric/agoric-sdk/pull/5576 goes, let decide whether when to merge this.

**Comment by mhofman** [comment]
@mergifyio refresh

**Pull request merged**
