### PR TITLE
Have `yarn lint-fix` run ESLint --fix before Typescript checks

### LINKED ISSUE #1745: Type check failure should not block other improvements
Many of out package.json files contain the script line

```js
 "lint-fix": "yarn lint:types&&eslint --fix '**/*.js'",
```

I suggest that this conjunction be everywhere reversed. The problem with this order is that a failure to type check blocks the fixes that eslint would do. I ran into this recently where my normal habit to reformat a program was blocked because I had not yet gotten it into a type-clean state.

### LINKED ISSUE #2419: yarn lint-fix does not reach dapp-svelte-wallet/ui
Especially after a big search replace, I rely on `yarn lint` to renormalize the source code as well as to alert me to any static lint errors I introduced. However, at 
https://github.com/Agoric/agoric-sdk/blob/667397754fc3d4db5956a340ef78b94e030a9701/packages/dapp-svelte-wallet/ui/src/display.js#L18 
we see, for example, a statement that's too wide. whereas at 
https://github.com/Agoric/agoric-sdk/blob/667397754fc3d4db5956a340ef78b94e030a9701/packages/dapp-svelte-wallet/ui/src/display.js#L20-L24
we see a statement that's too tall. Accepting suggestions in the IDE fixed them.

My primary concern though is not aesthetics. I've been using `yarn lint` to catch statically catchable problems.

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #1745

Just use `yarn lint-fix` to fix the lint (which then automatically runs extra typing checks on the results).

Also Closes #2419 by adding some linting to `@agoric/dapp-svelte-wallet-ui`.

### CODE REVIEW

**Comment by katelynsills** [comment]
Hmm, can you explain the motivation for this? I like that I can do `yarn lint-fix` and it checks everything for me, as well as fixing the eslint issues that it can

**Comment by michaelfig** [comment]
> I like that I can do `yarn lint-fix` and it checks everything for me, as well as fixing the eslint issues that it can

Ah good point.  The ideal, I think, is to have `yarn lint-fix` run `eslint --fix` first, followed by the Typescript checking.  That will accomodate @erights' complaint in #1745 (and #1747) as well as your use case.

**Comment by katelynsills** [comment]
> Ah good point. The ideal, I think, is to have `yarn lint-fix` run `eslint --fix` first, followed by the Typescript checking. That will accomodate @erights' complaint in #1745 (and #1747) as well as your use case.

Sounds good to me!

**Review by erights — COMMENTED** [review]
Are the changes to the *.js files just mechanical, or are there any I should review for content?

**Comment by michaelfig** [comment]
> Are the changes to the *.js files just mechanical, or are there any I should review for content?

Just enough of a change to pass the linter (should be no change in logic).  It's one of the parts that will need a comprehensive review someday (if we don't replace it first).

**Review by erights — APPROVED** [review]
LGTM thx!

**Pull request merged**
