### PR TITLE
DEBUGGING: instanceAdmin loses in reallocate

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
closes: #XXXX
refs: #XXXX

### CODE REVIEW

**Comment by erights** [comment]
Was this PR originally intended to solve #4383 ? #4383 is still open. Is this PR still relevant to resolving it?

**Comment by Chris-Hibbert** [comment]
I think #6302 gives the context.  What's the status of #5875?

**Comment by erights** [comment]
> I think #6302 gives the context. What's the status of #5875?

#5875 is blocked until we have adequate configurability so we can turn this on in development but off in production. We have half-implemented support for using environment variables for this https://github.com/endojs/endo/blob/master/packages/ses/src/environment-options.js , but have never made it reusable. Probably needs to be made into a separate package first.

**Comment by erights** [comment]
@Chris-Hibbert What is the status of this. Is it still relevant? Are you blocked waiting on me to review?

**Comment by Chris-Hibbert** [comment]
I'm not blocked on this for anything. If it's helpful to you in diagnosing anything related to #5875, then it's worth keeping. Otherwise, it can be closed.

**Comment by erights** [comment]
> I'm not blocked on this for anything. If it's helpful to you in diagnosing anything related to #5875, then it's worth keeping. Otherwise, it can be closed.

I don't think it'll help. If it would, I can still grab it after it's closed. Closing.

**Pull request closed without merging**
