### PR TITLE
Shutdown Old EC Charter

### LINKED ISSUE #10136: Outgoing members should not be able to propose
## What is the Problem Being Solved?

Outgoing members should not be able to propose

## Design

 - A revision to `econCommitteeCharter.js` to add a shutdown method.
   - **problematic**. See #10137 for options on shutdown design.
 - a core eval script based on `gov-replace-committee.js` (see #10105) that **upgrades the original EC contract** and calls the new shutdown method

## Test Plan

 - Unit test for the shutdown method (makeZoeForTest, startInstance, get the creatorFacet, call shutDown; then try to make an invitation to propose a parameter change)
 - Bootstrap test: test that when an outgoing member tries to propose, they get an error
 - `a3p-integration` test for upgrading the contract

## Upgrade Considerations

yes. See design, test plan.

### PR DESCRIPTION
**Pull request by rabi-siddique**
closes: #10136 

## Description
The PR will bring changes to shutdown instances of the old EC charter committee and add relevant tests. 

### Security Considerations
n/a

### Scaling Considerations
n/a

### Documentation Considerations
n/a

### Testing Considerations
n/a

### Upgrade Considerations
n/a

### CODE REVIEW

**Comment by dckc** [comment]
I trust you'll fill in the [PR template](https://github.com/Agoric/agoric-sdk/blob/master/.github/PULL_REQUEST_TEMPLATE.md) in due course. (In fact, I wonder how the section headers went away.)

In particular, I expect you'll add:

closes #10136

**Comment by rabi-siddique** [comment]
> (In fact, I wonder how the section headers went away.)

I have a weird habit of clearing templates in PR description :D I should stop doing that.

**Comment by dckc** [comment]
I gather this was closed because work on #10136 is postponed indefinitely.

**Comment by rabi-siddique** [comment]
> I gather this was closed because work on #10136 is postponed indefinitely.

Yes exactly. I should've left a comment while closing this PR

**Pull request closed without merging**
