### PR TITLE
Add governance to the list of packages to be tested in CI

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
## Description

Recent failures in CI revealed that the Governance package hadn't been added to CI. 

### Security Considerations

None 

### Documentation Considerations

we need documentation on what to do when adding a new package to agoric-sdk.

### Testing Considerations

None

### CODE REVIEW

**Review by michaelfig — COMMENTED** [review]
It looks good, but do you really want to merge this and cause all PRs' CI to fail?  I'd rather see this as part of a PR to fix the test failures.

**Comment by Chris-Hibbert** [comment]
> It looks good, but do you really want to merge this and cause all PRs' CI to fail? I'd rather see this as part of a PR to fix the test failures.

I'm working on fixing the test failures. I haven't been able to replicated the CI failures locally. (perhaps because I haven't managed to unset `LOCKDOWN_OPTIONS` yet?) 

I'll let you know when tests pass in CI.

**Review by michaelfig — COMMENTED** [review]
If you:
```
import { test } from '@agoric/swingset-vat/tools/prepare-test-env-ava.js';
```
then your test exceptions won't be censored.  With that, the old code should work.

**Review by michaelfig — APPROVED** [review]
Please consider https://github.com/Agoric/agoric-sdk/pull/4074#pullrequestreview-805388593 .

However, this PR is still good to land even if you don't want that change.  Thanks!

**Pull request merged**
