### PR TITLE
fix(swingset): don't perturb XS heap state when loading snapshot

### LINKED ISSUE #3428: taking XS snapshots causes kernel-observable GC differences, terminates vats
While running integration tests on current trunk (something close to 628ef14860aa72e4918c9d575b9669c58bbd4eae), I observed failures due to `vat-bank` being summarily executed by the kernel for an illegal syscall. @dckc and I tracked this down part-way, and we concluded that we must address the side-effects of snapshot-write operations.

In this codebase, we're running all vats (except comms) under `xs-worker-no-gc`, which uses XS like usual, but disables the force GC sweep that usually happens towards the end of each delivery. The normal `xs-worker` does:
* delivery starts
* userspace runs until the promise queue drains
* liveslots forces `gc()`
* liveslots gives finalizers a chance to run
  * if any finalizers could run liveslots emits `syscall.dropImports`/`syscall.retireImports` for the collected objects
* delivery finishes

Then, after the delivery has finished, the `vatWarehouse` decides whether or not to save a heap snapshot. The current policy makes a snapshot when `deliveryNum % 200 === 2`: after the 2nd delivery (to avoid replaying the expensive large `importBundle` that contracts do on their very first delivery), and then again every 200 deliveries (to keep the transcript, and consequent replay time, bounded to a reasonable value).

The `xs-worker-no-gc` variant does all of that except it omits the forced `gc()`. As a result, the only GC that happens is "organic": triggered by normal vat activity. In my tests, given the kind of load I was applying, I saw `vat-bank` performing one GC sweep for each 26 or 27 deliveries (`deliveryNum` of 23, 49, 76, 101), and they yielded 2/2/2/5 objects being dropped+retired.

In my test, I ran the kernel for 14 minutes (2943 cranks, 168 blocks), during which vat-bank received 124 deliveries. According to the slogfile, organic GC happened during deliveries 1, 2, 23 (drop+retire `o-54` and `o-60`), 49 (d+r `o-62` and `o-63`), 76 (`o-65` and `o-66`), and 101 (`o-68`, `o-69`, `o-70`, `o-72`, `o-73`).

Then I stopped the process and restarted it. The vat was reloaded from the snapshot taken at the 2nd delivery, then replayed the 122 post-snapshot deliveries. Unfortunately the slogfile does not record the syscalls made during replay, nor any metering numbers like `garbageCollectionCount`. 51 minutes later (at crankNum 4792, vat-bank delivery 128), vat-bank performed GC, and one of the syscalls it made during that delivery was treated as illegal by the kernel:

```json
{
  "time": 1624914008.3725057,
  "type": "deliver-result",
  "crankNum": 4792,
  "vatID": "v1",
  "deliveryNum": 128,
  "dr": [
    "error",
    "syscall.dropImports failed, prepare to die: syscall translation error: prepare to die",
    {
      "meterType": "xs-meter-8",
      "compute": 89906,
      "allocate": 42074144,
      "allocateChunksCalls": 1,
      "allocateSlotsCalls": 2,
      "garbageCollectionCount": 5,
      "mapSetAddCount": 4193,
      "mapSetRemoveCount": 149,
      "maxBucketSize": 3
    }
  ]
}
```

The kernel then terminated `vat-bank`, which causes all sorts of knock-on effects as the other vats connected to it see their result promises rejected. My load generator stopped making progress at that point, although the kernel did not panic. This test was using a one-node chain, so there were no other nodes to disagree with, but if it were a real chain, and the different nodes had different snapshot-timing policies, I think the divergence would have eventually spread to the comms messages, and that would have caused a consensus fault, evicting some of the validators. In addition, since vat-bank spends a lot of time communicating with the cosmos-sdk Bank module, divergence in the cosmos state would probably cause a consensus failure even sooner.

In trying to recover the details of the illegal syscall, I've identified a few diagnostic improvements we should make:
* The `slog()` call which records syscall details takes both the vat's original `VatSyscallObject` and the translated `KernelSyscallObject`, but if the translation fails, the syscall is not logged at all. This loses helpful information, and should be changed to record at least the `VatSyscallObject` upon a translation error.
* We record GC-related syscalls in the slog (when they succeed), which is great. We don't record them in the transcript, because we're trying to be somewhat tolerant of variations in their behavior, which is basically ok.
* We don't record any syscalls during replay, because they're supposed to be the same as in the original transcript (and if they diverge, we signal an `anachrophobia` error). But since we strip GC-related syscalls before recording the original transcript, and we ignore GC-related syscalls (for comparison purposes) during replay, we aren't recording enough information to find out about any differences.
  * We should record all syscalls during replay in the slogfile, ideally in the same format as the first time around, maybe with a flag to remind ourselves that we're in a replay and the syscalls were simulated (not actually delivered to the kernel).
  * The "do we match" syscall comparison code assumes that all GC-related syscalls were stripped from the transcript. This is generally the case for the normal kernel, but my standalone `replay-transcript.js` tool, which reconstructs transcripts from a slogfile or kernelDB, does not follow this pattern, and includes the GC syscalls in the generated transcript file. This confuses the do-we-match check.
* We should record delivery results during replay, specifically the metering results.

While using `replay-transcript.js` to try and reconstruct the timeline of the vat, I found that GC took place at different times during the (manually) reloaded vat. The organic sweeps happened on deliveries 1 (0 drops), 23 (`o-54` and `o-60`), 48 (`o-62` and `o-63`), 75 (`o-65` and `o-66`), 100 (`o-68` `o-69` `o-70` `o-72`), and 128 (`o-73` `o-75` `o-76` `o-77`). Note that the specific objects being dropped vary as well: `o-73` was dropped 28 deliveries later during the replay.

If the second run of the real kernel behaved like my `replay-transcript.js` run, where the recorded c-list tables (as of the last committed state, at delivery 124) treat `o-73` as already retired, then a `syscall.dropImports(o-73)` happening at delivery 128 would not match anything in the c-list, and the kernel would treat it as an illegal syscall. This seems like the most likely cause of the vat-bank termination I observed in the second kernel run.

## XS snapshot writes are not side-effect free

XS very specifically performs a full GC sweep [just before](https://github.com/Moddable-OpenSource/moddable/blob/decb548d0227e3536147644f24d92bbbdc20ef72/xs/sources/xsSnapshot.c#L1408) writing out a heap snapshot, probably to simplify and minimize the snapshot data (the reachability flag doesn't need to be recorded). As a result, when `vatWarehouse` decides to record a vat snapshot, it inadvertently provokes a full GC sweep. This "resets the counter" of garbage objects, which, as a side-effect, will forestall any organic GC sweeps that follow.

@dckc and I wrote [a test that compares three vats](https://github.com/Agoric/agoric-sdk/blob/78783c8a27abcedf66ab18c3a8f7931a05371cb0/packages/xsnap/test/test-xsnap.js#L339-L402), each doing an operation that creates and immediately drops a few hundred objects in a loop, and watches the metering stats to learn when organic GC sweeps happen.

* vat A just runs the loop
* vat B runs the loop a few times, then writes out a snapshot, then resumes running the loop
* vat C is loaded from that snapshot, then resumes running the loop

We observed that vats B and C ran GC at the same time, while vat A runs it earlier. This is consistent with vat B seeing a forced GC at the moment of snapshot write (deferring the need for GC for a while), and vat C starting from the post-GCed snapshotted state. And it is consistent with my `replay-transcript.js` run (which does *not* read or write any snapshots) experiencing GC earlier than the real kernel runs: `replay-transcript.js` is behaving like vat A, my first kernel run should behave like vat B, and my second kernel run should have behaved like vat C.

It doesn't yet explain the divergence between my first and second real kernel runs. Both should have seen the same forced GC at snapshot creation time, so I don't know why they apparently diverged later.

## vatWarehouse policy should be outside of consensus

_escalated to #3430_

Our intention with the vatWarehouse was that it ought to be able to take snapshots whenever it wants, without being visible to the consensus state. Two different validators should be able to use different policies (one taking snapshots quickly, the other more leisurely), and their vats should nevertheless behave identically. The fact that snapshot writes trigger GC interferes with this goal.

We can overcome this (and we must, since GC-before-snapshot is obviously the right thing to do) by doing more GC. If the consensus state of the chain would have done a GC between deliveries anyways, then the snapshot's GC won't have anything left to collect, and it becomes idempotent with the consensus-driven action.

Before we switched from `xs-worker` to `xs-worker-no-gc`, this is *almost* what we were doing. In `xs-worker`, liveslots does GC after userspace loses agency, but then proceeds to do more JS work (processing finalized vrefs, making syscalls), which builds up more garbage. The code is designed to perform more GC sweeps until they stop yielding freed userspace objects (this loop is not activated, because I don't think we need it yet, but future data structures might). When liveslots gives up control to the kernel and ends the delivery, there may still be garbage, but the quantity will be less than if userspace had been allowed to run after the liveslots `gc()`.

Then, if a snapshot is taken, the remaining garbage count drops to zero. The difference between "some" (whatever liveslots leaves around) and "zero" then determines the timing of the next organic GC operation. If enough garbage is left around, and the next delivery is busy enough, an organic sweep might happen before the end of that delivery. But it won't matter, because liveslots won't do anything with the finalizers that run until after it's done its own `gc()`.

Basically, by doing a GC at the end of each crank, and not acting upon finalizers any earlier than that, we can tolerate any extra (organic) sweeps. But if we aren't forcing that GC, we're dependent upon the organic sweeps, and that makes us vulnerable to their timing, which is influenced by the GC provoked by snapshot writes, thus making snapshot write timing part of consensus.

The solutions we've thought of:
* go back to forcing a GC in liveslots at the end of each crank
* don't do any extra GC, and include the snapshot writing schedule (vat warehouse policy) as part of consensus
* force GC on a consensus schedule, and only allow snapshot writes to happen just after these forced GC
  * e.g. do a GC after every 10 deliveries, and then give the vat warehouse policy the freedom to snapshot every 10th or 20th or 200th delivery
  * or (@dtribble will probably prefer this one), do GC on a block boundary: the kernel would accumulate the vatIDs which have had deliveries, then the host application would call some special kernel API that means "this is the end of a block, it's a great time to do cleanup and stuff before we commit a lot of state". The kernel would react by making a special delivery to all the "dirty" vats, which would force a GC sweep and emit drop/retire syscalls. After doing this, the vat warehouse has the option of snapshotting any of the dirty vats.
  * the original #1872 GC design called for a `dispatch.bringOutYourDead`, which would *return* the list of dropped objects, instead of using syscalls. This approach might be more efficient (liveslots ignores the finalizers and `deadSet` until this special crank), although the comms vat still wants spontaneous GC syscalls.
  * it's not clear whether we'd want to act upon those GC syscalls (and the `gcActions` they enqueue) immediately, during that cleanup period at the end of the block, because telling one vat that its export has been dropped might cause it to drop more objects. The worst case cascade would be some sort of distributed linked list. We probably need to bound the amount of cleanup work we do, because the whole reason we're at end-of-block is because we've exhausted our budget for doing work. We can make some guesses about how much time we'll need for GC, but in general I think we must be prepared to leave some amount of GC work unfinished, and pick it up again during the next block. (All `gcActions` are kept in a durable queue for exactly this reason).

## Consequences for the current chain

I think it's possible that we'll experience validators dropping out of consensus as a result of this problem, if what I observed between my first kernel run and my second cannot be explained by something else. I'm looking for an alternate explanation, because my conclusions here are that both runs should have seen the same forced `gc()` during the snapshot write.

My next step will be to improve the slogging to capture syscalls and `garbageCollectionCount` metrics during replay. If I can reproduce the vat-termination event with that logging enabled, I should be able to prove or disprove the theory that GC  is happening at different times during replay. If different, my next step will be to make a detailed record (using `$XSNAP_TEST_RECORD`) of the low-level messages sent to the XS process, and make sure they are identical for both the original and the reloaded vat: I'd be looking for some extra counter or timestamp or default configuration option that's different between the two, which might cause the supervisor to execute some additional code, which doesn't have any semantic effect, but causes allocation, which might modify the organic GC timing. If all the post-snapshot messages appear identical, I'll have to dig deeper.

### LINKED ISSUE #3429: XS snapshot not found during kernel reload
## Describe the bug

When restarting a local kernel, one of the vats was unable to reload from snapshot because it couldn't find the uncompressed snapshot file:

```
10:19AM INF Timed out dur=3000 height=223 module=consensus round=0 step=3
2021-06-29T17:19:03.301Z SwingSet: kernel: v15 online: xs-worker-no-gc static name=timer transcript entries replayed: 41
cannot read snapshot /home/warner/stuff/agoric/tlg2/_agstate/agoric-servers/local-chain-26657/data/ag-cosmos-chain-state/xs-snapshots/39c60159056c93c7ac82ca36cbf8d8bd07ee972491a0f064c594cd58b1beeee1-load-Ltrw9Y.xss: No such file or directory
Cannot initialize Controller Error: Cannot write messages to v12:vatAdmin: This socket has been ended by the other party
```

When I looked afterwards, the corresponding compressed file does seem to exist in that `xs-snapshots/` directory:

```
warner@turing:~/stuff/agoric/tlg2$ ls -l _agstate/agoric-servers/local-chain-26657/data/ag-cosmos-chain-state/xs-snapshots/39c6015905*
-rw-r--r-- 1 warner warner 296399 Jun 29 09:59 _agstate/agoric-servers/local-chain-26657/data/ag-cosmos-chain-state/xs-snapshots/39c60159056c93c7ac82ca36cbf8d8bd07ee972491a0f064c594cd58b1beeee1.gz
```

It launched normally when I restarted the chain process a second time.

The same thing happened to my solo node, and again a restart allows it to proceed.

I'm suspecting something involving the tempfile used for the decompressed version. Maybe we aren't waiting for the decompression to complete before giving it to `xsnap`?

### PR DESCRIPTION
**Pull request by dckc**
fixes #3428
fixes #3429

the xsnap API feature is tested a little bit, but, we have yet to...
  - create a test that creates a vat, runs it long enough to trigger a snapshot, runs it longer still to trigger GC, then stops the kernel and reloads.
    - postponed; see #3428

### validator testing?

If any validator wants to test this, it would be something like:

```
cd agoric-sdk
git fetch --all
git checkout xsnap-isready
yarn
yarn build
# then restart your validator
```

**Do not** restart your validator node with the older code. The older code had a bug with restarting (#3428).

### CODE REVIEW

**Review by FUDCo — COMMENTED** [review]
This looks fine as far as it goes, but what reason do we have to believe that `isReady` and its attendant activity won't stimulate memory allocation/GC behavior of its own that could manifest a variant of the same issue that the `evaluate` it replaces did?

**Comment by dckc** [comment]
> ... what reason do we have to believe that `isReady` and its attendant activity won't stimulate memory allocation/GC behavior of its own ...?

It doesn't touch the XS engine in any way. It may allocate in the C heap to do `snprintf` and such, but it doesn't touch the XS JS heap.

But it's a fair question, and my reply is a testable claim, so we're adding a test. f447454ca

**Comment by FUDCo** [comment]
Ah, the fact that the workers are independent processes with their own heaps is a subtlety I keep forgetting.  That makes total sense.

**Review by FUDCo — APPROVED** [review]
YOLO

**Comment by dckc** [comment]
I rebased this on `agorictest-15`. I'm not quite sure how this works... @michaelfig does this seem right?

**Review by warner — APPROVED** [review]
looks good to me too, thanks for the test

**Comment by dckc** [comment]
@michaelfig did you add those balance sorting go changes to `xsnap-isready` on purpose? I guess I expected to use `agorictest-15-p1` for changes other than the `isReady()` stuff.

I suppose it doesn't matter much. Is this PR still relevant? Should I close it? I'll leave it in your hands, I guess.

**Comment by michaelfig** [comment]
> @michaelfig did you add those balance sorting go changes to `xsnap-isready` on purpose? I guess I expected to use `agorictest-15-p1` for changes other than the `isReady()` stuff.

I wanted to be sure to merge the sorting changes on top of your changes, whether before or after this PR was merged.  But now, let's merge this PR to `agorictest-15-p1`!

**Pull request merged**
