### PR TITLE
fix(notifier): add Far/Data to notifier

### PR DESCRIPTION
**Pull request by warner**
This pulls in a subset of the changes from #2545 , which seemed easier than
iterating on that branch or applying more fixes on top. Thanks @katelynsills
for the cleanup!

### CODE REVIEW

**Review by katelynsills — APPROVED** [review]
LGTM!

**Comment by erights** [comment]
Also subscription. It isn't in use yet only because of our inability to pass `Symbol.asyncIterator` through the SwingSet kernel.

**Review by erights — CHANGES_REQUESTED** [review]
Also subscription. It isn't in use yet only because of our inability to pass Symbol.asyncIterator through the SwingSet kernel.

**Review by erights — CHANGES_REQUESTED** [review]
LGTM, thanks

**Review by erights — APPROVED** [review]

**Pull request merged**
