### PR TITLE
Draft: highlight where constant product differs from v1 and find out why

### PR DESCRIPTION
**Pull request by katelynsills**
refs: #3716 (original constant product code with tests)
refs: #3771 (constant product code that got merged)

## Description

This draft PR is to set up tests so that we can do a direct comparison of the constant product code and Uniswap v1. We're assuming that if the protocolFee is 0 and the price is not being "improved" or "reduced", the results should be the same. I'm getting different results. The file to look at is packages/zoe/test/unitTests/contracts/constantProduct/test-v1.js. I highlighted a particular test with `test.only`, but the other tests are failing too.

### CODE REVIEW

**Comment by katelynsills** [comment]
@dckc and @Chris-Hibbert, here's the differences I was seeing

**Comment by Chris-Hibbert** [comment]
> We're assuming that if the protocolFee is 0 and the price is not being "improved" or "reduced", the results should be the same.

@katelynsills  thinks the answers should be the same. I think they might be the same (in at least some cases, like `getInputPrice` vs. `getOutputPrice`), and it would be interesting to understand why they're different.

**Comment by katelynsills** [comment]
> @katelynsills thinks the answers should be the same. I think they might be the same (in at least some cases, like `getInputPrice` vs. `getOutputPrice`), and it would be interesting to understand why they're different.

Good point, I forgot we had talked about that.

**Comment by dckc** [comment]
FWIW, I reproduced the results in [a spreadsheet](https://docs.google.com/spreadsheets/d/1HBJ8z8x5hTagJ5PGqBhNpeuvNaYb1q9U9kPOR8-exKo/edit?usp=sharing)

as well as with `yarn test`.

**Comment by dckc** [comment]
oh... I didn't undo the "improved" stuff in my spreadsheet.

**Comment by Chris-Hibbert** [comment]
This code was all removed long ago.

**Pull request closed without merging**
