### PR TITLE
Propagate makeContract exceptions

### PR DESCRIPTION
**Pull request by michaelfig**
It is necessary to wrap the makeContract call within a .then callback
or else synchronous exceptions in it are not converted to a
rejected promise.

### CODE REVIEW

**Review by katelynsills — APPROVED** [review]
I hadn't realized this - thanks for bringing it up! Is there more I can read on this? 

Looks good to me, but I am also asking for a review from Mark because this is core infrastructure.

**Comment by katelynsills** [comment]
I was trying to replicate this in the Node REPL and it looks like both approaches are treated the same. What am I missing?

Screen Shot 2020-03-18 at 2 03 23 PM

**Comment by michaelfig** [comment]
> I was trying to replicate this in the Node REPL and it looks like both approaches are treated the same. What am I missing?

It's different: try `Promise.resolve().then(_ => fn())`.  You want to invoke the function only when the `then` is resolved.  Doing `Promise.resolve().then(fn())` invokes `fn()` in the same turn and passes its return value as `.then(returnValueOfFn)`.

Since `fn()` throws an exception, the exception is thrown right after the `Promise.resolve()` call, ,and not in a new turn.

**Comment by katelynsills** [comment]
> > I was trying to replicate this in the Node REPL and it looks like both approaches are treated the same. What am I missing?
> 
> It's different: try `Promise.resolve().then(() => fn())`. You want to invoke the function only when the `then` is resolved. Doing `Promise.resolve().then(fn())` invokes `fn()` and passes its return value as `.then(returnValueOfFn)`.

Thanks so much! That was very clear

**Review by erights — CHANGES_REQUESTED** [review]
The changes to assert.js and throwsAndLogs.js do not LGTM. The rest do. I don't see any dependence of that rest on these. If you can submit with PR without the changes to assert and throwsAndLogs, it will LGTM.

**Comment by michaelfig** [comment]
> The changes to assert.js and throwsAndLogs.js do not LGTM. The rest do. I don't see any dependence of that rest on these. If you can submit with PR without the changes to assert and throwsAndLogs, it will LGTM.

Thanks for the review.  I've removed that part of the PR.

**Review by erights — APPROVED** [review]
LGTM

**Pull request merged**
