### PR TITLE
fix(run-protocol): restore wrapLienedAmount on AttestationTool

### PR DESCRIPTION
**Pull request by turadg**
## Description

Solving https://github.com/Agoric/agoric-sdk/pull/5186#issuecomment-1107069676

That had been added in https://github.com/Agoric/agoric-sdk/pull/5094

### Security Considerations

No new.

### Documentation Considerations

--

### Testing Considerations

There should be a test for the feature that was added in https://github.com/Agoric/agoric-sdk/pull/5094 . I'd like to hold off on merging this until we have a regression test but if it's urgent @samsiegart okay with me to merge.

### CODE REVIEW

**Comment by dckc** [comment]
the dapp can do its own wrapping / unwrapping

this feature should probably go in something like `params.js` that clients can use without grabbing the whole contract

it was just convenient to have them close over the relevant brands

**Comment by dckc** [comment]
@turadg you assigned @samsiegart but didn't make him a reviewer.

(several folks around here tend to assign themselves on PRs they author)

**Comment by turadg** [comment]
> @turadg you assigned @samsiegart but didn't make him a reviewer.

A user input error. I’ve corrected it, though I assume anyone who wants to review would review, including Sam since he reported the problem.

> (several folks around here tend to assign themselves on PRs they author)

That makes sense to me if reassigning the PR to someone else,. The 95% case is that the author is the assignee so clicking that seems like busywork. We don’t use it for reporting.

> the dapp can do its own wrapping / unwrapping
> this feature should probably go in something like params.js that clients can use without grabbing the whole contract

SGTM.l @samsiegart will that work for you?

**Review by dckc — APPROVED** [review]
I also prefer to have a regression test, but if this becomes urgent, feel free to merge it.

**Review by samsiegart — APPROVED** [review]

**Pull request merged**
