### PR TITLE
refactor(SwingSet): convert `run-utils.ts` to JS

### PR DESCRIPTION
**Pull request by michaelfig**
## Description

So that SwingSet remains a "Just Javascript" package, convert `tools/run-utils.ts` from Typescript to Javascript.

Best reviewed without whitespace changes.

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

n/a

### Upgrade Considerations

n/a

### CODE REVIEW

**Review by turadg — APPROVED** [review]
I think it's harder to read now but worth it on balance for keeping this package just .js.

**Review by dckc — APPROVED** [review]
I wondered whether the main SwingSet maintainers were aware that some .ts got in to the package. Some spelunking shows it was don in 699d9e1 , which was written by Chip and reviewed by warner. So I'm a little ambivalent about this change.

I'm still don't have enough experience to be comfortable with typescript beyond .d.ts files, so I guess I'm happy in that sense.

**Comment by dckc** [comment]
I'm a little surprised that there are no changes to `package.json` to turn off `tsx` tooling. I suppose those settings are global to the monorepo?

**Comment by turadg** [comment]
> little surprised that there are no changes to package.json to turn off tsx tooling

This file was imported in exactly two places (packages/boot and packages/benchmark), and they both still need the tsx loader.

**Pull request merged**
