### PR TITLE
Remove .jsonlines hack from simple swing store

### PR DESCRIPTION
**Pull request by FUDCo**
This commit changes no files but attempts to introduce a commit comment that attempts to prod the lerna/conventional commits machinery into attempting to introduce a major version number increment.  Third attempt.

### CODE REVIEW

**Comment by michaelfig** [comment]
> This commit changes no files but attempts to introduce a commit comment that attempts to prod the lerna/conventional commits machinery into attempting to introduce a major version number increment. Third attempt.

You need to have your commit change a file under `packages/swing-store-simple` or else lerna can't figure out which package's version you mean.

**Comment by FUDCo** [comment]
> > This commit changes no files but attempts to introduce a commit comment that attempts to prod the lerna/conventional commits machinery into attempting to introduce a major version number increment. Third attempt.
> 
> You need to have your commit change a file under `packages/swing-store-simple` or else lerna can't figure out which package's version you mean.

That's why I asked if it was sufficient to just change the commit comment.

For something that's supposed to work automatically, the conventional commits thing seems awfully brittle.

I think I have reached my frustration limit on this.  Can I hand this off to you?

**Comment by michaelfig** [comment]
> That's why I asked if it was sufficient to just change the commit comment.

Ah, I should have given my answer the context of: "Yes, if that commit changes a file in the package you're trying to affect."

> I think I have reached my frustration limit on this. Can I hand this off to you?

Sure, I'll shepherd this one through.

**Review by kriskowal — APPROVED** [review]
The bits of the commit look right.

**Pull request merged**
