### PR TITLE
fix(agops): fix continuing id lookup in oracle setPrice

### LINKED ISSUE #8281: Unable to use setPrice in CLI to reliably change ATOM and stATOM price (for testing)
## Describe the bug

Product rely on CLI commands on testnets in order to test core vaults user flows such as liquidations - this requires us to be able to change the price on demand to trigger liquidations.

setPrice is a function that allows this but has not been reliable (or is broken since adding second collateral type - @dckc please add accurate details).

## To Reproduce
1. Open CLI terminal for on Ollinet with latest Agoric SDK etc.
2. Attempt to change price of an asset with for example 'agops oracle setPrice --keys gov1,gov2 --pair stATOM.USD --price 7.7 --keyring-backend test'
3. Monitor in Vaults UI (or elsewhere) if price change (it does not reliably do so)

## Expected behavior
The price of should change to 7.7 for stATOM in this case.

### PR DESCRIPTION
**Pull request by dckc**
needs instance based on --pair

closes: #8281
refs: #XXXX

### Testing Considerations

 - [ ] IOU a test

### CODE REVIEW

**Comment by dckc** [comment]
cc @0xpatrickdev

**Comment by dckc** [comment]
I looked into doing a test. Threading IO capabilities explicitly looks like more trouble than it's worth (#2160).

How about landing this as is?

**Review by turadg — APPROVED** [review]
> Threading IO capabilities explicitly looks like more trouble than it's worth.

It would be fine to use ambient IO capabilities for a test.

> I looked into doing a test.

A test would be nice but since this is an internal tool, if you've tested it manually that suffices for me.

**Comment by dckc** [comment]
> It would be fine to use ambient IO capabilities for a test.

Hm. It would go out to the network and such then, right? I would need to run a blockchain node or something.
The idea was to mock what it would find out in the world.

Alternatively, I could factor out the part that I fixed and unit test that, but again, it's kind of a pain.

**Comment by turadg** [comment]
> The idea was to mock what it would find out in the world.

Yeah, I was assuming we could mock module imports. That's built into Jest. In Ava it would take something like https://github.com/iambumblehead/esmock

**Comment by dckc** [comment]
> ... mock module imports ...

Yeah, that's another approach. I didn't look into it. Does it make a test seem more cost-effective?

**Comment by turadg** [comment]
More but not enough imo. Also using esmock-loader precludes using tsx-loader.

**Pull request merged**
