### PR TITLE
Wallet connection component

### PR DESCRIPTION
**Pull request by michaelfig**
This is an `<agoric-wallet-connection>` Web Component for dapps to use to enable connecting with the Agoric wallet backend.

We expect our dapps will usually be written in React, but this component allows cross-framework portability.

### CODE REVIEW

**Review by samsiegart — APPROVED** [review]
I rebased and pushed to this branch. Then I tested it on the react wallet and it seemed to work great! There's perhaps some tweaks I could make to the docs (around lockdown stuff particularly) but maybe we can merge this and follow up with that?

**Comment by michaelfig** [comment]
>  maybe we can merge this and follow up with that?

Yes, that's a good idea.  I'll update this branch one more time and merge it.

Once this is merged, we can work in parallel on different features.  To help unblock you, I plan on doing some code to get the wallet admin facet, given an accessToken.

Also, it would be nice to adjust the state machine to time out the iframe connection if there's no response, since we have no other way to detect when the connection has failed.

**Comment by dckc** [comment]
nifty!

Thanks for the reminder about `lit`.
`robot3` looks cool too.

**Comment by dckc** [comment]
I'm trying this out in https://github.com/dckc/gov-demo1 using...

```
yarn add https://gitpkg.now.sh/Agoric/agoric-sdk/packages/wallet-connection
```

**Pull request merged**
