### PR TITLE
Propagate agoric-cli chain config to testnet

### PR DESCRIPTION
**Pull request by michaelfig**
Refs #1238 

Ensure our testnet chains use the same basic config (`genesis.json` and `config.toml`) as the local chain.

We also add some more support for doing upgrades.  This doesn't yet work on the testnet (it prints an error and exits, since it is unimplemented), but it still does locally (as per #1183).

### CODE REVIEW

**Review by FUDCo — APPROVED** [review]
Subject to the strong caveat that I haven't deeply immersed myself in the problem space and so there are almost certainly things going on here that I don't understand, intuitively it feels like we're employing considerably more mechanism here than the underlying problem would seem to demand.  In particular, I'm instinctively suspicious of the TOML and json-merge-patch stuff -- is this something we need for compatibility with Cosmos or is this machinery of our choosing?

That said, I trust your expertise more than I trust my own gut on this (and in any case the above concerns aren't a reason to block you), so I'm approving.

**Comment by michaelfig** [comment]
@FUDCo, I'll remove the json-merge-patch dep now that it's isolated (and it's not ses-compatible).  Just had wishful thinking to make declarative changes.

**Review by warner — APPROVED** [review]
I'm similarly in the dark about how our provisioning/deployment code works, but nothing here jumps out at me as wrong. LGTM.

**Comment by michaelfig** [comment]
> @FUDCo, I'll remove the json-merge-patch dep now that it's isolated (and it's not ses-compatible). Just had wishful thinking to make declarative changes.

I did this but needed to keep the TOML parsing/unparsing since that's the file format of the `config.toml` that I want to modify.

**Pull request merged**
