### PR TITLE
feat(zoe/contracts): Support first-price auction, fix wakeup timer in current contract

### PR DESCRIPTION
**Pull request by simpletrontdip**
refs: https://github.com/Agoric/dapp-card-store/pull/40

## Description

While building NFT auction capability for card-store, I've added `first-price` auction logic based on **Zoe**'s current one. Although the above PR gets approved, @katelynsills suggested that we bring these changes to **Zoe** to benefit us all and avoid duplicating code.

So this PR addresses 2 things:
- Add first price-auction logic to based on existing one
- Refine `wakeup` logic to start at the first bid, not at the contract creation

### Security Considerations

N/A

### Documentation Considerations
- We may need to update the documentation page for `secondPriceAuction` to reflect these changes

### Testing Considerations
- New tests for first-price logic is added
- Existing tests are updated to check the `wakeup` logic

### CODE REVIEW

**Review by katelynsills — APPROVED** [review]
LGTM! Thank you!

**Comment by katelynsills** [comment]
I'm seeing a failure in https://github.com/Agoric/agoric-sdk/runs/4156521250?check_suite_focus=true. I'll try to replicate this locally in `packages/zoe` with `yarn test` later today and see if I can identify the problem.

**Comment by katelynsills** [comment]
Hi @simpletrontdip, I was able to identify what was failing. Can you add this commit to your branch? https://github.com/Agoric/agoric-sdk/commit/1d5c00340ef8bce0081e8ff596ff4e03f1f9ba12

**Comment by simpletrontdip** [comment]
@katelynsills updated 👯 👯 👯

**Pull request merged**
