### PR TITLE
Publish wallet.agoric.app

### PR DESCRIPTION
**Pull request by michaelfig**
Not ready for review.

### CODE REVIEW

**Comment by dckc** [comment]
Is this PR still relevant, @michaelfig ?

https://wallet.agoric.app/ is published... though I'm not sure we have spread the knowledge about how it works around.

**Comment by michaelfig** [comment]
> Is this PR still relevant, @michaelfig ?

Still relevant.  I hope to land sometime when it's up-to-date.

> https://wallet.agoric.app/ is published... though I'm not sure we have spread the knowledge about how it works around.

I'd like to transfer this site to @samsiegart.  Let's talk about doing that sometime when we're discussing wallet stuff.

**Comment by samsiegart** [comment]
> I'd like to transfer this site to @samsiegart. Let's talk about doing that sometime when we're discussing wallet stuff.

ACK, feel free to drop a calendar invite whenever you have the chance.

**Comment by michaelfig** [comment]
This is now https://github.com/Agoric/wallet-app

**Pull request closed without merging**
