### PR TITLE
rc2 changes

### PR DESCRIPTION
**Pull request by turadg**
## Description

https://github.com/Agoric/agoric-sdk/releases/tag/mainnet1B-rc1 was released last week. We're going to cut an rc2. This PR brings over all the master commits that we want to include in the release. 

(Note that the branch name this PR is bound to erronously says `rc3`, because I fat fingered naming the branch and noticed it too late)

### Testing Considerations

Review the commits and make sure they match the release plan.

- [ ] https://github.com/Agoric/agoric-sdk/issues/7791
- [ ] https://github.com/Agoric/agoric-sdk/issues/7799
- [ ] https://github.com/Agoric/agoric-sdk/issues/7806
- [ ] https://github.com/Agoric/agoric-sdk/issues/7837
- [ ] https://github.com/Agoric/agoric-sdk/issues/7842
- [ ] https://github.com/Agoric/agoric-sdk/issues/7844
- [ ] https://github.com/Agoric/agoric-sdk/issues/7848
- [ ] https://github.com/Agoric/agoric-sdk/issues/7850
- [ ] https://github.com/Agoric/agoric-sdk/issues/7851
- [ ] https://github.com/Agoric/agoric-sdk/pull/7573

Is there anything in master that's not safe for release?

### CODE REVIEW

**Review by Chris-Hibbert — CHANGES_REQUESTED** [review]
I don't see #7854 here. Am I missing something?

**Comment by turadg** [comment]
> I don't see #7854 here. Am I missing something?

No, that just wasn't in master the last time this was updated. This is in draft and won't be marked R4R until all the RC2 changes are in master and in this branch.

**Comment by Chris-Hibbert** [comment]
#7868 has also been merged now.

**Comment by Chris-Hibbert** [comment]
> No, that just wasn't in master the last time this was updated. This is in draft and won't be marked R4R until all the RC2 changes are in master and in this branch.

That's what I was missing. Thanks for clarifying!

**Comment by turadg** [comment]
| issue | PR in this branch during review
| ----- | ------- | 
| #7791 | #7804, #7857   |
| #7799 | #7868        |
| #7806 | #7827        |
| #7837 | #7827        |
| #7842 | #7854        |
| #7844 | #7845        |
| #7848 | #7861        |
| #7850 | #7863        |
| #7851 | #7859 (via #7827)        |

Additional not in test plan list:
- https://github.com/Agoric/agoric-sdk/pull/7813
- https://github.com/Agoric/agoric-sdk/pull/7840
- https://github.com/Agoric/agoric-sdk/pull/7843
- https://github.com/Agoric/agoric-sdk/pull/7573
- https://github.com/Agoric/agoric-sdk/pull/7866

**Review by Chris-Hibbert — APPROVED** [review]

**Review by ivanlei — APPROVED** [review]
Every issue and PR matches what's expected for this release. Nothing more or less.

**Pull request merged**
