### PR TITLE
feat: getBrandInfo() to support orcUtils.makeOsmosisSwap() (WIP)

### PR DESCRIPTION
**Pull request by dckc**
refs:
 - #9211 
 - #8863

## Description

`getBrandInfo()` is synchronous in the [Orchestrator](https://agoric-sdk.pages.dev/interfaces/_agoric_orchestration.Orchestrator) API. This is a bunch of hack-and-slash to try to meet that constraint while I figure out whether it's negotiable (@dtribble ).

`makeOsmosisSwap()` is also sync and doesn't even take an `Orchestrator` arg. Before I even try to do that, I'd like to talk this over with @turadg and @0xpatrickdev 

DRAFT until
 - [ ] various kludges

### CODE REVIEW

**Comment by dckc** [comment]
@turadg a bunch of this has landed by way of other PRs, yes?

@mitdralla I'd still like to talk this over with you; was hoping to do it in person around [Chain Abstraction Day](https://lu.ma/ChADay_EthCC2024) but didn't manage.
cc @Jovonni

**Comment by turadg** [comment]
> @turadg a bunch of this has landed by way of other PRs, yes?

Yep. At this point it might be better to use it to inform some fresh commits on top of master

**Comment by dckc** [comment]
obsolete. #9754 covers `getBrandInfo()`.

`makeOsmosisSwap()` remains TODO.

**Comment by dckc** [comment]
for some follow-up, see:
 - #9814

**Pull request closed without merging**
