### PR TITLE
feat: elected committee

### LINKED ISSUE #6485: Agoric governance: Open Electorate Created by Public Vote
## Description
Create an Agoric governance component using a new ElectionType that instantiates a public vote to give voting facets to the election winners. There should be a public registration of the identities of the candidates to make them visible.

This bounty focuses on creating the committee that will be elected and includes a charter to control the manner of their election and operation. Our existing committee is elected only once, and the membership can't be updated. The biggest open issues are refreshing the membership, and controlling the ability to create new votes.

Possible approaches to membership include replacing members who have become unresponsive, scheduling periodic elections, or supporting recalls. There are several plausible ways to limit the ability to open new questions: a chair or subcommittee, require approval from some subset of the members, or requiring a payment or deposit.

This bounty shouldn't include any work on those who vote to elect this committee. Internally, those processes are currently under review.

## Context
Currently, voters only get a voting facet via an invitation. The electors vote to choose a committee, and the committee members then get the ability to vote. The voters can reliably identify the Electorate by subscribing to get a list of new questions. Voters can use the questionHandle from each update from the subscription to get the questionDetails. They cast their vote by sending their selected position(s) to their electorate, which they know and trust.

We want everyone to be able to identify the candidates and winners. Anyone who knows the electorate can get a list of questions, so this includes both the original electorate and the elected committee members for the original election, and then the committee itself will be well-known, and so both the public and the committee members can find out what questions the committee is voting on.

This structure of Electorates and VoteCounters allows voters and observers to verify how votes will be counted, and who can vote on them, but doesn't constrain the process of creating questions. We now have a PSMCharter and EconCommittee Charter, that control aspects of creating questions that those committees can vote on. A charter or electionManager can control the voting threshold, the vote closing time, or the range of parameter values that can be specified.

## Acceptance Criteria
A successful bounty will:
* Complete the requirements from the description including reasonable edge cases not explicitly defined
* Pass code review from Agoric team
* Include documented open source code and walkthrough presentation

## Time Estimation
About One Week

## Reward
$3200

Payment will be made in USD (fiat currency) via wire transfer. The developer is responsible for providing their completed tax documents (W9 for US based developers and/or W8 or W8-BEN-E for non-US based developers) and providing their banking details in order to receive payment. 

## Applicant Assessment Criteria
Important: Please provide a clear work plan for how you will approach this bounty.  Use the work plan as an initial demonstration that you would be a good candidate.  Bounties will require coordination with the Agoric team, so unfortunately only plans submitted in English will be considered.

Applicants will be assessed based on the following criteria: 
* Issue-specific domain experience
* Issue-specific technical capability
* Familiarity with Agoric's platform
* JavaScript experience
* Availability and communication

## Experience Write-up (1000-1500 words)
As part of completing the bounty, we ask that you write up a short summary of your experience building on Agoric. Write-up should include:
* Begin with a compelling, relevant introductory hook statement (<50 words). 
* Clearly explain the specific bounty project (~100 words). 
* Describe how the developer approached the problem (~300 words). 
* Give a step-by-step description of the solution (>500 words && <1000 words).
* At least three code snippets per write-up. They do not count toward overall word count. 
* Conclude with clear calls to action on developing with Agoric - specifically how any ambition developer reading this piece could do more themselves (>150 words). 

This is important feedback for us as we evolve the platform.

## Review Process
* Agoric team reviews your submitted work plan on Gitcoin.
* It is best to join our Discord and post your Gitcoin name in the bounties channel, so that we can follow up with you. Otherwise, we will write on your Gitcoin profile wall and say hello!
* Agoric contacts you to provide reference projects / sample code for engineering review.
* Introductory call to discuss your plans and expected timeline.
* Join the Agoric Discord bounties channel (if you haven’t done so already).
* Agoric accepts you on Gitcoin and you get started!

## References
* [Agoric Documentation](https://docs.agoric.com/)
* [Agoric Governance Doc](https://github.com/Agoric/agoric-sdk/tree/master/packages/governance)
* [#bounties channel in Discord](https://discord.com/channels/585576150827532298/854426485900967988) for general questions and your private bounty channel for direct questions to the Agoric team

### PR DESCRIPTION
**Pull request by mul53**
closes: #6485 

## Description
Adds a governance component that creates a committee that will be elected

### CODE REVIEW

**Comment by mul53** [comment]
hey @Chris-Hibbert this is a draft, let me know if it's the right direction

**Comment by mul53** [comment]
hey @Chris-Hibbert, are you available to review this?

**Comment by Chris-Hibbert** [comment]
The two components I'm expecting to see are a new committee and a charter for it.

The committee would allow replacing some or all of the members, and know how to send out new invitations to distribute the new voting rights. 

The Charter would control the ability to call for votes so the following would be possible 
 * replace a single member
 * determine that there would be periodic (perhaps annual) elections for all the members
 * specify whether only one member (a "chairman") could call for votes, or any committee member could, or any member of the public who puts up a sufficient bond could.
 * when holding periodic elections, accept nominations for slates of candidates, and make the question sufficiently legible that voters can tell who is included in each slate.

I don't believe there's any need for a new ballot counter. The one from #6515 should be sufficient.

Once the new code has been written, duplicate code with any of the existing governance code should be factored out to a common place.

**Comment by mul53** [comment]
@Chris-Hibbert still working on this, was out of office, i have a few questions.

Will the charter act like the contractGovenor in this instance?

Okay i have added a `addElection` method in the committee which returns the outcome for the election, we store a list of addresses in the committee and we expose methods for the charter to use to modify the committee `addCommitteeMember` and `replaceCommitteMember`

And for the distribution i have added the method `getCommitteeMemberInvitations` which the charter uses to distribute the invitations.

In the charter, plan on adding `voteOnCommittee` and `voteOnCommiteeMemberReplacement`

is that ideal?

**Comment by dckc** [comment]
> Will the charter act like the contractGovenor in this instance?

No; it plays the role of an election manager (see [governance core architecture diagram](https://github.com/Agoric/agoric-sdk/blob/master/packages/governance/docs/index.md#corearchitecturepng)). One existing precedent is [econCommitteeCharter.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/econCommitteeCharter.js)

**Comment by dckc** [comment]
one possible scenario...

We're electing a 9 member executive board, so we start a Book club member-level charter contract to do that.

Valencia, V2, V3, V4, V5, V30 are the voters (a book club, say); they have invitations to the member-level charter.

Valencia nominates Charles (at address c) by exercising her invitation and calling some method on the offer result.
Likewise 12 other nominates.
We have 12 nominees when a timer for nominations expires and the member-level charter puts a question to itself to decide who is on the committee.

Each member can vote for up to 9 nominees (identified by addresses).
The ballot counter (launched when the above question was put) figures out the winners.

Then something like [distributeInvitation](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/proposals/committee-proposal.js#L26) to the 9 people (by address).

## Replacing a member.

Doug stops attending meetings, which makes the board less effective. Eric puts a question to vacate his seat. A super-majority of the executive board concurs, and they choose a replacement...

**Pull request closed without merging**
