### PR TITLE
Add autoswap-frontend/wallet-frontend to monorepo

### PR DESCRIPTION
**Pull request by warner**
This merges the history of https://github.com/Agoric/autoswap-frontend and https://github.com/Agoric/wallet-frontend , moved into subdirectories, into the main agoric-sdk monorepo. They've been added to the workspaces defined in the top-level `package.json`.

They aren't yet integrated into e.g. `agoric-cli`, nor is any CI set up.

refs #452

### CODE REVIEW

**Comment by warner** [comment]
@michaelfig I changed the `name:` in `packages/autoswap-frontend/package.json` to avoid a conflict with `packages/agoric-cli/template/ui` (which also calls itself `autoswap-frontend`). How should we resolve this? Does the `template/ui` directory go away in favor of the newly-incorporated `autoswap-frontend` package? I know those two directories have different contents, so maybe we also need to merge the contents together into `packages/autoswap-frontend/`?

**Review by katelynsills — APPROVED** [review]
This looks good to me. Is there a place we can explain about the `autoswap-frontend-2` and why that exists? Maybe a checklist in https://github.com/Agoric/agoric-sdk/issues/452?

**Comment by warner** [comment]
when this lands, I'll create tags for `wallet-frontend-v0.1.0` and `wallet-frontend-v0.1.1`, and I'll see if I can move any Issues over.

`autoswap-frontend` didn't have any tags.

**Comment by katelynsills** [comment]
> This looks good to me. Is there a place we can explain about the `autoswap-frontend-2` and why that exists? Maybe a checklist in #452?

Whoops, just saw your comment above

**Comment by michaelfig** [comment]
I'd suggest `agoric-dapp-ui` for the ui directory, and we'll work out the integration later.

**Comment by warner** [comment]
@michaelfig I pushed a commit: does that do what you're recommending?

BTW, when I run `yarn test` locally, at least one frontend directory stops the test process to ask me a question about what tests I want to run. I don't know if this happens only when there's a TTY connected, or if CI will get stuck waiting for human input, but we need to track it down and make sure that `yarn test` is non-interactive.

**Comment by warner** [comment]
Ok, CI just finished normally, so if there's something interactive happening, it's only happening when there's a console attached. That'd still be a blocker for landing this: I don't want people's `yarn test` workflow being interrupted.

Could one of you pull down this branch, do a `yarn install; yarn build; yarn test`, and see if it waits for user input for you too?

**Comment by michaelfig** [comment]
Hai!

We can rename "test" to "test:interactive" and create a dummy `"test": "exit 0"` package.json entry.

**Comment by michaelfig** [comment]
CI doesn't test every package.

**Comment by warner** [comment]
Ah, got it: a top-level `yarn test` *does* exercise the new packages (with their wait-for-user-input behavior), but CI is not using that: I made it run each package separately so I could see the results split out. That's why CI still works.

**Pull request merged**
