### PR TITLE
Upgrade to ses 0.12.2 release

### PR DESCRIPTION
**Pull request by erights**
Inherit all the recent debugging goodness!

### CODE REVIEW

**Comment by dckc** [comment]
fixes #2263

**Comment by dckc** [comment]
@erights I suspect we need a release of ses that includes https://github.com/Agoric/SES-shim/pull/571

**Comment by erights** [comment]
> @erights I suspect we need a release of ses that includes [Agoric/SES-shim#571](https://github.com/Agoric/SES-shim/pull/571)

ok

**Comment by erights** [comment]
@dckc If you haven't started cutting that new release, hold off a moment. There's one more small change I'd like to get in.

**Comment by erights** [comment]
> @dckc If you haven't started cutting that new release, hold off a moment. There's one more small change I'd like to get in.

For the record, that was https://github.com/Agoric/SES-shim/pull/572 , now merged.

**Comment by dckc** [comment]
xsnap seems to get along with 0.12.2

**Comment by erights** [comment]
@dckc @michaelfig Ready for review.

@michaelfig I think you'll be amused why I had to fix your fix to the bundle test ;)

**Review by michaelfig — APPROVED** [review]
LGTM!  It was amusing.

**Pull request merged**
