### PR TITLE
fix: ensure script main rejections exit with error

### PR DESCRIPTION
**Pull request by michaelfig**
## Description

Many scripts in the SDK exit successfully (status=0) even if their async main functions return a rejection.  This masks actual problems and makes it hard to find where scripts have gone off the rails.

Change them so that they exit with an error status code (nonzero status) on rejection.

### CODE REVIEW

**Review by kriskowal — APPROVED** [review]
Great progress.

Bradley Farias recently recommended a slightly different idiom to hedge against the possibility that the catch isn’t even reached. I’m not sure what circumstance would cause this, but I like failing closed.

```js
process.exitCode = 1;
run().then(() => {
  process.exitCode = 0;
}, err => {
  console.error('Failed with', err);
  process.exit(process.exitCode || 1);
});
```

**Comment by michaelfig** [comment]
> Bradley Farias recently recommended a slightly different idiom to hedge against the possibility that the catch isn’t even reached. I’m not sure what circumstance would cause this, but I like failing closed.

Thanks for this.  The situation I can see exiting silently with success if `run` calls `process.exit()`.

**Comment by kriskowal** [comment]
This is enough ceremony that it might be good to put a micro package in `@endo/run` for running main funcs. This is something I’m meaning to get around to.

**Comment by michaelfig** [comment]
> This is enough ceremony that it might be good to put a micro package in `@endo/run` for running main funcs. This is something I’m meaning to get around to.

I also have an old PR with an `endo-exec` runner that would run the `export const main` entry point (after locking down).  That way scripts don't need to side-effect the world upon import.

**Pull request merged**
