### PR TITLE
Cherry-pick CI improvements to release branch

### PR DESCRIPTION
**Pull request by mhofman**
refs: #XXXX

## Description

Cherry picks all commits necessary from master in order to bring CI in the release branch to parity.

Because some changes had already been partially picked, a decent amount of conflict resolution was necessary. A few changes were left behind as not applicable to the release branch.

Performed with the following rebase-todo:
```

# From pull request 7870
pick 377de7402 ci(restore-golang): avoid double-caching

# Branch Agoric-mfig-periodic-endo
label base-Agoric-mfig-periodic-endo
pick 45505c53a ci: schedule nightly test against Endo master
label Agoric-mfig-periodic-endo
reset base-Agoric-mfig-periodic-endo
merge -C 20433496e Agoric-mfig-periodic-endo # Merge pull request #7887 from Agoric/mfig-periodic-endo

# Branch Agoric-mfig-schedule-endo-ci
label base-Agoric-mfig-schedule-endo-ci
pick 15549b529 ci(restore-node): properly use `context.eventName` in script
label Agoric-mfig-schedule-endo-ci
reset base-Agoric-mfig-schedule-endo-ci
merge -C b8d669707 Agoric-mfig-schedule-endo-ci # Merge pull request #7917 from Agoric/mfig-schedule-endo-ci

# Branch Agoric-mfig-ci-notifications
label base-Agoric-mfig-ci-notifications
pick 00eb1f1a5 ci(notify-status): upgrade deprecated actions
pick 25ae4f3e3 ci: send test failure notifications when not a PR
label Agoric-mfig-ci-notifications
reset base-Agoric-mfig-ci-notifications
merge -C 2c5dd59ab Agoric-mfig-ci-notifications # Merge pull request #7934 from Agoric/mfig-ci-notifications

# Branch Agoric-mfig-endo-ci
label base-Agoric-mfig-endo-ci
pick 78fc322e3 ci: properly handle subdependencies for Endo branch override
pick da12531db ci(SwingSet): only test golden snapshot hashes with pinned Endo
label Agoric-mfig-endo-ci
reset base-Agoric-mfig-endo-ci
merge -C b05c226c0 Agoric-mfig-endo-ci # Merge pull request #7958 from Agoric/mfig-endo-ci

# From pull request 8140
pick d0da13cce chore(test-docker-build): break up overlong line

# Branch Agoric-mfig-endo-branch-cache
label base-Agoric-mfig-endo-branch-cache
pick 84101f15e ci(restore-node): avoid clobbering `#endo-branch:` setup
label Agoric-mfig-endo-branch-cache
reset base-Agoric-mfig-endo-branch-cache
merge -C d97cea7f5 Agoric-mfig-endo-branch-cache # Merge pull request #8155 from Agoric/mfig-endo-branch-cache

# Branch Agoric-mfig-staged-endo
label base-Agoric-mfig-staged-endo
pick 393201713 ci(restore-node): detect staged `yarn.lock`, `package.json`
pick 70cb214ec ci(test-dapp): find `notify-status` action in `./agoric-sdk`
label Agoric-mfig-staged-endo
reset base-Agoric-mfig-staged-endo
merge -C 3573f7960 Agoric-mfig-staged-endo # Merge pull request #8168 from Agoric/mfig-staged-endo

# From pull request 8112
pick 49cb43fee docs(test-docker-build): add some useful comments

# Branch Agoric-mhofman-dont-reinstall-deployment-test-deps
label base-Agoric-mhofman-dont-reinstall-deployment-test-deps
pick e68b29dc0 ci(deployment): only install ansible and terraform if not available
label Agoric-mhofman-dont-reinstall-deployment-test-deps
reset base-Agoric-mhofman-dont-reinstall-deployment-test-deps
merge -C 4b52dd61f Agoric-mhofman-dont-reinstall-deployment-test-deps # Merge pull request #8169 from Agoric/mhofman/dont-reinstall-deployment-test-deps

# From pull request 8236
pick feb75933c ci(lint): raise timeout 10m to 15m

# Branch Agoric-mhofman-combine-integration
label base-Agoric-mhofman-combine-integration
pick 50929fbd7 ci: combine integration tests
pick d078297f4 ci: remove mergify pismo queue
pick a9fd671aa ci: add docker upgrade test to mergify
pick e0eb08b5f ci: add checks for merge strategy and linear history
pick 4f343dd75 ci: rename automerge:merge label to automerge:no-update
label Agoric-mhofman-combine-integration
reset base-Agoric-mhofman-combine-integration
merge -C 2ffcef2e7 Agoric-mhofman-combine-integration # Merge pull request #8253 from Agoric/mhofman/combine-integration

# Pull Request #8266
pick d5a33e95f ci(Mergify): configuration update (#8266)

# Branch ci-fix-mergify-matrix-integration-tests-8267-
label base-ci-fix-mergify-matrix-integration-tests-8267-
pick baac7bd19 ci: capture combined integration test results
pick 7b91131f7 ci: add unlabeled pull_request trigger
# pick 62c774089 ci: some integration test failures are not fatal
pick 3e0bc6cc4 ci(mergify): use integration test combined result
label ci-fix-mergify-matrix-integration-tests-8267-
reset base-ci-fix-mergify-matrix-integration-tests-8267-
merge -C eb2d0301c ci-fix-mergify-matrix-integration-tests-8267- # ci: fix mergify matrix integration tests (#8267)

# Pull Request #8275
pick 89a3a851b ci: only satisfy pre-checks once merge requested (#8275)

# Branch ci-fix-integration-test-skip-8283-
label base-ci-fix-integration-test-skip-8283-
pick ad86d60ce ci: carry forward the previous success of an integration test
pick e4b2f484c ci(mergify): require success of integration test
label ci-fix-integration-test-skip-8283-
reset base-ci-fix-integration-test-skip-8283-
merge -C 9450530d5 ci-fix-integration-test-skip-8283- # ci: fix integration test skip (#8283)

# Pull Request #8315
pick 5fcf4525c ci: use a manual check for integration-test-result (#8315)

# Pull Request #8261
pick 3ac36ada7 ci: ensure integration tests run to completion (#8261)

# From pull request #8001
pick 42ecb1508 ci(integration): add `ag-chain-cosmos` output as an artifact

# From pull Request #8314
pick 06aa08a10 ci(registry): publish Endo in CI registry, update versions

# Pull Request #8369
pick 57802f970 ci: jobs compatibility with release branch (#8369)

# Branch Agoric-mhofman-remove-test-bootstrap-upgrade
label base-Agoric-mhofman-remove-test-bootstrap-upgrade
pick d457bb78f chore(upgrade-test): various fixes
pick bd840f4e2 chore(upgrade-test): remove BOOTSTRAP_MODE
label Agoric-mhofman-remove-test-bootstrap-upgrade
reset base-Agoric-mhofman-remove-test-bootstrap-upgrade
merge -C 51399d19e Agoric-mhofman-remove-test-bootstrap-upgrade # Merge pull request #8598 from Agoric/mhofman/remove-test-bootstrap-upgrade

# From pull request #8649
pick a926685cf ci: defer Loadgen compatibility

# Branch Agoric-mfig-ci-external-prs
label base-Agoric-mfig-ci-external-prs
pick 45e654887 ci(linear-history): fix external PR sha references
pick d2ae9c7b1 ci: manipulate checks within `workflow_run`
# pick 34fe9a469 test(upgrade-test): tolerate running after `a3p:main` zoe upgrade
pick 5395cda4a ci(mergify-ready): stub `wait-integration-pre-checks` to appease required jobs
label Agoric-mfig-ci-external-prs
reset base-Agoric-mfig-ci-external-prs
merge -C 05aeff247 Agoric-mfig-ci-external-prs # Merge pull request #8731 from Agoric/mfig-ci-external-prs

# Branch Agoric-raphdev-secmd
label base-Agoric-raphdev-secmd
pick 8bdc349b0 fix H1 link in SECURITY.md
label Agoric-raphdev-secmd
reset base-Agoric-raphdev-secmd
merge -C 73364fab9 Agoric-raphdev-secmd # Merge pull request #8734 from Agoric/raphdev-secmd

# Branch Agoric-8605-local-a3p
label base-Agoric-8605-local-a3p
pick eee7bfa94 lint: disable jsdoc/require-param-type for .ts
# pick 845ba0da3 chore(types): import .js for .ts modules
pick edcf2f4c9 chore(deps): bump commander to 11.1
# pick 23ecf28bf chore(deps): bump @types/node to 18
pick d8b84102a feat: a3p-integration package
fixup ca765ec57 chore(ci): use synthetic-chain build config  # From pull request #8744
fixup 7fcd59c95 chore(a3p): upgrade synthetic-chain # From pull request #8754
fixup d41103e3f fixup! feat: a3p-integration package # Manually authored
pick fea3198cb ci: run a3p-integration instead of upgrade-tests
fixup 663871d01 chore(ci): integration uses synthetic-chain build command # From pull request #8744
pick d8690bff9 chore: remove old upgrade-tests
label Agoric-8605-local-a3p
reset base-Agoric-8605-local-a3p
merge -C df3d0a788 Agoric-8605-local-a3p # Merge pull request #8635 from Agoric/8605-local-a3p

# Branch Agoric-mhofman-clean-docker-tags
label base-Agoric-mhofman-clean-docker-tags
pick e5302c694 chore(deployment): remove unused docker-push make targets
pick 3ac11031d chore: default deployment docker tag to unreleased
label Agoric-mhofman-clean-docker-tags
reset base-Agoric-mhofman-clean-docker-tags
merge -C f85d35b67 Agoric-mhofman-clean-docker-tags # Merge pull request #8760 from Agoric/mhofman/clean-docker-tags
```

### Security Considerations

None

### Scaling Considerations

None

### Documentation Considerations

None

### Testing Considerations

Yes! All CI tests should keep passing

### Upgrade Considerations

This does now yet change any upgrade logic, but does update the upgrade integration tests to the latest and greatest

### CODE REVIEW

**Review by raphdev — APPROVED** [review]
I was added due to codeowners on `SECURITY.md`, it has the recent fix, so approving. At a glance everything else looks good too.

**Comment by mhofman** [comment]
I expect the last few commits to change (the fixups in particular) once https://github.com/Agoric/agoric-3-proposals/pull/58 has landed and a new version of `synthetic-chain` is published (and used on master)

**Comment by mhofman** [comment]
This is now ready for final review.

To measure against the goal of catching up the GH Actions workflows, you can use https://github.com/Agoric/agoric-sdk/compare/master..mhofman/update-release-ci to compare `.github/`, `a3p-integration/` and `.mergify.yml` between this branch and `master`

**Comment by mhofman** [comment]
I plan on adding https://github.com/Agoric/agoric-sdk/pull/8760 to the cherry-picks once it lands

**Review by gibson042 — APPROVED** [review]
> To measure against the goal of catching up the GH Actions workflows, you can use https://github.com/Agoric/agoric-sdk/compare/master..mhofman/update-release-ci to compare `.github/`, `a3p-integration/` and `.mergify.yml` between this branch and `master`

The relevant directories do indeed align. Other changes do as well... affected files on the release side are still missing some changes such as those from #8205, but those are very disruptive and unnecessary here anyway. LGTM!

**Pull request merged**
