### PR TITLE
fix(smart-wallet): invitation issuer is remote

### PR DESCRIPTION
**Pull request by Chris-Hibbert**
refs: #6084

## Description

Dan and I were trying to make progress on voting based on top of #6084, and ran into two issues, but the PR merged before we could suggestion this correction.

missing E() around an invitationIssuer

(I originally included updating decentral-psm-config to use smartwallet, but that's maybe not for master).

### Security Considerations

None

### Documentation Considerations

None

### Testing Considerations

None

### CODE REVIEW

**Review by dtribble — APPROVED** [review]
LGTM

**Review by turadg — COMMENTED** [review]
Change is okay but I think before merge we should find a way to prevent this error in the future. I can do that if you prefer.

Looks like this type is wrong,
https://github.com/Agoric/agoric-sdk/blob/b120bbbe7755b13e678ebba457cd0fb2d73112ca/packages/zoe/src/zoeService/types.js#L54-L58

Should be `FarRef<Issuer>`?

Is there any way to have this fail in Ava without running a full swingset test?

**Comment by Chris-Hibbert** [comment]
> Change is okay but I think before merge we should find a way to prevent this error in the future. I can do that if you prefer.

It's your PR. Feel free to drop the `automerge:` label.

**Comment by Chris-Hibbert** [comment]
> Change is okay but I think before merge we should find a way to prevent this error in the future. I can do that if you prefer.

I removed `automerge:`.  would you prefer to make a new PR?

**Comment by turadg** [comment]
@Chris-Hibbert fixing the type was a rabbit hole. I think this is good to merge since there's no Ava test and the TS will get fixed over time.

I added back the automerge and made it "squash" to the PR title, which I've updated.

**Review by turadg — APPROVED** [review]

**Pull request merged**
