### PR TITLE
feat(store): reconcile with endo #1554

### PR DESCRIPTION
**Pull request by erights**
Stay in sync with changes in https://github.com/endojs/endo/pull/1554

See also https://github.com/Agoric/agoric-sdk/pull/7408

### CODE REVIEW

**Review by turadg — APPROVED** [review]
I think this is coming soon with the Endo sync so there will be some churn by landing this. But I suppose the value of having this debugging info is urgent enough to warrant that.

**Comment by erights** [comment]
> I think this is coming soon with the Endo sync so there will be some churn by landing this. But I suppose the value of having this debugging info is urgent enough to warrant that.

I'm actually trying to reduce churn, to minimize semantic differences that happen at the time of switchover. 

Attn @michaelfig , if this is hurting rather than helping your reconciliation efforts, please let me know. Otherwise I will continue to sync changes between the redundant code across the repos, in order to continue minimizing that churn.

**Comment by michaelfig** [comment]
> Attn @michaelfig , if this is hurting rather than helping your reconciliation efforts, please let me know. Otherwise I will continue to sync changes between the redundant code across the repos, in order to continue minimizing that churn.

My reconciliation efforts are unaffected.  I am relying upon you to decide when the code in the SDK should switch from using an `@agoric/*` package to its (after my release) migrated `@endo/*`.  All I'm doing is upgrading the existing `@endo` references, not migrating new ones.

**Comment by erights** [comment]
> I am relying upon you to ...

Will do. Thanks.

**Pull request merged**
