### PR TITLE
Enable lerna version with Conventional Commits

### LINKED ISSUE #639: Use lerna for versioning and CHANGELOGs
Without adopting all of Lerna, we can at least use it for maintaining the NPM releases.  I'm assuming we want independent semver based on [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

Here is how to get started to reproduce what I have in #640.

```sh
# Install lerna globally
yarn global add lerna @lerna/version

# Make a prerelease of all the packages, based on Conventional Commits
# Test what this command does on a branch (this is what I did to generate
# 639-lerna-version)
git checkout -b 639-lerna-version
lerna version --conventional-commits --conventional-prerelease --no-push -m 'chore: publish'
git push -u origin 639-lerna-version
```

When you're ready for real (committing and pushing tags and CHANGELOGs to master)
you can run just the following:

```sh
git checkout master
lerna version --conventional-commits --conventional-prerelease -m 'chore: publish'

# Publish all the changed packages to NPM.
lerna publish

# Later, when the packages are stable, make a graduated release using
# --conventional-graduated instead of --conventional-prerelease.
```

### PR DESCRIPTION
**Pull request by michaelfig**
Closes #639

This is no longer a demonstration of the generated result of running the test steps in #639.

Instead, it is the changes needed to the monorepo in order to enable `lerna` usage as described in `MAINTAINERS.md`.  Use:

```js
yarn lerna version --no-push --conventional-prerelease
```

to do the changes that used to be part of this commit.

---

Note that the following tags are also generated:

```
soil:agoric-sdk michael$ git tag -l | grep alpha
@agoric/assert@0.0.2-alpha.1
@agoric/bundle-source@1.1.0-alpha.1
@agoric/captp@1.2.1-alpha.1
@agoric/cosmic-swingset@0.12.0-alpha.1
@agoric/default-evaluate-options@0.3.1-alpha.1
@agoric/deployment@1.17.0-alpha.1
@agoric/ertp@0.3.2-alpha.1
@agoric/evaluate@2.2.1-alpha.1
@agoric/eventual-send@0.6.0-alpha.1
@agoric/make-promise@0.0.2-alpha.1
@agoric/marshal@0.1.3-alpha.1
@agoric/pixel-demo@0.0.4-alpha.1
@agoric/registrar@0.0.2-alpha.1
@agoric/same-structure@0.0.2-alpha.1
@agoric/sharing-service@0.0.2-alpha.1
@agoric/simple-exchange-frontend@0.0.2-alpha.1
@agoric/spawner@0.1.0-alpha.1
@agoric/store@0.0.2-alpha.1
@agoric/swing-store-lmdb@0.1.1-alpha.1
@agoric/swing-store-simple@0.1.1-alpha.1
@agoric/swingset-vat@0.4.0-alpha.1
@agoric/tame-metering@1.1.0-alpha.1
@agoric/transform-eventual-send@1.2.0-alpha.1
@agoric/transform-metering@1.2.0-alpha.1
@agoric/wallet-frontend@0.1.2-alpha.1
@agoric/weak-store@0.0.2-alpha.1
@agoric/zoe@0.3.0-alpha.1
agoric-dapp-api@0.1.1-alpha.1
agoric-dapp-contract@0.1.1-alpha.1
agoric-dapp-ui@0.0.2-alpha.1
agoric-servers@0.1.0-alpha.1
agoric@0.4.0-alpha.1
autoswap-frontend@0.0.2-alpha.1
swingset-runner@0.1.1-alpha.1
soil:agoric-sdk michael$ 
```

### CODE REVIEW

**Comment by michaelfig** [comment]
Note that besides the `lerna.json` addition, we probably need to rename `agoric-dapp-*` to `@agoric/dapp-*` and `autoswap-frontend` and `swingset-runner` to have the `@agoric` prefix as well.

**Comment by michaelfig** [comment]
All the commits in this PR except for the last one (the actual `chore: publish`) are intended to land.

Especially `scripts/version.sh` which allows something as easy as:

```sh
scripts/version.sh --conventional-prerelease --no-push
```

**Review by warner — APPROVED** [review]
Seems reasonable to me. A few questions:

* I think JF suggested that we could write scripts or top-level `package.json` commands for all the ways we might invoke `lerna`, so we could avoid requiring devs to install it globally.
* How does `lerna` decide which packages need to be released? And what version number to use for each? I'm all for automating this stuff, we're definitely hurting right now, I'd just like to know how it works. We have packages at very different versions (some 2.x, some 0.2.x), and the only examples I've seen of these tools is in projects like `eslint` where every package is released with the same version and at the same time.
* I've been in the habit of PGP signing some release tarballs (maybe swingset and `harden`), but I'm willing to give that up for a while for the sake of automating this stuff. Likewise for the signed git tags.
* Could you add a `maintainers.txt` or something with instructions for us to follow, both for "how to make a commit" (which I think wants to have a changelog snippet somewhere), and "how to make a release".

**Comment by michaelfig** [comment]
> * I think JF suggested that we could write scripts or top-level `package.json` commands for all the ways we might invoke `lerna`, so we could avoid requiring devs to install it globally.

Okay, I'll do that.

> * How does `lerna` decide which packages need to be released? And what version number to use for each? I'm all for automating this stuff, we're definitely hurting right now, I'd just like to know how it works. We have packages at very different versions (some 2.x, some 0.2.x), and the only examples I've seen of these tools is in projects like `eslint` where every package is released with the same version and at the same time.

This is where Conventional Commits come in.  `lerna` scans the set of commits to a given package since the last release, and:

* If there were any conforming conventional commits that (oversimplified) also match `!:` (like `fix(foo)!: this is a breaking change`), then the package's major version is bumped.
* If not, and there were conventional commits that match `feat`, then the package's minor version is bumped.
* If not, and there were conventional commits that match `fix`, then the package's patch is bumped.

Thus, we won't be bumping the version unless we use conventional commits, but that's just a matter of educating whomever actually writes those commits to DTRT.  The Github Action I'm adding that warns you when you don't write conventional commits will point them out to you, and suggest you read the fine manual.

> * I've been in the habit of PGP signing some release tarballs (maybe swingset and `harden`), but I'm willing to give that up for a while for the sake of automating this stuff. Likewise for the signed git tags.

I do sign the git tags, but with my GPG key, not yours. 😉 

> * Could you add a `maintainers.txt` or something with instructions for us to follow, both for "how to make a commit" (which I think wants to have a changelog snippet somewhere), and "how to make a release".

Gladly!

**Pull request merged**
