### PR TITLE
refactor(ERTP): rename `extent` to `value`

### LINKED ISSUE #1293: [ERTP] Rename `extent` to `value`
**What is the Problem Being Solved?**

@kriskowal said: "ERTP terminology feels solid to me. Mint, issuer, purse, amount, and payment are all good terms. I found `extent` odd and suspect that `value` would be less odd for fungible cases and forgivable for non-fungible cases."

I (Kate) agree with this. 

@Chris-Hibbert says: "For me, the crucial test is how it works with 'amount' (or whatever we might rename that to.) 'extent' feels distinctly different, while 'value' is too confusable with 'amount'. I think we may have tried this combo before, and value/amount didn't have the right contrast.
I realize that 'extent' is rarer as English vocab, but it's not hard to get used to."

**Description of the Design**
Rename `extent` to `value`

**Security Considerations**
None

**Test Plan**
Current unit tests

### PR DESCRIPTION
**Pull request by katelynsills**
Rename `extent` to `value`

Closes #1293

### CODE REVIEW

**Comment by katelynsills** [comment]
Got a verbal approval from @erights this morning

**Review by erights — APPROVED** [review]
yup LGTM

**Review by Chris-Hibbert — APPROVED** [review]

**Comment by kriskowal** [comment]
I like the results a lot. Thanks for taking my feedback into consideration!

**Comment by katelynsills** [comment]
> I like the results a lot. Thanks for taking my feedback into consideration!

Thanks so much for the feedback! I think it reads much better!

**Pull request merged**
