### PR TITLE
chore(deployment): Use latest Node 14 in docker images

### PR DESCRIPTION
**Pull request by mhofman**
refs: #4459

## Description

#4420 requires a more recent node version, and the `deployment` package was hard coding `14.15`. Switch to the latest 14 instead.

### CODE REVIEW

**Comment by turadg** [comment]
I think we also need to update other references of `14.15.0` to `14.17.0` or later. https://github.com/Agoric/agoric-sdk/search?q=14.15

**Review by michaelfig — APPROVED** [review]
LGTM!

**Comment by mhofman** [comment]
> I think we also need to update other references of `14.15.0` to `14.17.0` or later. https://github.com/Agoric/agoric-sdk/search?q=14.15

I think all other occurrences are fine, they're either doc or already have a `>=`

**Comment by turadg** [comment]
> I think all other occurrences are fine, they're either doc or already have a >=

They won't break but they're all inaccurate, right? We now require `>= 14.17`, not `14.15` as declared. 

For example, the [docs on how to contribute](https://github.com/Agoric/agoric-sdk/blob/639b8c7abf8528109068fdf184b6354ab4e660e7/CONTRIBUTING.md?plain=1#L11) say,
```
 - [node](https://nodejs.org/) 14.15.0 or higher
```

**Comment by mhofman** [comment]
Yeah I guess. I'm willing to live with that until we move to Node 16

**Pull request merged**
